/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/_index'
import { Route as LoginIndexImport } from './routes/login/index'
import { Route as DashboardIndexImport } from './routes/dashboard/index'
import { Route as IndexIndexImport } from './routes/_index/index'
import { Route as ScaffoldConsultationImport } from './routes/scaffold/consultation'
import { Route as DashboardWalletIndexImport } from './routes/dashboard/wallet/index'
import { Route as DashboardProfileIndexImport } from './routes/dashboard/profile/index'
import { Route as DashboardDoctorsIndexImport } from './routes/dashboard/doctors/index'
import { Route as DashboardChatsIndexImport } from './routes/dashboard/chats/index'
import { Route as DashboardChatsDoctorIdIndexImport } from './routes/dashboard/chats/$doctorId/index'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  id: '/_index',
  getParentRoute: () => rootRoute,
} as any)

const LoginIndexRoute = LoginIndexImport.update({
  path: '/login/',
  getParentRoute: () => rootRoute,
} as any)

const DashboardIndexRoute = DashboardIndexImport.update({
  path: '/dashboard/',
  getParentRoute: () => rootRoute,
} as any)

const IndexIndexRoute = IndexIndexImport.update({
  path: '/',
  getParentRoute: () => IndexRoute,
} as any)

const ScaffoldConsultationRoute = ScaffoldConsultationImport.update({
  path: '/scaffold/consultation',
  getParentRoute: () => rootRoute,
} as any)

const DashboardWalletIndexRoute = DashboardWalletIndexImport.update({
  path: '/dashboard/wallet/',
  getParentRoute: () => rootRoute,
} as any)

const DashboardProfileIndexRoute = DashboardProfileIndexImport.update({
  path: '/dashboard/profile/',
  getParentRoute: () => rootRoute,
} as any)

const DashboardDoctorsIndexRoute = DashboardDoctorsIndexImport.update({
  path: '/dashboard/doctors/',
  getParentRoute: () => rootRoute,
} as any)

const DashboardChatsIndexRoute = DashboardChatsIndexImport.update({
  path: '/dashboard/chats/',
  getParentRoute: () => rootRoute,
} as any)

const DashboardChatsDoctorIdIndexRoute =
  DashboardChatsDoctorIdIndexImport.update({
    path: '/dashboard/chats/$doctorId/',
    getParentRoute: () => rootRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_index': {
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/scaffold/consultation': {
      preLoaderRoute: typeof ScaffoldConsultationImport
      parentRoute: typeof rootRoute
    }
    '/_index/': {
      preLoaderRoute: typeof IndexIndexImport
      parentRoute: typeof IndexImport
    }
    '/dashboard/': {
      preLoaderRoute: typeof DashboardIndexImport
      parentRoute: typeof rootRoute
    }
    '/login/': {
      preLoaderRoute: typeof LoginIndexImport
      parentRoute: typeof rootRoute
    }
    '/dashboard/chats/': {
      preLoaderRoute: typeof DashboardChatsIndexImport
      parentRoute: typeof rootRoute
    }
    '/dashboard/doctors/': {
      preLoaderRoute: typeof DashboardDoctorsIndexImport
      parentRoute: typeof rootRoute
    }
    '/dashboard/profile/': {
      preLoaderRoute: typeof DashboardProfileIndexImport
      parentRoute: typeof rootRoute
    }
    '/dashboard/wallet/': {
      preLoaderRoute: typeof DashboardWalletIndexImport
      parentRoute: typeof rootRoute
    }
    '/dashboard/chats/$doctorId/': {
      preLoaderRoute: typeof DashboardChatsDoctorIdIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  IndexRoute.addChildren([IndexIndexRoute]),
  ScaffoldConsultationRoute,
  DashboardIndexRoute,
  LoginIndexRoute,
  DashboardChatsIndexRoute,
  DashboardDoctorsIndexRoute,
  DashboardProfileIndexRoute,
  DashboardWalletIndexRoute,
  DashboardChatsDoctorIdIndexRoute,
])

/* prettier-ignore-end */
