/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as PagesImport } from './routes/_pages'
import { Route as DoctorImport } from './routes/_doctor'
import { Route as AppImport } from './routes/_app'
import { Route as PagesPagesImport } from './routes/_pages/_pages'
import { Route as AppDoctorImport } from './routes/_app/_doctor'
import { Route as PagesPagesIndexImport } from './routes/_pages/_pages/index'
import { Route as AppDashboardIndexImport } from './routes/_app/dashboard/index'
import { Route as AppAuthSignUpImport } from './routes/_app/auth/sign-up'
import { Route as AppAuthSignInImport } from './routes/_app/auth/sign-in'
import { Route as AppDashboardWalletIndexImport } from './routes/_app/dashboard/wallet/index'
import { Route as AppDashboardScheduleIndexImport } from './routes/_app/dashboard/schedule/index'
import { Route as AppDashboardProfileIndexImport } from './routes/_app/dashboard/profile/index'
import { Route as AppDashboardDoctorsIndexImport } from './routes/_app/dashboard/doctors/index'
import { Route as AppDoctorDoctorIndexImport } from './routes/_app/_doctor/doctor/index'
import { Route as AppConsultationConsultationsIndexImport } from './routes/_app/_consultation/consultations/index'
import { Route as AppDashboardChatsDoctorIdIndexImport } from './routes/_app/dashboard/chats/$doctorId/index'
import { Route as AppDoctorDoctorSupportIndexImport } from './routes/_app/_doctor/doctor/support/index'
import { Route as AppDoctorDoctorPatientsIndexImport } from './routes/_app/_doctor/doctor/patients/index'
import { Route as AppDoctorDoctorMessageIndexImport } from './routes/_app/_doctor/doctor/message/index'
import { Route as AppDoctorDoctorLabIndexImport } from './routes/_app/_doctor/doctor/lab/index'
import { Route as AppDoctorDoctorAppointmentsIndexImport } from './routes/_app/_doctor/doctor/appointments/index'
import { Route as AppDashboardDoctorsProfileDoctorIdIndexImport } from './routes/_app/dashboard/doctors/profile/$doctorId/index'
import { Route as AppDoctorDoctorMessagePatientIdIndexImport } from './routes/_app/_doctor/doctor/message/$patientId/index'

// Create/Update Routes

const PagesRoute = PagesImport.update({
  id: '/_pages',
  getParentRoute: () => rootRoute,
} as any)

const DoctorRoute = DoctorImport.update({
  id: '/_doctor',
  getParentRoute: () => rootRoute,
} as any)

const AppRoute = AppImport.update({
  id: '/_app',
  getParentRoute: () => rootRoute,
} as any)

const PagesPagesRoute = PagesPagesImport.update({
  id: '/_pages',
  getParentRoute: () => PagesRoute,
} as any)

const AppDoctorRoute = AppDoctorImport.update({
  id: '/_doctor',
  getParentRoute: () => AppRoute,
} as any)

const PagesPagesIndexRoute = PagesPagesIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PagesPagesRoute,
} as any)

const AppDashboardIndexRoute = AppDashboardIndexImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => AppRoute,
} as any)

const AppAuthSignUpRoute = AppAuthSignUpImport.update({
  id: '/auth/sign-up',
  path: '/auth/sign-up',
  getParentRoute: () => AppRoute,
} as any)

const AppAuthSignInRoute = AppAuthSignInImport.update({
  id: '/auth/sign-in',
  path: '/auth/sign-in',
  getParentRoute: () => AppRoute,
} as any)

const AppDashboardWalletIndexRoute = AppDashboardWalletIndexImport.update({
  id: '/dashboard/wallet/',
  path: '/dashboard/wallet/',
  getParentRoute: () => AppRoute,
} as any)

const AppDashboardScheduleIndexRoute = AppDashboardScheduleIndexImport.update({
  id: '/dashboard/schedule/',
  path: '/dashboard/schedule/',
  getParentRoute: () => AppRoute,
} as any)

const AppDashboardProfileIndexRoute = AppDashboardProfileIndexImport.update({
  id: '/dashboard/profile/',
  path: '/dashboard/profile/',
  getParentRoute: () => AppRoute,
} as any)

const AppDashboardDoctorsIndexRoute = AppDashboardDoctorsIndexImport.update({
  id: '/dashboard/doctors/',
  path: '/dashboard/doctors/',
  getParentRoute: () => AppRoute,
} as any)

const AppDoctorDoctorIndexRoute = AppDoctorDoctorIndexImport.update({
  id: '/doctor/',
  path: '/doctor/',
  getParentRoute: () => AppDoctorRoute,
} as any)

const AppConsultationConsultationsIndexRoute =
  AppConsultationConsultationsIndexImport.update({
    id: '/_consultation/consultations/',
    path: '/consultations/',
    getParentRoute: () => AppRoute,
  } as any)

const AppDashboardChatsDoctorIdIndexRoute =
  AppDashboardChatsDoctorIdIndexImport.update({
    id: '/dashboard/chats/$doctorId/',
    path: '/dashboard/chats/$doctorId/',
    getParentRoute: () => AppRoute,
  } as any)

const AppDoctorDoctorSupportIndexRoute =
  AppDoctorDoctorSupportIndexImport.update({
    id: '/doctor/support/',
    path: '/doctor/support/',
    getParentRoute: () => AppDoctorRoute,
  } as any)

const AppDoctorDoctorPatientsIndexRoute =
  AppDoctorDoctorPatientsIndexImport.update({
    id: '/doctor/patients/',
    path: '/doctor/patients/',
    getParentRoute: () => AppDoctorRoute,
  } as any)

const AppDoctorDoctorMessageIndexRoute =
  AppDoctorDoctorMessageIndexImport.update({
    id: '/doctor/message/',
    path: '/doctor/message/',
    getParentRoute: () => AppDoctorRoute,
  } as any)

const AppDoctorDoctorLabIndexRoute = AppDoctorDoctorLabIndexImport.update({
  id: '/doctor/lab/',
  path: '/doctor/lab/',
  getParentRoute: () => AppDoctorRoute,
} as any)

const AppDoctorDoctorAppointmentsIndexRoute =
  AppDoctorDoctorAppointmentsIndexImport.update({
    id: '/doctor/appointments/',
    path: '/doctor/appointments/',
    getParentRoute: () => AppDoctorRoute,
  } as any)

const AppDashboardDoctorsProfileDoctorIdIndexRoute =
  AppDashboardDoctorsProfileDoctorIdIndexImport.update({
    id: '/dashboard/doctors/profile/$doctorId/',
    path: '/dashboard/doctors/profile/$doctorId/',
    getParentRoute: () => AppRoute,
  } as any)

const AppDoctorDoctorMessagePatientIdIndexRoute =
  AppDoctorDoctorMessagePatientIdIndexImport.update({
    id: '/doctor/message/$patientId/',
    path: '/doctor/message/$patientId/',
    getParentRoute: () => AppDoctorRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AppImport
      parentRoute: typeof rootRoute
    }
    '/_doctor': {
      id: '/_doctor'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof DoctorImport
      parentRoute: typeof rootRoute
    }
    '/_pages': {
      id: '/_pages'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof PagesImport
      parentRoute: typeof rootRoute
    }
    '/_app/_doctor': {
      id: '/_app/_doctor'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AppDoctorImport
      parentRoute: typeof AppImport
    }
    '/_pages/_pages': {
      id: '/_pages/_pages'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof PagesPagesImport
      parentRoute: typeof PagesImport
    }
    '/_app/auth/sign-in': {
      id: '/_app/auth/sign-in'
      path: '/auth/sign-in'
      fullPath: '/auth/sign-in'
      preLoaderRoute: typeof AppAuthSignInImport
      parentRoute: typeof AppImport
    }
    '/_app/auth/sign-up': {
      id: '/_app/auth/sign-up'
      path: '/auth/sign-up'
      fullPath: '/auth/sign-up'
      preLoaderRoute: typeof AppAuthSignUpImport
      parentRoute: typeof AppImport
    }
    '/_app/dashboard/': {
      id: '/_app/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardIndexImport
      parentRoute: typeof AppImport
    }
    '/_pages/_pages/': {
      id: '/_pages/_pages/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PagesPagesIndexImport
      parentRoute: typeof PagesPagesImport
    }
    '/_app/_consultation/consultations/': {
      id: '/_app/_consultation/consultations/'
      path: '/consultations'
      fullPath: '/consultations'
      preLoaderRoute: typeof AppConsultationConsultationsIndexImport
      parentRoute: typeof AppImport
    }
    '/_app/_doctor/doctor/': {
      id: '/_app/_doctor/doctor/'
      path: '/doctor'
      fullPath: '/doctor'
      preLoaderRoute: typeof AppDoctorDoctorIndexImport
      parentRoute: typeof AppDoctorImport
    }
    '/_app/dashboard/doctors/': {
      id: '/_app/dashboard/doctors/'
      path: '/dashboard/doctors'
      fullPath: '/dashboard/doctors'
      preLoaderRoute: typeof AppDashboardDoctorsIndexImport
      parentRoute: typeof AppImport
    }
    '/_app/dashboard/profile/': {
      id: '/_app/dashboard/profile/'
      path: '/dashboard/profile'
      fullPath: '/dashboard/profile'
      preLoaderRoute: typeof AppDashboardProfileIndexImport
      parentRoute: typeof AppImport
    }
    '/_app/dashboard/schedule/': {
      id: '/_app/dashboard/schedule/'
      path: '/dashboard/schedule'
      fullPath: '/dashboard/schedule'
      preLoaderRoute: typeof AppDashboardScheduleIndexImport
      parentRoute: typeof AppImport
    }
    '/_app/dashboard/wallet/': {
      id: '/_app/dashboard/wallet/'
      path: '/dashboard/wallet'
      fullPath: '/dashboard/wallet'
      preLoaderRoute: typeof AppDashboardWalletIndexImport
      parentRoute: typeof AppImport
    }
    '/_app/_doctor/doctor/appointments/': {
      id: '/_app/_doctor/doctor/appointments/'
      path: '/doctor/appointments'
      fullPath: '/doctor/appointments'
      preLoaderRoute: typeof AppDoctorDoctorAppointmentsIndexImport
      parentRoute: typeof AppDoctorImport
    }
    '/_app/_doctor/doctor/lab/': {
      id: '/_app/_doctor/doctor/lab/'
      path: '/doctor/lab'
      fullPath: '/doctor/lab'
      preLoaderRoute: typeof AppDoctorDoctorLabIndexImport
      parentRoute: typeof AppDoctorImport
    }
    '/_app/_doctor/doctor/message/': {
      id: '/_app/_doctor/doctor/message/'
      path: '/doctor/message'
      fullPath: '/doctor/message'
      preLoaderRoute: typeof AppDoctorDoctorMessageIndexImport
      parentRoute: typeof AppDoctorImport
    }
    '/_app/_doctor/doctor/patients/': {
      id: '/_app/_doctor/doctor/patients/'
      path: '/doctor/patients'
      fullPath: '/doctor/patients'
      preLoaderRoute: typeof AppDoctorDoctorPatientsIndexImport
      parentRoute: typeof AppDoctorImport
    }
    '/_app/_doctor/doctor/support/': {
      id: '/_app/_doctor/doctor/support/'
      path: '/doctor/support'
      fullPath: '/doctor/support'
      preLoaderRoute: typeof AppDoctorDoctorSupportIndexImport
      parentRoute: typeof AppDoctorImport
    }
    '/_app/dashboard/chats/$doctorId/': {
      id: '/_app/dashboard/chats/$doctorId/'
      path: '/dashboard/chats/$doctorId'
      fullPath: '/dashboard/chats/$doctorId'
      preLoaderRoute: typeof AppDashboardChatsDoctorIdIndexImport
      parentRoute: typeof AppImport
    }
    '/_app/_doctor/doctor/message/$patientId/': {
      id: '/_app/_doctor/doctor/message/$patientId/'
      path: '/doctor/message/$patientId'
      fullPath: '/doctor/message/$patientId'
      preLoaderRoute: typeof AppDoctorDoctorMessagePatientIdIndexImport
      parentRoute: typeof AppDoctorImport
    }
    '/_app/dashboard/doctors/profile/$doctorId/': {
      id: '/_app/dashboard/doctors/profile/$doctorId/'
      path: '/dashboard/doctors/profile/$doctorId'
      fullPath: '/dashboard/doctors/profile/$doctorId'
      preLoaderRoute: typeof AppDashboardDoctorsProfileDoctorIdIndexImport
      parentRoute: typeof AppImport
    }
  }
}

// Create and export the route tree

interface AppDoctorRouteChildren {
  AppDoctorDoctorIndexRoute: typeof AppDoctorDoctorIndexRoute
  AppDoctorDoctorAppointmentsIndexRoute: typeof AppDoctorDoctorAppointmentsIndexRoute
  AppDoctorDoctorLabIndexRoute: typeof AppDoctorDoctorLabIndexRoute
  AppDoctorDoctorMessageIndexRoute: typeof AppDoctorDoctorMessageIndexRoute
  AppDoctorDoctorPatientsIndexRoute: typeof AppDoctorDoctorPatientsIndexRoute
  AppDoctorDoctorSupportIndexRoute: typeof AppDoctorDoctorSupportIndexRoute
  AppDoctorDoctorMessagePatientIdIndexRoute: typeof AppDoctorDoctorMessagePatientIdIndexRoute
}

const AppDoctorRouteChildren: AppDoctorRouteChildren = {
  AppDoctorDoctorIndexRoute: AppDoctorDoctorIndexRoute,
  AppDoctorDoctorAppointmentsIndexRoute: AppDoctorDoctorAppointmentsIndexRoute,
  AppDoctorDoctorLabIndexRoute: AppDoctorDoctorLabIndexRoute,
  AppDoctorDoctorMessageIndexRoute: AppDoctorDoctorMessageIndexRoute,
  AppDoctorDoctorPatientsIndexRoute: AppDoctorDoctorPatientsIndexRoute,
  AppDoctorDoctorSupportIndexRoute: AppDoctorDoctorSupportIndexRoute,
  AppDoctorDoctorMessagePatientIdIndexRoute:
    AppDoctorDoctorMessagePatientIdIndexRoute,
}

const AppDoctorRouteWithChildren = AppDoctorRoute._addFileChildren(
  AppDoctorRouteChildren,
)

interface AppRouteChildren {
  AppDoctorRoute: typeof AppDoctorRouteWithChildren
  AppAuthSignInRoute: typeof AppAuthSignInRoute
  AppAuthSignUpRoute: typeof AppAuthSignUpRoute
  AppDashboardIndexRoute: typeof AppDashboardIndexRoute
  AppConsultationConsultationsIndexRoute: typeof AppConsultationConsultationsIndexRoute
  AppDashboardDoctorsIndexRoute: typeof AppDashboardDoctorsIndexRoute
  AppDashboardProfileIndexRoute: typeof AppDashboardProfileIndexRoute
  AppDashboardScheduleIndexRoute: typeof AppDashboardScheduleIndexRoute
  AppDashboardWalletIndexRoute: typeof AppDashboardWalletIndexRoute
  AppDashboardChatsDoctorIdIndexRoute: typeof AppDashboardChatsDoctorIdIndexRoute
  AppDashboardDoctorsProfileDoctorIdIndexRoute: typeof AppDashboardDoctorsProfileDoctorIdIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppDoctorRoute: AppDoctorRouteWithChildren,
  AppAuthSignInRoute: AppAuthSignInRoute,
  AppAuthSignUpRoute: AppAuthSignUpRoute,
  AppDashboardIndexRoute: AppDashboardIndexRoute,
  AppConsultationConsultationsIndexRoute:
    AppConsultationConsultationsIndexRoute,
  AppDashboardDoctorsIndexRoute: AppDashboardDoctorsIndexRoute,
  AppDashboardProfileIndexRoute: AppDashboardProfileIndexRoute,
  AppDashboardScheduleIndexRoute: AppDashboardScheduleIndexRoute,
  AppDashboardWalletIndexRoute: AppDashboardWalletIndexRoute,
  AppDashboardChatsDoctorIdIndexRoute: AppDashboardChatsDoctorIdIndexRoute,
  AppDashboardDoctorsProfileDoctorIdIndexRoute:
    AppDashboardDoctorsProfileDoctorIdIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface PagesPagesRouteChildren {
  PagesPagesIndexRoute: typeof PagesPagesIndexRoute
}

const PagesPagesRouteChildren: PagesPagesRouteChildren = {
  PagesPagesIndexRoute: PagesPagesIndexRoute,
}

const PagesPagesRouteWithChildren = PagesPagesRoute._addFileChildren(
  PagesPagesRouteChildren,
)

interface PagesRouteChildren {
  PagesPagesRoute: typeof PagesPagesRouteWithChildren
}

const PagesRouteChildren: PagesRouteChildren = {
  PagesPagesRoute: PagesPagesRouteWithChildren,
}

const PagesRouteWithChildren = PagesRoute._addFileChildren(PagesRouteChildren)

export interface FileRoutesByFullPath {
  '': typeof PagesPagesRouteWithChildren
  '/auth/sign-in': typeof AppAuthSignInRoute
  '/auth/sign-up': typeof AppAuthSignUpRoute
  '/dashboard': typeof AppDashboardIndexRoute
  '/': typeof PagesPagesIndexRoute
  '/consultations': typeof AppConsultationConsultationsIndexRoute
  '/doctor': typeof AppDoctorDoctorIndexRoute
  '/dashboard/doctors': typeof AppDashboardDoctorsIndexRoute
  '/dashboard/profile': typeof AppDashboardProfileIndexRoute
  '/dashboard/schedule': typeof AppDashboardScheduleIndexRoute
  '/dashboard/wallet': typeof AppDashboardWalletIndexRoute
  '/doctor/appointments': typeof AppDoctorDoctorAppointmentsIndexRoute
  '/doctor/lab': typeof AppDoctorDoctorLabIndexRoute
  '/doctor/message': typeof AppDoctorDoctorMessageIndexRoute
  '/doctor/patients': typeof AppDoctorDoctorPatientsIndexRoute
  '/doctor/support': typeof AppDoctorDoctorSupportIndexRoute
  '/dashboard/chats/$doctorId': typeof AppDashboardChatsDoctorIdIndexRoute
  '/doctor/message/$patientId': typeof AppDoctorDoctorMessagePatientIdIndexRoute
  '/dashboard/doctors/profile/$doctorId': typeof AppDashboardDoctorsProfileDoctorIdIndexRoute
}

export interface FileRoutesByTo {
  '': typeof AppDoctorRouteWithChildren
  '/auth/sign-in': typeof AppAuthSignInRoute
  '/auth/sign-up': typeof AppAuthSignUpRoute
  '/dashboard': typeof AppDashboardIndexRoute
  '/': typeof PagesPagesIndexRoute
  '/consultations': typeof AppConsultationConsultationsIndexRoute
  '/doctor': typeof AppDoctorDoctorIndexRoute
  '/dashboard/doctors': typeof AppDashboardDoctorsIndexRoute
  '/dashboard/profile': typeof AppDashboardProfileIndexRoute
  '/dashboard/schedule': typeof AppDashboardScheduleIndexRoute
  '/dashboard/wallet': typeof AppDashboardWalletIndexRoute
  '/doctor/appointments': typeof AppDoctorDoctorAppointmentsIndexRoute
  '/doctor/lab': typeof AppDoctorDoctorLabIndexRoute
  '/doctor/message': typeof AppDoctorDoctorMessageIndexRoute
  '/doctor/patients': typeof AppDoctorDoctorPatientsIndexRoute
  '/doctor/support': typeof AppDoctorDoctorSupportIndexRoute
  '/dashboard/chats/$doctorId': typeof AppDashboardChatsDoctorIdIndexRoute
  '/doctor/message/$patientId': typeof AppDoctorDoctorMessagePatientIdIndexRoute
  '/dashboard/doctors/profile/$doctorId': typeof AppDashboardDoctorsProfileDoctorIdIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/_app': typeof AppRouteWithChildren
  '/_doctor': typeof DoctorRoute
  '/_pages': typeof PagesRouteWithChildren
  '/_app/_doctor': typeof AppDoctorRouteWithChildren
  '/_pages/_pages': typeof PagesPagesRouteWithChildren
  '/_app/auth/sign-in': typeof AppAuthSignInRoute
  '/_app/auth/sign-up': typeof AppAuthSignUpRoute
  '/_app/dashboard/': typeof AppDashboardIndexRoute
  '/_pages/_pages/': typeof PagesPagesIndexRoute
  '/_app/_consultation/consultations/': typeof AppConsultationConsultationsIndexRoute
  '/_app/_doctor/doctor/': typeof AppDoctorDoctorIndexRoute
  '/_app/dashboard/doctors/': typeof AppDashboardDoctorsIndexRoute
  '/_app/dashboard/profile/': typeof AppDashboardProfileIndexRoute
  '/_app/dashboard/schedule/': typeof AppDashboardScheduleIndexRoute
  '/_app/dashboard/wallet/': typeof AppDashboardWalletIndexRoute
  '/_app/_doctor/doctor/appointments/': typeof AppDoctorDoctorAppointmentsIndexRoute
  '/_app/_doctor/doctor/lab/': typeof AppDoctorDoctorLabIndexRoute
  '/_app/_doctor/doctor/message/': typeof AppDoctorDoctorMessageIndexRoute
  '/_app/_doctor/doctor/patients/': typeof AppDoctorDoctorPatientsIndexRoute
  '/_app/_doctor/doctor/support/': typeof AppDoctorDoctorSupportIndexRoute
  '/_app/dashboard/chats/$doctorId/': typeof AppDashboardChatsDoctorIdIndexRoute
  '/_app/_doctor/doctor/message/$patientId/': typeof AppDoctorDoctorMessagePatientIdIndexRoute
  '/_app/dashboard/doctors/profile/$doctorId/': typeof AppDashboardDoctorsProfileDoctorIdIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | ''
    | '/auth/sign-in'
    | '/auth/sign-up'
    | '/dashboard'
    | '/'
    | '/consultations'
    | '/doctor'
    | '/dashboard/doctors'
    | '/dashboard/profile'
    | '/dashboard/schedule'
    | '/dashboard/wallet'
    | '/doctor/appointments'
    | '/doctor/lab'
    | '/doctor/message'
    | '/doctor/patients'
    | '/doctor/support'
    | '/dashboard/chats/$doctorId'
    | '/doctor/message/$patientId'
    | '/dashboard/doctors/profile/$doctorId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | ''
    | '/auth/sign-in'
    | '/auth/sign-up'
    | '/dashboard'
    | '/'
    | '/consultations'
    | '/doctor'
    | '/dashboard/doctors'
    | '/dashboard/profile'
    | '/dashboard/schedule'
    | '/dashboard/wallet'
    | '/doctor/appointments'
    | '/doctor/lab'
    | '/doctor/message'
    | '/doctor/patients'
    | '/doctor/support'
    | '/dashboard/chats/$doctorId'
    | '/doctor/message/$patientId'
    | '/dashboard/doctors/profile/$doctorId'
  id:
    | '__root__'
    | '/_app'
    | '/_doctor'
    | '/_pages'
    | '/_app/_doctor'
    | '/_pages/_pages'
    | '/_app/auth/sign-in'
    | '/_app/auth/sign-up'
    | '/_app/dashboard/'
    | '/_pages/_pages/'
    | '/_app/_consultation/consultations/'
    | '/_app/_doctor/doctor/'
    | '/_app/dashboard/doctors/'
    | '/_app/dashboard/profile/'
    | '/_app/dashboard/schedule/'
    | '/_app/dashboard/wallet/'
    | '/_app/_doctor/doctor/appointments/'
    | '/_app/_doctor/doctor/lab/'
    | '/_app/_doctor/doctor/message/'
    | '/_app/_doctor/doctor/patients/'
    | '/_app/_doctor/doctor/support/'
    | '/_app/dashboard/chats/$doctorId/'
    | '/_app/_doctor/doctor/message/$patientId/'
    | '/_app/dashboard/doctors/profile/$doctorId/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  DoctorRoute: typeof DoctorRoute
  PagesRoute: typeof PagesRouteWithChildren
}

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  DoctorRoute: DoctorRoute,
  PagesRoute: PagesRouteWithChildren,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/_app",
        "/_doctor",
        "/_pages"
      ]
    },
    "/_app": {
      "filePath": "_app.tsx",
      "children": [
        "/_app/_doctor",
        "/_app/auth/sign-in",
        "/_app/auth/sign-up",
        "/_app/dashboard/",
        "/_app/_consultation/consultations/",
        "/_app/dashboard/doctors/",
        "/_app/dashboard/profile/",
        "/_app/dashboard/schedule/",
        "/_app/dashboard/wallet/",
        "/_app/dashboard/chats/$doctorId/",
        "/_app/dashboard/doctors/profile/$doctorId/"
      ]
    },
    "/_doctor": {
      "filePath": "_doctor.tsx"
    },
    "/_pages": {
      "filePath": "_pages.tsx",
      "children": [
        "/_pages/_pages"
      ]
    },
    "/_app/_doctor": {
      "filePath": "_app/_doctor.tsx",
      "parent": "/_app",
      "children": [
        "/_app/_doctor/doctor/",
        "/_app/_doctor/doctor/appointments/",
        "/_app/_doctor/doctor/lab/",
        "/_app/_doctor/doctor/message/",
        "/_app/_doctor/doctor/patients/",
        "/_app/_doctor/doctor/support/",
        "/_app/_doctor/doctor/message/$patientId/"
      ]
    },
    "/_pages/_pages": {
      "filePath": "_pages/_pages.tsx",
      "parent": "/_pages",
      "children": [
        "/_pages/_pages/"
      ]
    },
    "/_app/auth/sign-in": {
      "filePath": "_app/auth/sign-in.tsx",
      "parent": "/_app"
    },
    "/_app/auth/sign-up": {
      "filePath": "_app/auth/sign-up.tsx",
      "parent": "/_app"
    },
    "/_app/dashboard/": {
      "filePath": "_app/dashboard/index.tsx",
      "parent": "/_app"
    },
    "/_pages/_pages/": {
      "filePath": "_pages/_pages/index.tsx",
      "parent": "/_pages/_pages"
    },
    "/_app/_consultation/consultations/": {
      "filePath": "_app/_consultation/consultations/index.tsx",
      "parent": "/_app"
    },
    "/_app/_doctor/doctor/": {
      "filePath": "_app/_doctor/doctor/index.tsx",
      "parent": "/_app/_doctor"
    },
    "/_app/dashboard/doctors/": {
      "filePath": "_app/dashboard/doctors/index.tsx",
      "parent": "/_app"
    },
    "/_app/dashboard/profile/": {
      "filePath": "_app/dashboard/profile/index.tsx",
      "parent": "/_app"
    },
    "/_app/dashboard/schedule/": {
      "filePath": "_app/dashboard/schedule/index.tsx",
      "parent": "/_app"
    },
    "/_app/dashboard/wallet/": {
      "filePath": "_app/dashboard/wallet/index.tsx",
      "parent": "/_app"
    },
    "/_app/_doctor/doctor/appointments/": {
      "filePath": "_app/_doctor/doctor/appointments/index.tsx",
      "parent": "/_app/_doctor"
    },
    "/_app/_doctor/doctor/lab/": {
      "filePath": "_app/_doctor/doctor/lab/index.tsx",
      "parent": "/_app/_doctor"
    },
    "/_app/_doctor/doctor/message/": {
      "filePath": "_app/_doctor/doctor/message/index.tsx",
      "parent": "/_app/_doctor"
    },
    "/_app/_doctor/doctor/patients/": {
      "filePath": "_app/_doctor/doctor/patients/index.tsx",
      "parent": "/_app/_doctor"
    },
    "/_app/_doctor/doctor/support/": {
      "filePath": "_app/_doctor/doctor/support/index.tsx",
      "parent": "/_app/_doctor"
    },
    "/_app/dashboard/chats/$doctorId/": {
      "filePath": "_app/dashboard/chats/$doctorId/index.tsx",
      "parent": "/_app"
    },
    "/_app/_doctor/doctor/message/$patientId/": {
      "filePath": "_app/_doctor/doctor/message/$patientId/index.tsx",
      "parent": "/_app/_doctor"
    },
    "/_app/dashboard/doctors/profile/$doctorId/": {
      "filePath": "_app/dashboard/doctors/profile/$doctorId/index.tsx",
      "parent": "/_app"
    }
  }
}
ROUTE_MANIFEST_END */
