/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/auth/resend-verification-email": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Resend verification email */
        post: operations["Authentication_resendVerificationEmail"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/reset-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** @description Reset password */
        put: operations["Authentication_resetPassword"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/reset-password/send-email": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Send reset password email */
        post: operations["Authentication_sendResetPasswordEmail"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/sign-in": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Sign in user */
        post: operations["Authentication_signIn"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/sign-out": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Sign out user */
        get: operations["Authentication_signOut"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/sign-up": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Sign up new user */
        post: operations["Authentication_signUp"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/verify-email": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Verify email address */
        post: operations["Authentication_verifyEmail"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/consultation/request/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Fetch consultation requests */
        get: operations["Request_fetchConsultationRequests"];
        put?: never;
        /** @description Request consultation */
        post: operations["Request_requestConsultation"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/consultation/request/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Fetch consultation request by ID */
        get: operations["Request_fetchConsultationRequestById"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/consultation/request/{id}/accept": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Accept consultation request */
        post: operations["Request_acceptConsultationRequest"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/consultation/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Fetch consultation by ID */
        get: operations["Consultation_fetchConsultationById"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/consultation/{id}/chat": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Add chat */
        post: operations["Consultation_fetchChat"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/consultation/{id}/note": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Add doctors notes */
        post: operations["Consultation_addDoctorsNotes"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/doctors/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Fetch all doctors */
        get: operations["Doctor_fetchDoctors"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/doctors/profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Fetch doctor profile */
        get: operations["Doctor_fetchProfile"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/doctors/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Fetch doctor by ID */
        get: operations["Doctor_fetchDoctorById"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** @description Update doctor by ID */
        patch: operations["Doctor_updateDoctorById"];
        trace?: never;
    };
    "/api/patients/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Fetch all patients */
        get: operations["Patient_fetchPatients"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/patients/profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Fetch patient profile */
        get: operations["Patient_fetchProfile"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/patients/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Fetch patient by ID */
        get: operations["Patient_fetchPatientById"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** @description Update patient by ID */
        patch: operations["Patient_updatePatientById"];
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description Authentication token */
        "Api.Authentication.AuthCredentials": {
            /** @example 745731af4484f323968969eda289aeee */
            token: string;
        };
        "Api.Authentication.ResendVerificationEmailPayload": {
            /** @example mary.slessor@mail.com */
            email: string;
        };
        "Api.Authentication.ResetPasswordPayload": {
            /** @example mary.slessor@mail.com */
            email: string;
            /** @example NewP@ssw0rd */
            password: string;
        };
        "Api.Authentication.SendResetPasswordEmailPayload": {
            /** @example mary.slessor@mail.com */
            email: string;
        };
        "Api.Authentication.SignInPayload": {
            /** @example mary.slessor@mail.com */
            email: string;
            /** @example $3cureP@ssw0rd */
            password: string;
        };
        "Api.Authentication.SignOutSuccessful": {
            /** @example Sign out successful */
            message: string;
        };
        "Api.Authentication.SignUpPayload": {
            /** @example Mary */
            first_name: string;
            /** @example Slessor */
            last_name: string;
            /** @example mary.slessor@mail.com */
            email: string;
            /** @example $3cureP@ssw0rd */
            password: string;
            /** @enum {string} */
            role: "patient" | "doctor";
        };
        "Api.Authentication.VerificationSuccessful": {
            /** @example Email verified successfully */
            message: string;
        };
        "Api.Authentication.VerifyEmailPayload": {
            /** @example mary.slessor@mail.com */
            email: string;
            /** @example 123456 */
            otp: string;
        };
        "Api.Authentication.WelcomeMessage": {
            /** @example Please check your email address for a verification code */
            message: string;
        };
        "Api.BadRequestError": {
            /** @example Invalid data */
            message: string;
        };
        "Api.Consultation.Chat": {
            id: components["schemas"]["Id"];
            /** @example Hello, how are you feeling today? */
            content: string;
            media: components["schemas"]["Api.Consultation.Media"][];
            /** @enum {string} */
            sent_by: "doctor" | "patient";
            created_at: components["schemas"]["Date"];
        };
        "Api.Consultation.Consultation": {
            doctors_notes: components["schemas"]["Api.Consultation.DoctorNote"][];
            chats: components["schemas"]["Api.Consultation.Chat"][];
            doctor_id: components["schemas"]["Id"];
            patient_id: components["schemas"]["Id"];
        };
        "Api.Consultation.ConsultationChatAdded": {
            /** @example Chat added */
            message: string;
        };
        "Api.Consultation.ConsultationNoteAdded": {
            /** @example Doctors notes added */
            message: string;
        };
        "Api.Consultation.DoctorNote": {
            id: components["schemas"]["Id"];
            /** @example Patient is suffering from a cold */
            content: string;
            created_at: components["schemas"]["Date"];
        };
        "Api.Consultation.Media": {
            /** @enum {string} */
            type: "image" | "video";
            /** @example https://example.com/image.jpg */
            url: string;
        };
        "Api.Consultation.Request.ConsultationRequest": {
            doctor_id: components["schemas"]["Id"];
            patient_id: components["schemas"]["Id"];
            /** @enum {string} */
            status: "pending" | "accepted" | "rejected";
            /** @example I am feeling unwell */
            message: string;
        };
        "Api.Consultation.Request.ConsultationRequestAccepted": {
            /** @enum {string} */
            message: "Consultation request accepted";
        };
        "Api.Consultation.Request.ConsultationRequestCreated": {
            /** @example Consultation request created */
            message: string;
        };
        "Api.Consultation.Request.ConsultationRequestPayload": {
            doctor_id: components["schemas"]["Id"];
            /** @example I am feeling unwell */
            message: string;
        };
        "Api.Doctor.Doctor": {
            id: components["schemas"]["Id"];
            /** @example John */
            first_name: string;
            /** @example Doe */
            last_name: string;
            /** @example john.doe@mail.com */
            email: string;
        };
        "Api.Doctor.DoctorUpdate": {
            id?: components["schemas"]["Id"];
            /** @example John */
            first_name?: string;
            /** @example Doe */
            last_name?: string;
            /** @example john.doe@mail.com */
            email?: string;
        };
        "Api.Patient.Patient": {
            id: components["schemas"]["Id"];
            /** @example Mary */
            first_name: string;
            /** @example Slessor */
            last_name: string;
            /** @example mary.slessor@mail.com */
            email: string;
        };
        "Api.Patient.PatientUpdate": {
            id?: components["schemas"]["Id"];
            /** @example Mary */
            first_name?: string;
            /** @example Slessor */
            last_name?: string;
            /** @example mary.slessor@mail.com */
            email?: string;
        };
        "Api.UnexpectedError": {
            /** @example An unexpected error occurred */
            message: string;
        };
        /** @example 2021-09-01T12:00:00Z */
        Date: string;
        /** @example f47ac10b-58cc-4372-a567-0e02b2c3d479 */
        Id: string;
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    Authentication_resendVerificationEmail: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Api.Authentication.ResendVerificationEmailPayload"];
            };
        };
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Api.Authentication.WelcomeMessage"];
                };
            };
            /** @description The server could not understand the request due to invalid syntax. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Api.BadRequestError"];
                };
            };
            /** @description Server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Api.UnexpectedError"];
                };
            };
        };
    };
    Authentication_resetPassword: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Api.Authentication.ResetPasswordPayload"];
            };
        };
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Api.Authentication.WelcomeMessage"];
                };
            };
            /** @description The server could not understand the request due to invalid syntax. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Api.BadRequestError"];
                };
            };
            /** @description Server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Api.UnexpectedError"];
                };
            };
        };
    };
    Authentication_sendResetPasswordEmail: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Api.Authentication.SendResetPasswordEmailPayload"];
            };
        };
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Api.Authentication.WelcomeMessage"];
                };
            };
            /** @description The server could not understand the request due to invalid syntax. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Api.BadRequestError"];
                };
            };
            /** @description Server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Api.UnexpectedError"];
                };
            };
        };
    };
    Authentication_signIn: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Api.Authentication.SignInPayload"];
            };
        };
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Api.Authentication.AuthCredentials"];
                };
            };
            /** @description The server could not understand the request due to invalid syntax. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Api.BadRequestError"];
                };
            };
            /** @description Server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Api.UnexpectedError"];
                };
            };
        };
    };
    Authentication_signOut: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Api.Authentication.SignOutSuccessful"];
                };
            };
            /** @description Server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Api.UnexpectedError"];
                };
            };
        };
    };
    Authentication_signUp: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Api.Authentication.SignUpPayload"];
            };
        };
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Api.Authentication.WelcomeMessage"];
                };
            };
            /** @description The server could not understand the request due to invalid syntax. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Api.BadRequestError"];
                };
            };
            /** @description Server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Api.UnexpectedError"];
                };
            };
        };
    };
    Authentication_verifyEmail: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Api.Authentication.VerifyEmailPayload"];
            };
        };
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Api.Authentication.VerificationSuccessful"];
                };
            };
            /** @description The server could not understand the request due to invalid syntax. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Api.BadRequestError"];
                };
            };
            /** @description Server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Api.UnexpectedError"];
                };
            };
        };
    };
    Request_fetchConsultationRequests: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Api.Consultation.Request.ConsultationRequest"][];
                };
            };
            /** @description Server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Api.UnexpectedError"];
                };
            };
        };
    };
    Request_requestConsultation: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Api.Consultation.Request.ConsultationRequestPayload"];
            };
        };
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Api.Consultation.Request.ConsultationRequestCreated"];
                };
            };
            /** @description Server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Api.UnexpectedError"];
                };
            };
        };
    };
    Request_fetchConsultationRequestById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Api.Consultation.Request.ConsultationRequest"];
                };
            };
            /** @description Server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Api.UnexpectedError"];
                };
            };
        };
    };
    Request_acceptConsultationRequest: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Api.Consultation.Request.ConsultationRequestAccepted"][];
                };
            };
            /** @description Server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Api.UnexpectedError"];
                };
            };
        };
    };
    Consultation_fetchConsultationById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Api.Consultation.Consultation"];
                };
            };
            /** @description Server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Api.UnexpectedError"];
                };
            };
        };
    };
    Consultation_fetchChat: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Api.Consultation.ConsultationChatAdded"];
                };
            };
            /** @description Server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Api.UnexpectedError"];
                };
            };
        };
    };
    Consultation_addDoctorsNotes: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": string;
            };
        };
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Api.Consultation.ConsultationNoteAdded"];
                };
            };
            /** @description Server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Api.UnexpectedError"];
                };
            };
        };
    };
    Doctor_fetchDoctors: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Api.Doctor.Doctor"][];
                };
            };
            /** @description Server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Api.UnexpectedError"];
                };
            };
        };
    };
    Doctor_fetchProfile: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Api.Doctor.Doctor"];
                };
            };
            /** @description Server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Api.UnexpectedError"];
                };
            };
        };
    };
    Doctor_fetchDoctorById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Api.Doctor.Doctor"];
                };
            };
            /** @description Server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Api.UnexpectedError"];
                };
            };
        };
    };
    Doctor_updateDoctorById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Api.Doctor.DoctorUpdate"];
            };
        };
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Api.Doctor.Doctor"];
                };
            };
            /** @description Server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Api.UnexpectedError"];
                };
            };
        };
    };
    Patient_fetchPatients: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Api.Patient.Patient"][];
                };
            };
            /** @description Server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Api.UnexpectedError"];
                };
            };
        };
    };
    Patient_fetchProfile: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Api.Patient.Patient"];
                };
            };
            /** @description Server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Api.UnexpectedError"];
                };
            };
        };
    };
    Patient_fetchPatientById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Api.Patient.Patient"];
                };
            };
            /** @description Server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Api.UnexpectedError"];
                };
            };
        };
    };
    Patient_updatePatientById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Api.Patient.PatientUpdate"];
            };
        };
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Api.Patient.Patient"];
                };
            };
            /** @description Server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Api.UnexpectedError"];
                };
            };
        };
    };
}
