/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as AppImport } from './routes/_app'
import { Route as IndexImport } from './routes/index'
import { Route as AppDoctorImport } from './routes/_app/_doctor'
import { Route as AppDashboardImport } from './routes/_app/_dashboard'
import { Route as AppTestcallIndexImport } from './routes/_app/testcall/index'
import { Route as AppTermsIndexImport } from './routes/_app/terms/index'
import { Route as AppPrivacyIndexImport } from './routes/_app/privacy/index'
import { Route as AppOnboardingIndexImport } from './routes/_app/onboarding/index'
import { Route as AppHelpIndexImport } from './routes/_app/help/index'
import { Route as AppTestcallCallImport } from './routes/_app/testcall/call'
import { Route as AppAuthVerifyImport } from './routes/_app/auth/verify'
import { Route as AppAuthSignUpImport } from './routes/_app/auth/sign-up'
import { Route as AppAuthSignInImport } from './routes/_app/auth/sign-in'
import { Route as AppAuthSetProfileIndexImport } from './routes/_app/auth/set-profile/index'
import { Route as AppAuthForgotPasswordIndexImport } from './routes/_app/auth/forgot-password/index'
import { Route as AppDoctorDoctorIndexImport } from './routes/_app/_doctor/doctor/index'
import { Route as AppDashboardDashboardIndexImport } from './routes/_app/_dashboard/dashboard/index'
import { Route as AppConsultationConsultationsIndexImport } from './routes/_app/_consultation/consultations/index'
import { Route as AppAuthForgotPasswordTokenImport } from './routes/_app/auth/forgot-password/token'
import { Route as AppDashboardDashboardConsultationImport } from './routes/_app/_dashboard/dashboard/_consultation'
import { Route as AppAuthForgotPasswordTokenIndexImport } from './routes/_app/auth/forgot-password/$token/index'
import { Route as AppDoctorDoctorSupportIndexImport } from './routes/_app/_doctor/doctor/support/index'
import { Route as AppDoctorDoctorPatientsIndexImport } from './routes/_app/_doctor/doctor/patients/index'
import { Route as AppDoctorDoctorMessageIndexImport } from './routes/_app/_doctor/doctor/message/index'
import { Route as AppDoctorDoctorLabIndexImport } from './routes/_app/_doctor/doctor/lab/index'
import { Route as AppDoctorDoctorDashboardIndexImport } from './routes/_app/_doctor/doctor/dashboard/index'
import { Route as AppDashboardDashboardWalletIndexImport } from './routes/_app/_dashboard/dashboard/wallet/index'
import { Route as AppDashboardDashboardScheduleIndexImport } from './routes/_app/_dashboard/dashboard/schedule/index'
import { Route as AppDashboardDashboardProfileIndexImport } from './routes/_app/_dashboard/dashboard/profile/index'
import { Route as AppDashboardDashboardDoctorsIndexImport } from './routes/_app/_dashboard/dashboard/doctors/index'
import { Route as AppDashboardDashboardPharmacyCartImport } from './routes/_app/_dashboard/dashboard/pharmacy/cart'
import { Route as AppDashboardDashboardConsultationJitsiconsultationImport } from './routes/_app/_dashboard/dashboard/_consultation/jitsiconsultation'
import { Route as AppDashboardDashboardConsultationClientconsultationImport } from './routes/_app/_dashboard/dashboard/_consultation/clientconsultation'
import { Route as AppDoctorDoctorMessagePatientIdIndexImport } from './routes/_app/_doctor/doctor/message/$patientId/index'
import { Route as AppDoctorDoctorDashboardWalletIndexImport } from './routes/_app/_doctor/doctor/dashboard/wallet/index'
import { Route as AppDoctorDoctorDashboardProfileIndexImport } from './routes/_app/_doctor/doctor/dashboard/profile/index'
import { Route as AppDoctorDoctorDashboardPatientsIndexImport } from './routes/_app/_doctor/doctor/dashboard/patients/index'
import { Route as AppDoctorDoctorDashboardEarningsIndexImport } from './routes/_app/_doctor/doctor/dashboard/earnings/index'
import { Route as AppDoctorDoctorDashboardAppointmentsIndexImport } from './routes/_app/_doctor/doctor/dashboard/appointments/index'
import { Route as AppDashboardDashboardPharmacyProductIndexImport } from './routes/_app/_dashboard/dashboard/pharmacy/product/index'
import { Route as AppDashboardDashboardMessagesDoctorIdIndexImport } from './routes/_app/_dashboard/dashboard/messages/$doctorId/index'
import { Route as AppDashboardDashboardDoctorsIdIndexImport } from './routes/_app/_dashboard/dashboard/doctors/$id/index'
import { Route as AppDashboardDashboardChatsDoctorIdIndexImport } from './routes/_app/_dashboard/dashboard/chats/$doctorId/index'
import { Route as AppDoctorDoctorDashboardPatientsIdIndexImport } from './routes/_app/_doctor/doctor/dashboard/patients/$id/index'
import { Route as AppDashboardDashboardPharmacyProductIdIndexImport } from './routes/_app/_dashboard/dashboard/pharmacy/product/$id/index'

// Create Virtual Routes

const AppDashboardDashboardImport = createFileRoute(
  '/_app/_dashboard/dashboard',
)()

// Create/Update Routes

const AppRoute = AppImport.update({
  id: '/_app',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const AppDoctorRoute = AppDoctorImport.update({
  id: '/_doctor',
  getParentRoute: () => AppRoute,
} as any)

const AppDashboardRoute = AppDashboardImport.update({
  id: '/_dashboard',
  getParentRoute: () => AppRoute,
} as any)

const AppDashboardDashboardRoute = AppDashboardDashboardImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppDashboardRoute,
} as any)

const AppTestcallIndexRoute = AppTestcallIndexImport.update({
  id: '/testcall/',
  path: '/testcall/',
  getParentRoute: () => AppRoute,
} as any)

const AppTermsIndexRoute = AppTermsIndexImport.update({
  id: '/terms/',
  path: '/terms/',
  getParentRoute: () => AppRoute,
} as any)

const AppPrivacyIndexRoute = AppPrivacyIndexImport.update({
  id: '/privacy/',
  path: '/privacy/',
  getParentRoute: () => AppRoute,
} as any)

const AppOnboardingIndexRoute = AppOnboardingIndexImport.update({
  id: '/onboarding/',
  path: '/onboarding/',
  getParentRoute: () => AppRoute,
} as any)

const AppHelpIndexRoute = AppHelpIndexImport.update({
  id: '/help/',
  path: '/help/',
  getParentRoute: () => AppRoute,
} as any)

const AppTestcallCallRoute = AppTestcallCallImport.update({
  id: '/testcall/call',
  path: '/testcall/call',
  getParentRoute: () => AppRoute,
} as any)

const AppAuthVerifyRoute = AppAuthVerifyImport.update({
  id: '/auth/verify',
  path: '/auth/verify',
  getParentRoute: () => AppRoute,
} as any)

const AppAuthSignUpRoute = AppAuthSignUpImport.update({
  id: '/auth/sign-up',
  path: '/auth/sign-up',
  getParentRoute: () => AppRoute,
} as any)

const AppAuthSignInRoute = AppAuthSignInImport.update({
  id: '/auth/sign-in',
  path: '/auth/sign-in',
  getParentRoute: () => AppRoute,
} as any)

const AppAuthSetProfileIndexRoute = AppAuthSetProfileIndexImport.update({
  id: '/auth/set-profile/',
  path: '/auth/set-profile/',
  getParentRoute: () => AppRoute,
} as any)

const AppAuthForgotPasswordIndexRoute = AppAuthForgotPasswordIndexImport.update(
  {
    id: '/auth/forgot-password/',
    path: '/auth/forgot-password/',
    getParentRoute: () => AppRoute,
  } as any,
)

const AppDoctorDoctorIndexRoute = AppDoctorDoctorIndexImport.update({
  id: '/doctor/',
  path: '/doctor/',
  getParentRoute: () => AppDoctorRoute,
} as any)

const AppDashboardDashboardIndexRoute = AppDashboardDashboardIndexImport.update(
  {
    id: '/',
    path: '/',
    getParentRoute: () => AppDashboardDashboardRoute,
  } as any,
)

const AppConsultationConsultationsIndexRoute =
  AppConsultationConsultationsIndexImport.update({
    id: '/_consultation/consultations/',
    path: '/consultations/',
    getParentRoute: () => AppRoute,
  } as any)

const AppAuthForgotPasswordTokenRoute = AppAuthForgotPasswordTokenImport.update(
  {
    id: '/auth/forgot-password/token',
    path: '/auth/forgot-password/token',
    getParentRoute: () => AppRoute,
  } as any,
)

const AppDashboardDashboardConsultationRoute =
  AppDashboardDashboardConsultationImport.update({
    id: '/_consultation',
    getParentRoute: () => AppDashboardDashboardRoute,
  } as any)

const AppAuthForgotPasswordTokenIndexRoute =
  AppAuthForgotPasswordTokenIndexImport.update({
    id: '/auth/forgot-password/$token/',
    path: '/auth/forgot-password/$token/',
    getParentRoute: () => AppRoute,
  } as any)

const AppDoctorDoctorSupportIndexRoute =
  AppDoctorDoctorSupportIndexImport.update({
    id: '/doctor/support/',
    path: '/doctor/support/',
    getParentRoute: () => AppDoctorRoute,
  } as any)

const AppDoctorDoctorPatientsIndexRoute =
  AppDoctorDoctorPatientsIndexImport.update({
    id: '/doctor/patients/',
    path: '/doctor/patients/',
    getParentRoute: () => AppDoctorRoute,
  } as any)

const AppDoctorDoctorMessageIndexRoute =
  AppDoctorDoctorMessageIndexImport.update({
    id: '/doctor/message/',
    path: '/doctor/message/',
    getParentRoute: () => AppDoctorRoute,
  } as any)

const AppDoctorDoctorLabIndexRoute = AppDoctorDoctorLabIndexImport.update({
  id: '/doctor/lab/',
  path: '/doctor/lab/',
  getParentRoute: () => AppDoctorRoute,
} as any)

const AppDoctorDoctorDashboardIndexRoute =
  AppDoctorDoctorDashboardIndexImport.update({
    id: '/doctor/dashboard/',
    path: '/doctor/dashboard/',
    getParentRoute: () => AppDoctorRoute,
  } as any)

const AppDashboardDashboardWalletIndexRoute =
  AppDashboardDashboardWalletIndexImport.update({
    id: '/wallet/',
    path: '/wallet/',
    getParentRoute: () => AppDashboardDashboardRoute,
  } as any)

const AppDashboardDashboardScheduleIndexRoute =
  AppDashboardDashboardScheduleIndexImport.update({
    id: '/schedule/',
    path: '/schedule/',
    getParentRoute: () => AppDashboardDashboardRoute,
  } as any)

const AppDashboardDashboardProfileIndexRoute =
  AppDashboardDashboardProfileIndexImport.update({
    id: '/profile/',
    path: '/profile/',
    getParentRoute: () => AppDashboardDashboardRoute,
  } as any)

const AppDashboardDashboardDoctorsIndexRoute =
  AppDashboardDashboardDoctorsIndexImport.update({
    id: '/doctors/',
    path: '/doctors/',
    getParentRoute: () => AppDashboardDashboardRoute,
  } as any)

const AppDashboardDashboardPharmacyCartRoute =
  AppDashboardDashboardPharmacyCartImport.update({
    id: '/pharmacy/cart',
    path: '/pharmacy/cart',
    getParentRoute: () => AppDashboardDashboardRoute,
  } as any)

const AppDashboardDashboardConsultationJitsiconsultationRoute =
  AppDashboardDashboardConsultationJitsiconsultationImport.update({
    id: '/jitsiconsultation',
    path: '/jitsiconsultation',
    getParentRoute: () => AppDashboardDashboardConsultationRoute,
  } as any)

const AppDashboardDashboardConsultationClientconsultationRoute =
  AppDashboardDashboardConsultationClientconsultationImport.update({
    id: '/clientconsultation',
    path: '/clientconsultation',
    getParentRoute: () => AppDashboardDashboardConsultationRoute,
  } as any)

const AppDoctorDoctorMessagePatientIdIndexRoute =
  AppDoctorDoctorMessagePatientIdIndexImport.update({
    id: '/doctor/message/$patientId/',
    path: '/doctor/message/$patientId/',
    getParentRoute: () => AppDoctorRoute,
  } as any)

const AppDoctorDoctorDashboardWalletIndexRoute =
  AppDoctorDoctorDashboardWalletIndexImport.update({
    id: '/doctor/dashboard/wallet/',
    path: '/doctor/dashboard/wallet/',
    getParentRoute: () => AppDoctorRoute,
  } as any)

const AppDoctorDoctorDashboardProfileIndexRoute =
  AppDoctorDoctorDashboardProfileIndexImport.update({
    id: '/doctor/dashboard/profile/',
    path: '/doctor/dashboard/profile/',
    getParentRoute: () => AppDoctorRoute,
  } as any)

const AppDoctorDoctorDashboardPatientsIndexRoute =
  AppDoctorDoctorDashboardPatientsIndexImport.update({
    id: '/doctor/dashboard/patients/',
    path: '/doctor/dashboard/patients/',
    getParentRoute: () => AppDoctorRoute,
  } as any)

const AppDoctorDoctorDashboardEarningsIndexRoute =
  AppDoctorDoctorDashboardEarningsIndexImport.update({
    id: '/doctor/dashboard/earnings/',
    path: '/doctor/dashboard/earnings/',
    getParentRoute: () => AppDoctorRoute,
  } as any)

const AppDoctorDoctorDashboardAppointmentsIndexRoute =
  AppDoctorDoctorDashboardAppointmentsIndexImport.update({
    id: '/doctor/dashboard/appointments/',
    path: '/doctor/dashboard/appointments/',
    getParentRoute: () => AppDoctorRoute,
  } as any)

const AppDashboardDashboardPharmacyProductIndexRoute =
  AppDashboardDashboardPharmacyProductIndexImport.update({
    id: '/pharmacy/product/',
    path: '/pharmacy/product/',
    getParentRoute: () => AppDashboardDashboardRoute,
  } as any)

const AppDashboardDashboardMessagesDoctorIdIndexRoute =
  AppDashboardDashboardMessagesDoctorIdIndexImport.update({
    id: '/messages/$doctorId/',
    path: '/messages/$doctorId/',
    getParentRoute: () => AppDashboardDashboardRoute,
  } as any)

const AppDashboardDashboardDoctorsIdIndexRoute =
  AppDashboardDashboardDoctorsIdIndexImport.update({
    id: '/doctors/$id/',
    path: '/doctors/$id/',
    getParentRoute: () => AppDashboardDashboardRoute,
  } as any)

const AppDashboardDashboardChatsDoctorIdIndexRoute =
  AppDashboardDashboardChatsDoctorIdIndexImport.update({
    id: '/chats/$doctorId/',
    path: '/chats/$doctorId/',
    getParentRoute: () => AppDashboardDashboardRoute,
  } as any)

const AppDoctorDoctorDashboardPatientsIdIndexRoute =
  AppDoctorDoctorDashboardPatientsIdIndexImport.update({
    id: '/doctor/dashboard/patients/$id/',
    path: '/doctor/dashboard/patients/$id/',
    getParentRoute: () => AppDoctorRoute,
  } as any)

const AppDashboardDashboardPharmacyProductIdIndexRoute =
  AppDashboardDashboardPharmacyProductIdIndexImport.update({
    id: '/pharmacy/product/$id/',
    path: '/pharmacy/product/$id/',
    getParentRoute: () => AppDashboardDashboardRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AppImport
      parentRoute: typeof rootRoute
    }
    '/_app/_dashboard': {
      id: '/_app/_dashboard'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AppDashboardImport
      parentRoute: typeof AppImport
    }
    '/_app/_doctor': {
      id: '/_app/_doctor'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AppDoctorImport
      parentRoute: typeof AppImport
    }
    '/_app/auth/sign-in': {
      id: '/_app/auth/sign-in'
      path: '/auth/sign-in'
      fullPath: '/auth/sign-in'
      preLoaderRoute: typeof AppAuthSignInImport
      parentRoute: typeof AppImport
    }
    '/_app/auth/sign-up': {
      id: '/_app/auth/sign-up'
      path: '/auth/sign-up'
      fullPath: '/auth/sign-up'
      preLoaderRoute: typeof AppAuthSignUpImport
      parentRoute: typeof AppImport
    }
    '/_app/auth/verify': {
      id: '/_app/auth/verify'
      path: '/auth/verify'
      fullPath: '/auth/verify'
      preLoaderRoute: typeof AppAuthVerifyImport
      parentRoute: typeof AppImport
    }
    '/_app/testcall/call': {
      id: '/_app/testcall/call'
      path: '/testcall/call'
      fullPath: '/testcall/call'
      preLoaderRoute: typeof AppTestcallCallImport
      parentRoute: typeof AppImport
    }
    '/_app/help/': {
      id: '/_app/help/'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof AppHelpIndexImport
      parentRoute: typeof AppImport
    }
    '/_app/onboarding/': {
      id: '/_app/onboarding/'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AppOnboardingIndexImport
      parentRoute: typeof AppImport
    }
    '/_app/privacy/': {
      id: '/_app/privacy/'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof AppPrivacyIndexImport
      parentRoute: typeof AppImport
    }
    '/_app/terms/': {
      id: '/_app/terms/'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof AppTermsIndexImport
      parentRoute: typeof AppImport
    }
    '/_app/testcall/': {
      id: '/_app/testcall/'
      path: '/testcall'
      fullPath: '/testcall'
      preLoaderRoute: typeof AppTestcallIndexImport
      parentRoute: typeof AppImport
    }
    '/_app/_dashboard/dashboard': {
      id: '/_app/_dashboard/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardDashboardImport
      parentRoute: typeof AppDashboardImport
    }
    '/_app/_dashboard/dashboard/_consultation': {
      id: '/_app/_dashboard/dashboard/_consultation'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardDashboardConsultationImport
      parentRoute: typeof AppDashboardDashboardRoute
    }
    '/_app/auth/forgot-password/token': {
      id: '/_app/auth/forgot-password/token'
      path: '/auth/forgot-password/token'
      fullPath: '/auth/forgot-password/token'
      preLoaderRoute: typeof AppAuthForgotPasswordTokenImport
      parentRoute: typeof AppImport
    }
    '/_app/_consultation/consultations/': {
      id: '/_app/_consultation/consultations/'
      path: '/consultations'
      fullPath: '/consultations'
      preLoaderRoute: typeof AppConsultationConsultationsIndexImport
      parentRoute: typeof AppImport
    }
    '/_app/_dashboard/dashboard/': {
      id: '/_app/_dashboard/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof AppDashboardDashboardIndexImport
      parentRoute: typeof AppDashboardDashboardImport
    }
    '/_app/_doctor/doctor/': {
      id: '/_app/_doctor/doctor/'
      path: '/doctor'
      fullPath: '/doctor'
      preLoaderRoute: typeof AppDoctorDoctorIndexImport
      parentRoute: typeof AppDoctorImport
    }
    '/_app/auth/forgot-password/': {
      id: '/_app/auth/forgot-password/'
      path: '/auth/forgot-password'
      fullPath: '/auth/forgot-password'
      preLoaderRoute: typeof AppAuthForgotPasswordIndexImport
      parentRoute: typeof AppImport
    }
    '/_app/auth/set-profile/': {
      id: '/_app/auth/set-profile/'
      path: '/auth/set-profile'
      fullPath: '/auth/set-profile'
      preLoaderRoute: typeof AppAuthSetProfileIndexImport
      parentRoute: typeof AppImport
    }
    '/_app/_dashboard/dashboard/_consultation/clientconsultation': {
      id: '/_app/_dashboard/dashboard/_consultation/clientconsultation'
      path: '/clientconsultation'
      fullPath: '/dashboard/clientconsultation'
      preLoaderRoute: typeof AppDashboardDashboardConsultationClientconsultationImport
      parentRoute: typeof AppDashboardDashboardConsultationImport
    }
    '/_app/_dashboard/dashboard/_consultation/jitsiconsultation': {
      id: '/_app/_dashboard/dashboard/_consultation/jitsiconsultation'
      path: '/jitsiconsultation'
      fullPath: '/dashboard/jitsiconsultation'
      preLoaderRoute: typeof AppDashboardDashboardConsultationJitsiconsultationImport
      parentRoute: typeof AppDashboardDashboardConsultationImport
    }
    '/_app/_dashboard/dashboard/pharmacy/cart': {
      id: '/_app/_dashboard/dashboard/pharmacy/cart'
      path: '/pharmacy/cart'
      fullPath: '/dashboard/pharmacy/cart'
      preLoaderRoute: typeof AppDashboardDashboardPharmacyCartImport
      parentRoute: typeof AppDashboardDashboardImport
    }
    '/_app/_dashboard/dashboard/doctors/': {
      id: '/_app/_dashboard/dashboard/doctors/'
      path: '/doctors'
      fullPath: '/dashboard/doctors'
      preLoaderRoute: typeof AppDashboardDashboardDoctorsIndexImport
      parentRoute: typeof AppDashboardDashboardImport
    }
    '/_app/_dashboard/dashboard/profile/': {
      id: '/_app/_dashboard/dashboard/profile/'
      path: '/profile'
      fullPath: '/dashboard/profile'
      preLoaderRoute: typeof AppDashboardDashboardProfileIndexImport
      parentRoute: typeof AppDashboardDashboardImport
    }
    '/_app/_dashboard/dashboard/schedule/': {
      id: '/_app/_dashboard/dashboard/schedule/'
      path: '/schedule'
      fullPath: '/dashboard/schedule'
      preLoaderRoute: typeof AppDashboardDashboardScheduleIndexImport
      parentRoute: typeof AppDashboardDashboardImport
    }
    '/_app/_dashboard/dashboard/wallet/': {
      id: '/_app/_dashboard/dashboard/wallet/'
      path: '/wallet'
      fullPath: '/dashboard/wallet'
      preLoaderRoute: typeof AppDashboardDashboardWalletIndexImport
      parentRoute: typeof AppDashboardDashboardImport
    }
    '/_app/_doctor/doctor/dashboard/': {
      id: '/_app/_doctor/doctor/dashboard/'
      path: '/doctor/dashboard'
      fullPath: '/doctor/dashboard'
      preLoaderRoute: typeof AppDoctorDoctorDashboardIndexImport
      parentRoute: typeof AppDoctorImport
    }
    '/_app/_doctor/doctor/lab/': {
      id: '/_app/_doctor/doctor/lab/'
      path: '/doctor/lab'
      fullPath: '/doctor/lab'
      preLoaderRoute: typeof AppDoctorDoctorLabIndexImport
      parentRoute: typeof AppDoctorImport
    }
    '/_app/_doctor/doctor/message/': {
      id: '/_app/_doctor/doctor/message/'
      path: '/doctor/message'
      fullPath: '/doctor/message'
      preLoaderRoute: typeof AppDoctorDoctorMessageIndexImport
      parentRoute: typeof AppDoctorImport
    }
    '/_app/_doctor/doctor/patients/': {
      id: '/_app/_doctor/doctor/patients/'
      path: '/doctor/patients'
      fullPath: '/doctor/patients'
      preLoaderRoute: typeof AppDoctorDoctorPatientsIndexImport
      parentRoute: typeof AppDoctorImport
    }
    '/_app/_doctor/doctor/support/': {
      id: '/_app/_doctor/doctor/support/'
      path: '/doctor/support'
      fullPath: '/doctor/support'
      preLoaderRoute: typeof AppDoctorDoctorSupportIndexImport
      parentRoute: typeof AppDoctorImport
    }
    '/_app/auth/forgot-password/$token/': {
      id: '/_app/auth/forgot-password/$token/'
      path: '/auth/forgot-password/$token'
      fullPath: '/auth/forgot-password/$token'
      preLoaderRoute: typeof AppAuthForgotPasswordTokenIndexImport
      parentRoute: typeof AppImport
    }
    '/_app/_dashboard/dashboard/chats/$doctorId/': {
      id: '/_app/_dashboard/dashboard/chats/$doctorId/'
      path: '/chats/$doctorId'
      fullPath: '/dashboard/chats/$doctorId'
      preLoaderRoute: typeof AppDashboardDashboardChatsDoctorIdIndexImport
      parentRoute: typeof AppDashboardDashboardImport
    }
    '/_app/_dashboard/dashboard/doctors/$id/': {
      id: '/_app/_dashboard/dashboard/doctors/$id/'
      path: '/doctors/$id'
      fullPath: '/dashboard/doctors/$id'
      preLoaderRoute: typeof AppDashboardDashboardDoctorsIdIndexImport
      parentRoute: typeof AppDashboardDashboardImport
    }
    '/_app/_dashboard/dashboard/messages/$doctorId/': {
      id: '/_app/_dashboard/dashboard/messages/$doctorId/'
      path: '/messages/$doctorId'
      fullPath: '/dashboard/messages/$doctorId'
      preLoaderRoute: typeof AppDashboardDashboardMessagesDoctorIdIndexImport
      parentRoute: typeof AppDashboardDashboardImport
    }
    '/_app/_dashboard/dashboard/pharmacy/product/': {
      id: '/_app/_dashboard/dashboard/pharmacy/product/'
      path: '/pharmacy/product'
      fullPath: '/dashboard/pharmacy/product'
      preLoaderRoute: typeof AppDashboardDashboardPharmacyProductIndexImport
      parentRoute: typeof AppDashboardDashboardImport
    }
    '/_app/_doctor/doctor/dashboard/appointments/': {
      id: '/_app/_doctor/doctor/dashboard/appointments/'
      path: '/doctor/dashboard/appointments'
      fullPath: '/doctor/dashboard/appointments'
      preLoaderRoute: typeof AppDoctorDoctorDashboardAppointmentsIndexImport
      parentRoute: typeof AppDoctorImport
    }
    '/_app/_doctor/doctor/dashboard/earnings/': {
      id: '/_app/_doctor/doctor/dashboard/earnings/'
      path: '/doctor/dashboard/earnings'
      fullPath: '/doctor/dashboard/earnings'
      preLoaderRoute: typeof AppDoctorDoctorDashboardEarningsIndexImport
      parentRoute: typeof AppDoctorImport
    }
    '/_app/_doctor/doctor/dashboard/patients/': {
      id: '/_app/_doctor/doctor/dashboard/patients/'
      path: '/doctor/dashboard/patients'
      fullPath: '/doctor/dashboard/patients'
      preLoaderRoute: typeof AppDoctorDoctorDashboardPatientsIndexImport
      parentRoute: typeof AppDoctorImport
    }
    '/_app/_doctor/doctor/dashboard/profile/': {
      id: '/_app/_doctor/doctor/dashboard/profile/'
      path: '/doctor/dashboard/profile'
      fullPath: '/doctor/dashboard/profile'
      preLoaderRoute: typeof AppDoctorDoctorDashboardProfileIndexImport
      parentRoute: typeof AppDoctorImport
    }
    '/_app/_doctor/doctor/dashboard/wallet/': {
      id: '/_app/_doctor/doctor/dashboard/wallet/'
      path: '/doctor/dashboard/wallet'
      fullPath: '/doctor/dashboard/wallet'
      preLoaderRoute: typeof AppDoctorDoctorDashboardWalletIndexImport
      parentRoute: typeof AppDoctorImport
    }
    '/_app/_doctor/doctor/message/$patientId/': {
      id: '/_app/_doctor/doctor/message/$patientId/'
      path: '/doctor/message/$patientId'
      fullPath: '/doctor/message/$patientId'
      preLoaderRoute: typeof AppDoctorDoctorMessagePatientIdIndexImport
      parentRoute: typeof AppDoctorImport
    }
    '/_app/_dashboard/dashboard/pharmacy/product/$id/': {
      id: '/_app/_dashboard/dashboard/pharmacy/product/$id/'
      path: '/pharmacy/product/$id'
      fullPath: '/dashboard/pharmacy/product/$id'
      preLoaderRoute: typeof AppDashboardDashboardPharmacyProductIdIndexImport
      parentRoute: typeof AppDashboardDashboardImport
    }
    '/_app/_doctor/doctor/dashboard/patients/$id/': {
      id: '/_app/_doctor/doctor/dashboard/patients/$id/'
      path: '/doctor/dashboard/patients/$id'
      fullPath: '/doctor/dashboard/patients/$id'
      preLoaderRoute: typeof AppDoctorDoctorDashboardPatientsIdIndexImport
      parentRoute: typeof AppDoctorImport
    }
  }
}

// Create and export the route tree

interface AppDashboardDashboardConsultationRouteChildren {
  AppDashboardDashboardConsultationClientconsultationRoute: typeof AppDashboardDashboardConsultationClientconsultationRoute
  AppDashboardDashboardConsultationJitsiconsultationRoute: typeof AppDashboardDashboardConsultationJitsiconsultationRoute
}

const AppDashboardDashboardConsultationRouteChildren: AppDashboardDashboardConsultationRouteChildren =
  {
    AppDashboardDashboardConsultationClientconsultationRoute:
      AppDashboardDashboardConsultationClientconsultationRoute,
    AppDashboardDashboardConsultationJitsiconsultationRoute:
      AppDashboardDashboardConsultationJitsiconsultationRoute,
  }

const AppDashboardDashboardConsultationRouteWithChildren =
  AppDashboardDashboardConsultationRoute._addFileChildren(
    AppDashboardDashboardConsultationRouteChildren,
  )

interface AppDashboardDashboardRouteChildren {
  AppDashboardDashboardConsultationRoute: typeof AppDashboardDashboardConsultationRouteWithChildren
  AppDashboardDashboardIndexRoute: typeof AppDashboardDashboardIndexRoute
  AppDashboardDashboardPharmacyCartRoute: typeof AppDashboardDashboardPharmacyCartRoute
  AppDashboardDashboardDoctorsIndexRoute: typeof AppDashboardDashboardDoctorsIndexRoute
  AppDashboardDashboardProfileIndexRoute: typeof AppDashboardDashboardProfileIndexRoute
  AppDashboardDashboardScheduleIndexRoute: typeof AppDashboardDashboardScheduleIndexRoute
  AppDashboardDashboardWalletIndexRoute: typeof AppDashboardDashboardWalletIndexRoute
  AppDashboardDashboardChatsDoctorIdIndexRoute: typeof AppDashboardDashboardChatsDoctorIdIndexRoute
  AppDashboardDashboardDoctorsIdIndexRoute: typeof AppDashboardDashboardDoctorsIdIndexRoute
  AppDashboardDashboardMessagesDoctorIdIndexRoute: typeof AppDashboardDashboardMessagesDoctorIdIndexRoute
  AppDashboardDashboardPharmacyProductIndexRoute: typeof AppDashboardDashboardPharmacyProductIndexRoute
  AppDashboardDashboardPharmacyProductIdIndexRoute: typeof AppDashboardDashboardPharmacyProductIdIndexRoute
}

const AppDashboardDashboardRouteChildren: AppDashboardDashboardRouteChildren = {
  AppDashboardDashboardConsultationRoute:
    AppDashboardDashboardConsultationRouteWithChildren,
  AppDashboardDashboardIndexRoute: AppDashboardDashboardIndexRoute,
  AppDashboardDashboardPharmacyCartRoute:
    AppDashboardDashboardPharmacyCartRoute,
  AppDashboardDashboardDoctorsIndexRoute:
    AppDashboardDashboardDoctorsIndexRoute,
  AppDashboardDashboardProfileIndexRoute:
    AppDashboardDashboardProfileIndexRoute,
  AppDashboardDashboardScheduleIndexRoute:
    AppDashboardDashboardScheduleIndexRoute,
  AppDashboardDashboardWalletIndexRoute: AppDashboardDashboardWalletIndexRoute,
  AppDashboardDashboardChatsDoctorIdIndexRoute:
    AppDashboardDashboardChatsDoctorIdIndexRoute,
  AppDashboardDashboardDoctorsIdIndexRoute:
    AppDashboardDashboardDoctorsIdIndexRoute,
  AppDashboardDashboardMessagesDoctorIdIndexRoute:
    AppDashboardDashboardMessagesDoctorIdIndexRoute,
  AppDashboardDashboardPharmacyProductIndexRoute:
    AppDashboardDashboardPharmacyProductIndexRoute,
  AppDashboardDashboardPharmacyProductIdIndexRoute:
    AppDashboardDashboardPharmacyProductIdIndexRoute,
}

const AppDashboardDashboardRouteWithChildren =
  AppDashboardDashboardRoute._addFileChildren(
    AppDashboardDashboardRouteChildren,
  )

interface AppDashboardRouteChildren {
  AppDashboardDashboardRoute: typeof AppDashboardDashboardRouteWithChildren
}

const AppDashboardRouteChildren: AppDashboardRouteChildren = {
  AppDashboardDashboardRoute: AppDashboardDashboardRouteWithChildren,
}

const AppDashboardRouteWithChildren = AppDashboardRoute._addFileChildren(
  AppDashboardRouteChildren,
)

interface AppDoctorRouteChildren {
  AppDoctorDoctorIndexRoute: typeof AppDoctorDoctorIndexRoute
  AppDoctorDoctorDashboardIndexRoute: typeof AppDoctorDoctorDashboardIndexRoute
  AppDoctorDoctorLabIndexRoute: typeof AppDoctorDoctorLabIndexRoute
  AppDoctorDoctorMessageIndexRoute: typeof AppDoctorDoctorMessageIndexRoute
  AppDoctorDoctorPatientsIndexRoute: typeof AppDoctorDoctorPatientsIndexRoute
  AppDoctorDoctorSupportIndexRoute: typeof AppDoctorDoctorSupportIndexRoute
  AppDoctorDoctorDashboardAppointmentsIndexRoute: typeof AppDoctorDoctorDashboardAppointmentsIndexRoute
  AppDoctorDoctorDashboardEarningsIndexRoute: typeof AppDoctorDoctorDashboardEarningsIndexRoute
  AppDoctorDoctorDashboardPatientsIndexRoute: typeof AppDoctorDoctorDashboardPatientsIndexRoute
  AppDoctorDoctorDashboardProfileIndexRoute: typeof AppDoctorDoctorDashboardProfileIndexRoute
  AppDoctorDoctorDashboardWalletIndexRoute: typeof AppDoctorDoctorDashboardWalletIndexRoute
  AppDoctorDoctorMessagePatientIdIndexRoute: typeof AppDoctorDoctorMessagePatientIdIndexRoute
  AppDoctorDoctorDashboardPatientsIdIndexRoute: typeof AppDoctorDoctorDashboardPatientsIdIndexRoute
}

const AppDoctorRouteChildren: AppDoctorRouteChildren = {
  AppDoctorDoctorIndexRoute: AppDoctorDoctorIndexRoute,
  AppDoctorDoctorDashboardIndexRoute: AppDoctorDoctorDashboardIndexRoute,
  AppDoctorDoctorLabIndexRoute: AppDoctorDoctorLabIndexRoute,
  AppDoctorDoctorMessageIndexRoute: AppDoctorDoctorMessageIndexRoute,
  AppDoctorDoctorPatientsIndexRoute: AppDoctorDoctorPatientsIndexRoute,
  AppDoctorDoctorSupportIndexRoute: AppDoctorDoctorSupportIndexRoute,
  AppDoctorDoctorDashboardAppointmentsIndexRoute:
    AppDoctorDoctorDashboardAppointmentsIndexRoute,
  AppDoctorDoctorDashboardEarningsIndexRoute:
    AppDoctorDoctorDashboardEarningsIndexRoute,
  AppDoctorDoctorDashboardPatientsIndexRoute:
    AppDoctorDoctorDashboardPatientsIndexRoute,
  AppDoctorDoctorDashboardProfileIndexRoute:
    AppDoctorDoctorDashboardProfileIndexRoute,
  AppDoctorDoctorDashboardWalletIndexRoute:
    AppDoctorDoctorDashboardWalletIndexRoute,
  AppDoctorDoctorMessagePatientIdIndexRoute:
    AppDoctorDoctorMessagePatientIdIndexRoute,
  AppDoctorDoctorDashboardPatientsIdIndexRoute:
    AppDoctorDoctorDashboardPatientsIdIndexRoute,
}

const AppDoctorRouteWithChildren = AppDoctorRoute._addFileChildren(
  AppDoctorRouteChildren,
)

interface AppRouteChildren {
  AppDashboardRoute: typeof AppDashboardRouteWithChildren
  AppDoctorRoute: typeof AppDoctorRouteWithChildren
  AppAuthSignInRoute: typeof AppAuthSignInRoute
  AppAuthSignUpRoute: typeof AppAuthSignUpRoute
  AppAuthVerifyRoute: typeof AppAuthVerifyRoute
  AppTestcallCallRoute: typeof AppTestcallCallRoute
  AppHelpIndexRoute: typeof AppHelpIndexRoute
  AppOnboardingIndexRoute: typeof AppOnboardingIndexRoute
  AppPrivacyIndexRoute: typeof AppPrivacyIndexRoute
  AppTermsIndexRoute: typeof AppTermsIndexRoute
  AppTestcallIndexRoute: typeof AppTestcallIndexRoute
  AppAuthForgotPasswordTokenRoute: typeof AppAuthForgotPasswordTokenRoute
  AppConsultationConsultationsIndexRoute: typeof AppConsultationConsultationsIndexRoute
  AppAuthForgotPasswordIndexRoute: typeof AppAuthForgotPasswordIndexRoute
  AppAuthSetProfileIndexRoute: typeof AppAuthSetProfileIndexRoute
  AppAuthForgotPasswordTokenIndexRoute: typeof AppAuthForgotPasswordTokenIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppDashboardRoute: AppDashboardRouteWithChildren,
  AppDoctorRoute: AppDoctorRouteWithChildren,
  AppAuthSignInRoute: AppAuthSignInRoute,
  AppAuthSignUpRoute: AppAuthSignUpRoute,
  AppAuthVerifyRoute: AppAuthVerifyRoute,
  AppTestcallCallRoute: AppTestcallCallRoute,
  AppHelpIndexRoute: AppHelpIndexRoute,
  AppOnboardingIndexRoute: AppOnboardingIndexRoute,
  AppPrivacyIndexRoute: AppPrivacyIndexRoute,
  AppTermsIndexRoute: AppTermsIndexRoute,
  AppTestcallIndexRoute: AppTestcallIndexRoute,
  AppAuthForgotPasswordTokenRoute: AppAuthForgotPasswordTokenRoute,
  AppConsultationConsultationsIndexRoute:
    AppConsultationConsultationsIndexRoute,
  AppAuthForgotPasswordIndexRoute: AppAuthForgotPasswordIndexRoute,
  AppAuthSetProfileIndexRoute: AppAuthSetProfileIndexRoute,
  AppAuthForgotPasswordTokenIndexRoute: AppAuthForgotPasswordTokenIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '': typeof AppDoctorRouteWithChildren
  '/auth/sign-in': typeof AppAuthSignInRoute
  '/auth/sign-up': typeof AppAuthSignUpRoute
  '/auth/verify': typeof AppAuthVerifyRoute
  '/testcall/call': typeof AppTestcallCallRoute
  '/help': typeof AppHelpIndexRoute
  '/onboarding': typeof AppOnboardingIndexRoute
  '/privacy': typeof AppPrivacyIndexRoute
  '/terms': typeof AppTermsIndexRoute
  '/testcall': typeof AppTestcallIndexRoute
  '/dashboard': typeof AppDashboardDashboardConsultationRouteWithChildren
  '/auth/forgot-password/token': typeof AppAuthForgotPasswordTokenRoute
  '/consultations': typeof AppConsultationConsultationsIndexRoute
  '/dashboard/': typeof AppDashboardDashboardIndexRoute
  '/doctor': typeof AppDoctorDoctorIndexRoute
  '/auth/forgot-password': typeof AppAuthForgotPasswordIndexRoute
  '/auth/set-profile': typeof AppAuthSetProfileIndexRoute
  '/dashboard/clientconsultation': typeof AppDashboardDashboardConsultationClientconsultationRoute
  '/dashboard/jitsiconsultation': typeof AppDashboardDashboardConsultationJitsiconsultationRoute
  '/dashboard/pharmacy/cart': typeof AppDashboardDashboardPharmacyCartRoute
  '/dashboard/doctors': typeof AppDashboardDashboardDoctorsIndexRoute
  '/dashboard/profile': typeof AppDashboardDashboardProfileIndexRoute
  '/dashboard/schedule': typeof AppDashboardDashboardScheduleIndexRoute
  '/dashboard/wallet': typeof AppDashboardDashboardWalletIndexRoute
  '/doctor/dashboard': typeof AppDoctorDoctorDashboardIndexRoute
  '/doctor/lab': typeof AppDoctorDoctorLabIndexRoute
  '/doctor/message': typeof AppDoctorDoctorMessageIndexRoute
  '/doctor/patients': typeof AppDoctorDoctorPatientsIndexRoute
  '/doctor/support': typeof AppDoctorDoctorSupportIndexRoute
  '/auth/forgot-password/$token': typeof AppAuthForgotPasswordTokenIndexRoute
  '/dashboard/chats/$doctorId': typeof AppDashboardDashboardChatsDoctorIdIndexRoute
  '/dashboard/doctors/$id': typeof AppDashboardDashboardDoctorsIdIndexRoute
  '/dashboard/messages/$doctorId': typeof AppDashboardDashboardMessagesDoctorIdIndexRoute
  '/dashboard/pharmacy/product': typeof AppDashboardDashboardPharmacyProductIndexRoute
  '/doctor/dashboard/appointments': typeof AppDoctorDoctorDashboardAppointmentsIndexRoute
  '/doctor/dashboard/earnings': typeof AppDoctorDoctorDashboardEarningsIndexRoute
  '/doctor/dashboard/patients': typeof AppDoctorDoctorDashboardPatientsIndexRoute
  '/doctor/dashboard/profile': typeof AppDoctorDoctorDashboardProfileIndexRoute
  '/doctor/dashboard/wallet': typeof AppDoctorDoctorDashboardWalletIndexRoute
  '/doctor/message/$patientId': typeof AppDoctorDoctorMessagePatientIdIndexRoute
  '/dashboard/pharmacy/product/$id': typeof AppDashboardDashboardPharmacyProductIdIndexRoute
  '/doctor/dashboard/patients/$id': typeof AppDoctorDoctorDashboardPatientsIdIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '': typeof AppDoctorRouteWithChildren
  '/auth/sign-in': typeof AppAuthSignInRoute
  '/auth/sign-up': typeof AppAuthSignUpRoute
  '/auth/verify': typeof AppAuthVerifyRoute
  '/testcall/call': typeof AppTestcallCallRoute
  '/help': typeof AppHelpIndexRoute
  '/onboarding': typeof AppOnboardingIndexRoute
  '/privacy': typeof AppPrivacyIndexRoute
  '/terms': typeof AppTermsIndexRoute
  '/testcall': typeof AppTestcallIndexRoute
  '/dashboard': typeof AppDashboardDashboardIndexRoute
  '/auth/forgot-password/token': typeof AppAuthForgotPasswordTokenRoute
  '/consultations': typeof AppConsultationConsultationsIndexRoute
  '/doctor': typeof AppDoctorDoctorIndexRoute
  '/auth/forgot-password': typeof AppAuthForgotPasswordIndexRoute
  '/auth/set-profile': typeof AppAuthSetProfileIndexRoute
  '/dashboard/clientconsultation': typeof AppDashboardDashboardConsultationClientconsultationRoute
  '/dashboard/jitsiconsultation': typeof AppDashboardDashboardConsultationJitsiconsultationRoute
  '/dashboard/pharmacy/cart': typeof AppDashboardDashboardPharmacyCartRoute
  '/dashboard/doctors': typeof AppDashboardDashboardDoctorsIndexRoute
  '/dashboard/profile': typeof AppDashboardDashboardProfileIndexRoute
  '/dashboard/schedule': typeof AppDashboardDashboardScheduleIndexRoute
  '/dashboard/wallet': typeof AppDashboardDashboardWalletIndexRoute
  '/doctor/dashboard': typeof AppDoctorDoctorDashboardIndexRoute
  '/doctor/lab': typeof AppDoctorDoctorLabIndexRoute
  '/doctor/message': typeof AppDoctorDoctorMessageIndexRoute
  '/doctor/patients': typeof AppDoctorDoctorPatientsIndexRoute
  '/doctor/support': typeof AppDoctorDoctorSupportIndexRoute
  '/auth/forgot-password/$token': typeof AppAuthForgotPasswordTokenIndexRoute
  '/dashboard/chats/$doctorId': typeof AppDashboardDashboardChatsDoctorIdIndexRoute
  '/dashboard/doctors/$id': typeof AppDashboardDashboardDoctorsIdIndexRoute
  '/dashboard/messages/$doctorId': typeof AppDashboardDashboardMessagesDoctorIdIndexRoute
  '/dashboard/pharmacy/product': typeof AppDashboardDashboardPharmacyProductIndexRoute
  '/doctor/dashboard/appointments': typeof AppDoctorDoctorDashboardAppointmentsIndexRoute
  '/doctor/dashboard/earnings': typeof AppDoctorDoctorDashboardEarningsIndexRoute
  '/doctor/dashboard/patients': typeof AppDoctorDoctorDashboardPatientsIndexRoute
  '/doctor/dashboard/profile': typeof AppDoctorDoctorDashboardProfileIndexRoute
  '/doctor/dashboard/wallet': typeof AppDoctorDoctorDashboardWalletIndexRoute
  '/doctor/message/$patientId': typeof AppDoctorDoctorMessagePatientIdIndexRoute
  '/dashboard/pharmacy/product/$id': typeof AppDashboardDashboardPharmacyProductIdIndexRoute
  '/doctor/dashboard/patients/$id': typeof AppDoctorDoctorDashboardPatientsIdIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/_app/_dashboard': typeof AppDashboardRouteWithChildren
  '/_app/_doctor': typeof AppDoctorRouteWithChildren
  '/_app/auth/sign-in': typeof AppAuthSignInRoute
  '/_app/auth/sign-up': typeof AppAuthSignUpRoute
  '/_app/auth/verify': typeof AppAuthVerifyRoute
  '/_app/testcall/call': typeof AppTestcallCallRoute
  '/_app/help/': typeof AppHelpIndexRoute
  '/_app/onboarding/': typeof AppOnboardingIndexRoute
  '/_app/privacy/': typeof AppPrivacyIndexRoute
  '/_app/terms/': typeof AppTermsIndexRoute
  '/_app/testcall/': typeof AppTestcallIndexRoute
  '/_app/_dashboard/dashboard': typeof AppDashboardDashboardRouteWithChildren
  '/_app/_dashboard/dashboard/_consultation': typeof AppDashboardDashboardConsultationRouteWithChildren
  '/_app/auth/forgot-password/token': typeof AppAuthForgotPasswordTokenRoute
  '/_app/_consultation/consultations/': typeof AppConsultationConsultationsIndexRoute
  '/_app/_dashboard/dashboard/': typeof AppDashboardDashboardIndexRoute
  '/_app/_doctor/doctor/': typeof AppDoctorDoctorIndexRoute
  '/_app/auth/forgot-password/': typeof AppAuthForgotPasswordIndexRoute
  '/_app/auth/set-profile/': typeof AppAuthSetProfileIndexRoute
  '/_app/_dashboard/dashboard/_consultation/clientconsultation': typeof AppDashboardDashboardConsultationClientconsultationRoute
  '/_app/_dashboard/dashboard/_consultation/jitsiconsultation': typeof AppDashboardDashboardConsultationJitsiconsultationRoute
  '/_app/_dashboard/dashboard/pharmacy/cart': typeof AppDashboardDashboardPharmacyCartRoute
  '/_app/_dashboard/dashboard/doctors/': typeof AppDashboardDashboardDoctorsIndexRoute
  '/_app/_dashboard/dashboard/profile/': typeof AppDashboardDashboardProfileIndexRoute
  '/_app/_dashboard/dashboard/schedule/': typeof AppDashboardDashboardScheduleIndexRoute
  '/_app/_dashboard/dashboard/wallet/': typeof AppDashboardDashboardWalletIndexRoute
  '/_app/_doctor/doctor/dashboard/': typeof AppDoctorDoctorDashboardIndexRoute
  '/_app/_doctor/doctor/lab/': typeof AppDoctorDoctorLabIndexRoute
  '/_app/_doctor/doctor/message/': typeof AppDoctorDoctorMessageIndexRoute
  '/_app/_doctor/doctor/patients/': typeof AppDoctorDoctorPatientsIndexRoute
  '/_app/_doctor/doctor/support/': typeof AppDoctorDoctorSupportIndexRoute
  '/_app/auth/forgot-password/$token/': typeof AppAuthForgotPasswordTokenIndexRoute
  '/_app/_dashboard/dashboard/chats/$doctorId/': typeof AppDashboardDashboardChatsDoctorIdIndexRoute
  '/_app/_dashboard/dashboard/doctors/$id/': typeof AppDashboardDashboardDoctorsIdIndexRoute
  '/_app/_dashboard/dashboard/messages/$doctorId/': typeof AppDashboardDashboardMessagesDoctorIdIndexRoute
  '/_app/_dashboard/dashboard/pharmacy/product/': typeof AppDashboardDashboardPharmacyProductIndexRoute
  '/_app/_doctor/doctor/dashboard/appointments/': typeof AppDoctorDoctorDashboardAppointmentsIndexRoute
  '/_app/_doctor/doctor/dashboard/earnings/': typeof AppDoctorDoctorDashboardEarningsIndexRoute
  '/_app/_doctor/doctor/dashboard/patients/': typeof AppDoctorDoctorDashboardPatientsIndexRoute
  '/_app/_doctor/doctor/dashboard/profile/': typeof AppDoctorDoctorDashboardProfileIndexRoute
  '/_app/_doctor/doctor/dashboard/wallet/': typeof AppDoctorDoctorDashboardWalletIndexRoute
  '/_app/_doctor/doctor/message/$patientId/': typeof AppDoctorDoctorMessagePatientIdIndexRoute
  '/_app/_dashboard/dashboard/pharmacy/product/$id/': typeof AppDashboardDashboardPharmacyProductIdIndexRoute
  '/_app/_doctor/doctor/dashboard/patients/$id/': typeof AppDoctorDoctorDashboardPatientsIdIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | ''
    | '/auth/sign-in'
    | '/auth/sign-up'
    | '/auth/verify'
    | '/testcall/call'
    | '/help'
    | '/onboarding'
    | '/privacy'
    | '/terms'
    | '/testcall'
    | '/dashboard'
    | '/auth/forgot-password/token'
    | '/consultations'
    | '/dashboard/'
    | '/doctor'
    | '/auth/forgot-password'
    | '/auth/set-profile'
    | '/dashboard/clientconsultation'
    | '/dashboard/jitsiconsultation'
    | '/dashboard/pharmacy/cart'
    | '/dashboard/doctors'
    | '/dashboard/profile'
    | '/dashboard/schedule'
    | '/dashboard/wallet'
    | '/doctor/dashboard'
    | '/doctor/lab'
    | '/doctor/message'
    | '/doctor/patients'
    | '/doctor/support'
    | '/auth/forgot-password/$token'
    | '/dashboard/chats/$doctorId'
    | '/dashboard/doctors/$id'
    | '/dashboard/messages/$doctorId'
    | '/dashboard/pharmacy/product'
    | '/doctor/dashboard/appointments'
    | '/doctor/dashboard/earnings'
    | '/doctor/dashboard/patients'
    | '/doctor/dashboard/profile'
    | '/doctor/dashboard/wallet'
    | '/doctor/message/$patientId'
    | '/dashboard/pharmacy/product/$id'
    | '/doctor/dashboard/patients/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | ''
    | '/auth/sign-in'
    | '/auth/sign-up'
    | '/auth/verify'
    | '/testcall/call'
    | '/help'
    | '/onboarding'
    | '/privacy'
    | '/terms'
    | '/testcall'
    | '/dashboard'
    | '/auth/forgot-password/token'
    | '/consultations'
    | '/doctor'
    | '/auth/forgot-password'
    | '/auth/set-profile'
    | '/dashboard/clientconsultation'
    | '/dashboard/jitsiconsultation'
    | '/dashboard/pharmacy/cart'
    | '/dashboard/doctors'
    | '/dashboard/profile'
    | '/dashboard/schedule'
    | '/dashboard/wallet'
    | '/doctor/dashboard'
    | '/doctor/lab'
    | '/doctor/message'
    | '/doctor/patients'
    | '/doctor/support'
    | '/auth/forgot-password/$token'
    | '/dashboard/chats/$doctorId'
    | '/dashboard/doctors/$id'
    | '/dashboard/messages/$doctorId'
    | '/dashboard/pharmacy/product'
    | '/doctor/dashboard/appointments'
    | '/doctor/dashboard/earnings'
    | '/doctor/dashboard/patients'
    | '/doctor/dashboard/profile'
    | '/doctor/dashboard/wallet'
    | '/doctor/message/$patientId'
    | '/dashboard/pharmacy/product/$id'
    | '/doctor/dashboard/patients/$id'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/_app/_dashboard'
    | '/_app/_doctor'
    | '/_app/auth/sign-in'
    | '/_app/auth/sign-up'
    | '/_app/auth/verify'
    | '/_app/testcall/call'
    | '/_app/help/'
    | '/_app/onboarding/'
    | '/_app/privacy/'
    | '/_app/terms/'
    | '/_app/testcall/'
    | '/_app/_dashboard/dashboard'
    | '/_app/_dashboard/dashboard/_consultation'
    | '/_app/auth/forgot-password/token'
    | '/_app/_consultation/consultations/'
    | '/_app/_dashboard/dashboard/'
    | '/_app/_doctor/doctor/'
    | '/_app/auth/forgot-password/'
    | '/_app/auth/set-profile/'
    | '/_app/_dashboard/dashboard/_consultation/clientconsultation'
    | '/_app/_dashboard/dashboard/_consultation/jitsiconsultation'
    | '/_app/_dashboard/dashboard/pharmacy/cart'
    | '/_app/_dashboard/dashboard/doctors/'
    | '/_app/_dashboard/dashboard/profile/'
    | '/_app/_dashboard/dashboard/schedule/'
    | '/_app/_dashboard/dashboard/wallet/'
    | '/_app/_doctor/doctor/dashboard/'
    | '/_app/_doctor/doctor/lab/'
    | '/_app/_doctor/doctor/message/'
    | '/_app/_doctor/doctor/patients/'
    | '/_app/_doctor/doctor/support/'
    | '/_app/auth/forgot-password/$token/'
    | '/_app/_dashboard/dashboard/chats/$doctorId/'
    | '/_app/_dashboard/dashboard/doctors/$id/'
    | '/_app/_dashboard/dashboard/messages/$doctorId/'
    | '/_app/_dashboard/dashboard/pharmacy/product/'
    | '/_app/_doctor/doctor/dashboard/appointments/'
    | '/_app/_doctor/doctor/dashboard/earnings/'
    | '/_app/_doctor/doctor/dashboard/patients/'
    | '/_app/_doctor/doctor/dashboard/profile/'
    | '/_app/_doctor/doctor/dashboard/wallet/'
    | '/_app/_doctor/doctor/message/$patientId/'
    | '/_app/_dashboard/dashboard/pharmacy/product/$id/'
    | '/_app/_doctor/doctor/dashboard/patients/$id/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/_app"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/_app": {
      "filePath": "_app.tsx",
      "children": [
        "/_app/_dashboard",
        "/_app/_doctor",
        "/_app/auth/sign-in",
        "/_app/auth/sign-up",
        "/_app/auth/verify",
        "/_app/testcall/call",
        "/_app/help/",
        "/_app/onboarding/",
        "/_app/privacy/",
        "/_app/terms/",
        "/_app/testcall/",
        "/_app/auth/forgot-password/token",
        "/_app/_consultation/consultations/",
        "/_app/auth/forgot-password/",
        "/_app/auth/set-profile/",
        "/_app/auth/forgot-password/$token/"
      ]
    },
    "/_app/_dashboard": {
      "filePath": "_app/_dashboard.tsx",
      "parent": "/_app",
      "children": [
        "/_app/_dashboard/dashboard"
      ]
    },
    "/_app/_doctor": {
      "filePath": "_app/_doctor.tsx",
      "parent": "/_app",
      "children": [
        "/_app/_doctor/doctor/",
        "/_app/_doctor/doctor/dashboard/",
        "/_app/_doctor/doctor/lab/",
        "/_app/_doctor/doctor/message/",
        "/_app/_doctor/doctor/patients/",
        "/_app/_doctor/doctor/support/",
        "/_app/_doctor/doctor/dashboard/appointments/",
        "/_app/_doctor/doctor/dashboard/earnings/",
        "/_app/_doctor/doctor/dashboard/patients/",
        "/_app/_doctor/doctor/dashboard/profile/",
        "/_app/_doctor/doctor/dashboard/wallet/",
        "/_app/_doctor/doctor/message/$patientId/",
        "/_app/_doctor/doctor/dashboard/patients/$id/"
      ]
    },
    "/_app/auth/sign-in": {
      "filePath": "_app/auth/sign-in.tsx",
      "parent": "/_app"
    },
    "/_app/auth/sign-up": {
      "filePath": "_app/auth/sign-up.tsx",
      "parent": "/_app"
    },
    "/_app/auth/verify": {
      "filePath": "_app/auth/verify.tsx",
      "parent": "/_app"
    },
    "/_app/testcall/call": {
      "filePath": "_app/testcall/call.tsx",
      "parent": "/_app"
    },
    "/_app/help/": {
      "filePath": "_app/help/index.tsx",
      "parent": "/_app"
    },
    "/_app/onboarding/": {
      "filePath": "_app/onboarding/index.tsx",
      "parent": "/_app"
    },
    "/_app/privacy/": {
      "filePath": "_app/privacy/index.tsx",
      "parent": "/_app"
    },
    "/_app/terms/": {
      "filePath": "_app/terms/index.tsx",
      "parent": "/_app"
    },
    "/_app/testcall/": {
      "filePath": "_app/testcall/index.tsx",
      "parent": "/_app"
    },
    "/_app/_dashboard/dashboard": {
      "filePath": "_app/_dashboard/dashboard",
      "parent": "/_app/_dashboard",
      "children": [
        "/_app/_dashboard/dashboard/_consultation",
        "/_app/_dashboard/dashboard/",
        "/_app/_dashboard/dashboard/pharmacy/cart",
        "/_app/_dashboard/dashboard/doctors/",
        "/_app/_dashboard/dashboard/profile/",
        "/_app/_dashboard/dashboard/schedule/",
        "/_app/_dashboard/dashboard/wallet/",
        "/_app/_dashboard/dashboard/chats/$doctorId/",
        "/_app/_dashboard/dashboard/doctors/$id/",
        "/_app/_dashboard/dashboard/messages/$doctorId/",
        "/_app/_dashboard/dashboard/pharmacy/product/",
        "/_app/_dashboard/dashboard/pharmacy/product/$id/"
      ]
    },
    "/_app/_dashboard/dashboard/_consultation": {
      "filePath": "_app/_dashboard/dashboard/_consultation.tsx",
      "parent": "/_app/_dashboard/dashboard",
      "children": [
        "/_app/_dashboard/dashboard/_consultation/clientconsultation",
        "/_app/_dashboard/dashboard/_consultation/jitsiconsultation"
      ]
    },
    "/_app/auth/forgot-password/token": {
      "filePath": "_app/auth/forgot-password/token.tsx",
      "parent": "/_app"
    },
    "/_app/_consultation/consultations/": {
      "filePath": "_app/_consultation/consultations/index.tsx",
      "parent": "/_app"
    },
    "/_app/_dashboard/dashboard/": {
      "filePath": "_app/_dashboard/dashboard/index.tsx",
      "parent": "/_app/_dashboard/dashboard"
    },
    "/_app/_doctor/doctor/": {
      "filePath": "_app/_doctor/doctor/index.tsx",
      "parent": "/_app/_doctor"
    },
    "/_app/auth/forgot-password/": {
      "filePath": "_app/auth/forgot-password/index.tsx",
      "parent": "/_app"
    },
    "/_app/auth/set-profile/": {
      "filePath": "_app/auth/set-profile/index.tsx",
      "parent": "/_app"
    },
    "/_app/_dashboard/dashboard/_consultation/clientconsultation": {
      "filePath": "_app/_dashboard/dashboard/_consultation/clientconsultation.tsx",
      "parent": "/_app/_dashboard/dashboard/_consultation"
    },
    "/_app/_dashboard/dashboard/_consultation/jitsiconsultation": {
      "filePath": "_app/_dashboard/dashboard/_consultation/jitsiconsultation.tsx",
      "parent": "/_app/_dashboard/dashboard/_consultation"
    },
    "/_app/_dashboard/dashboard/pharmacy/cart": {
      "filePath": "_app/_dashboard/dashboard/pharmacy/cart.tsx",
      "parent": "/_app/_dashboard/dashboard"
    },
    "/_app/_dashboard/dashboard/doctors/": {
      "filePath": "_app/_dashboard/dashboard/doctors/index.tsx",
      "parent": "/_app/_dashboard/dashboard"
    },
    "/_app/_dashboard/dashboard/profile/": {
      "filePath": "_app/_dashboard/dashboard/profile/index.tsx",
      "parent": "/_app/_dashboard/dashboard"
    },
    "/_app/_dashboard/dashboard/schedule/": {
      "filePath": "_app/_dashboard/dashboard/schedule/index.tsx",
      "parent": "/_app/_dashboard/dashboard"
    },
    "/_app/_dashboard/dashboard/wallet/": {
      "filePath": "_app/_dashboard/dashboard/wallet/index.tsx",
      "parent": "/_app/_dashboard/dashboard"
    },
    "/_app/_doctor/doctor/dashboard/": {
      "filePath": "_app/_doctor/doctor/dashboard/index.tsx",
      "parent": "/_app/_doctor"
    },
    "/_app/_doctor/doctor/lab/": {
      "filePath": "_app/_doctor/doctor/lab/index.tsx",
      "parent": "/_app/_doctor"
    },
    "/_app/_doctor/doctor/message/": {
      "filePath": "_app/_doctor/doctor/message/index.tsx",
      "parent": "/_app/_doctor"
    },
    "/_app/_doctor/doctor/patients/": {
      "filePath": "_app/_doctor/doctor/patients/index.tsx",
      "parent": "/_app/_doctor"
    },
    "/_app/_doctor/doctor/support/": {
      "filePath": "_app/_doctor/doctor/support/index.tsx",
      "parent": "/_app/_doctor"
    },
    "/_app/auth/forgot-password/$token/": {
      "filePath": "_app/auth/forgot-password/$token/index.tsx",
      "parent": "/_app"
    },
    "/_app/_dashboard/dashboard/chats/$doctorId/": {
      "filePath": "_app/_dashboard/dashboard/chats/$doctorId/index.tsx",
      "parent": "/_app/_dashboard/dashboard"
    },
    "/_app/_dashboard/dashboard/doctors/$id/": {
      "filePath": "_app/_dashboard/dashboard/doctors/$id/index.tsx",
      "parent": "/_app/_dashboard/dashboard"
    },
    "/_app/_dashboard/dashboard/messages/$doctorId/": {
      "filePath": "_app/_dashboard/dashboard/messages/$doctorId/index.tsx",
      "parent": "/_app/_dashboard/dashboard"
    },
    "/_app/_dashboard/dashboard/pharmacy/product/": {
      "filePath": "_app/_dashboard/dashboard/pharmacy/product/index.tsx",
      "parent": "/_app/_dashboard/dashboard"
    },
    "/_app/_doctor/doctor/dashboard/appointments/": {
      "filePath": "_app/_doctor/doctor/dashboard/appointments/index.tsx",
      "parent": "/_app/_doctor"
    },
    "/_app/_doctor/doctor/dashboard/earnings/": {
      "filePath": "_app/_doctor/doctor/dashboard/earnings/index.tsx",
      "parent": "/_app/_doctor"
    },
    "/_app/_doctor/doctor/dashboard/patients/": {
      "filePath": "_app/_doctor/doctor/dashboard/patients/index.tsx",
      "parent": "/_app/_doctor"
    },
    "/_app/_doctor/doctor/dashboard/profile/": {
      "filePath": "_app/_doctor/doctor/dashboard/profile/index.tsx",
      "parent": "/_app/_doctor"
    },
    "/_app/_doctor/doctor/dashboard/wallet/": {
      "filePath": "_app/_doctor/doctor/dashboard/wallet/index.tsx",
      "parent": "/_app/_doctor"
    },
    "/_app/_doctor/doctor/message/$patientId/": {
      "filePath": "_app/_doctor/doctor/message/$patientId/index.tsx",
      "parent": "/_app/_doctor"
    },
    "/_app/_dashboard/dashboard/pharmacy/product/$id/": {
      "filePath": "_app/_dashboard/dashboard/pharmacy/product/$id/index.tsx",
      "parent": "/_app/_dashboard/dashboard"
    },
    "/_app/_doctor/doctor/dashboard/patients/$id/": {
      "filePath": "_app/_doctor/doctor/dashboard/patients/$id/index.tsx",
      "parent": "/_app/_doctor"
    }
  }
}
ROUTE_MANIFEST_END */
