/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as AppImport } from './routes/_app'
import { Route as AppDoctorImport } from './routes/_app/_doctor'
import { Route as AppDashboardIndexImport } from './routes/_app/dashboard/index'
import { Route as AppPharmacyCartImport } from './routes/_app/pharmacy/cart'
import { Route as AppDashboardConsultationImport } from './routes/_app/dashboard/_consultation'
import { Route as AppAuthVerifyImport } from './routes/_app/auth/verify'
import { Route as AppAuthSignInImport } from './routes/_app/auth/sign-in'
import { Route as AppPharmacyProductIndexImport } from './routes/_app/pharmacy/product/index'
import { Route as AppDashboardWalletIndexImport } from './routes/_app/dashboard/wallet/index'
import { Route as AppDashboardScheduleIndexImport } from './routes/_app/dashboard/schedule/index'
import { Route as AppDashboardProfileIndexImport } from './routes/_app/dashboard/profile/index'
import { Route as AppDashboardDoctorsIndexImport } from './routes/_app/dashboard/doctors/index'
import { Route as AppAuthSignUpIndexImport } from './routes/_app/auth/sign-up/index'
import { Route as AppDoctorDoctorIndexImport } from './routes/_app/_doctor/doctor/index'
import { Route as AppConsultationConsultationsIndexImport } from './routes/_app/_consultation/consultations/index'
import { Route as AppDashboardConsultationJitsiconsultationImport } from './routes/_app/dashboard/_consultation/jitsiconsultation'
import { Route as AppDashboardConsultationClientconsultationImport } from './routes/_app/dashboard/_consultation/clientconsultation'
import { Route as AppPharmacyProductIdIndexImport } from './routes/_app/pharmacy/product/$id/index'
import { Route as AppDashboardChatsDoctorIdIndexImport } from './routes/_app/dashboard/chats/$doctorId/index'
import { Route as AppDoctorDoctorSupportIndexImport } from './routes/_app/_doctor/doctor/support/index'
import { Route as AppDoctorDoctorPatientsIndexImport } from './routes/_app/_doctor/doctor/patients/index'
import { Route as AppDoctorDoctorMessageIndexImport } from './routes/_app/_doctor/doctor/message/index'
import { Route as AppDoctorDoctorLabIndexImport } from './routes/_app/_doctor/doctor/lab/index'
import { Route as AppDoctorDoctorAppointmentsIndexImport } from './routes/_app/_doctor/doctor/appointments/index'
import { Route as AppDashboardDoctorsProfileDoctorIdIndexImport } from './routes/_app/dashboard/doctors/profile/$doctorId/index'
import { Route as AppDoctorDoctorMessagePatientIdIndexImport } from './routes/_app/_doctor/doctor/message/$patientId/index'

// Create Virtual Routes

const AppDashboardImport = createFileRoute('/_app/dashboard')()

// Create/Update Routes

const AppRoute = AppImport.update({
  id: '/_app',
  getParentRoute: () => rootRoute,
} as any)

const AppDashboardRoute = AppDashboardImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)

const AppDoctorRoute = AppDoctorImport.update({
  id: '/_doctor',
  getParentRoute: () => AppRoute,
} as any)

const AppDashboardIndexRoute = AppDashboardIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppDashboardRoute,
} as any)

const AppPharmacyCartRoute = AppPharmacyCartImport.update({
  id: '/pharmacy/cart',
  path: '/pharmacy/cart',
  getParentRoute: () => AppRoute,
} as any)

const AppDashboardConsultationRoute = AppDashboardConsultationImport.update({
  id: '/_consultation',
  getParentRoute: () => AppDashboardRoute,
} as any)

const AppAuthVerifyRoute = AppAuthVerifyImport.update({
  id: '/auth/verify',
  path: '/auth/verify',
  getParentRoute: () => AppRoute,
} as any)

const AppAuthSignInRoute = AppAuthSignInImport.update({
  id: '/auth/sign-in',
  path: '/auth/sign-in',
  getParentRoute: () => AppRoute,
} as any)

const AppPharmacyProductIndexRoute = AppPharmacyProductIndexImport.update({
  id: '/pharmacy/product/',
  path: '/pharmacy/product/',
  getParentRoute: () => AppRoute,
} as any)

const AppDashboardWalletIndexRoute = AppDashboardWalletIndexImport.update({
  id: '/wallet/',
  path: '/wallet/',
  getParentRoute: () => AppDashboardRoute,
} as any)

const AppDashboardScheduleIndexRoute = AppDashboardScheduleIndexImport.update({
  id: '/schedule/',
  path: '/schedule/',
  getParentRoute: () => AppDashboardRoute,
} as any)

const AppDashboardProfileIndexRoute = AppDashboardProfileIndexImport.update({
  id: '/profile/',
  path: '/profile/',
  getParentRoute: () => AppDashboardRoute,
} as any)

const AppDashboardDoctorsIndexRoute = AppDashboardDoctorsIndexImport.update({
  id: '/doctors/',
  path: '/doctors/',
  getParentRoute: () => AppDashboardRoute,
} as any)

const AppAuthSignUpIndexRoute = AppAuthSignUpIndexImport.update({
  id: '/auth/sign-up/',
  path: '/auth/sign-up/',
  getParentRoute: () => AppRoute,
} as any)

const AppDoctorDoctorIndexRoute = AppDoctorDoctorIndexImport.update({
  id: '/doctor/',
  path: '/doctor/',
  getParentRoute: () => AppDoctorRoute,
} as any)

const AppConsultationConsultationsIndexRoute =
  AppConsultationConsultationsIndexImport.update({
    id: '/_consultation/consultations/',
    path: '/consultations/',
    getParentRoute: () => AppRoute,
  } as any)

const AppDashboardConsultationJitsiconsultationRoute =
  AppDashboardConsultationJitsiconsultationImport.update({
    id: '/jitsiconsultation',
    path: '/jitsiconsultation',
    getParentRoute: () => AppDashboardConsultationRoute,
  } as any)

const AppDashboardConsultationClientconsultationRoute =
  AppDashboardConsultationClientconsultationImport.update({
    id: '/clientconsultation',
    path: '/clientconsultation',
    getParentRoute: () => AppDashboardConsultationRoute,
  } as any)

const AppPharmacyProductIdIndexRoute = AppPharmacyProductIdIndexImport.update({
  id: '/pharmacy/product/$id/',
  path: '/pharmacy/product/$id/',
  getParentRoute: () => AppRoute,
} as any)

const AppDashboardChatsDoctorIdIndexRoute =
  AppDashboardChatsDoctorIdIndexImport.update({
    id: '/chats/$doctorId/',
    path: '/chats/$doctorId/',
    getParentRoute: () => AppDashboardRoute,
  } as any)

const AppDoctorDoctorSupportIndexRoute =
  AppDoctorDoctorSupportIndexImport.update({
    id: '/doctor/support/',
    path: '/doctor/support/',
    getParentRoute: () => AppDoctorRoute,
  } as any)

const AppDoctorDoctorPatientsIndexRoute =
  AppDoctorDoctorPatientsIndexImport.update({
    id: '/doctor/patients/',
    path: '/doctor/patients/',
    getParentRoute: () => AppDoctorRoute,
  } as any)

const AppDoctorDoctorMessageIndexRoute =
  AppDoctorDoctorMessageIndexImport.update({
    id: '/doctor/message/',
    path: '/doctor/message/',
    getParentRoute: () => AppDoctorRoute,
  } as any)

const AppDoctorDoctorLabIndexRoute = AppDoctorDoctorLabIndexImport.update({
  id: '/doctor/lab/',
  path: '/doctor/lab/',
  getParentRoute: () => AppDoctorRoute,
} as any)

const AppDoctorDoctorAppointmentsIndexRoute =
  AppDoctorDoctorAppointmentsIndexImport.update({
    id: '/doctor/appointments/',
    path: '/doctor/appointments/',
    getParentRoute: () => AppDoctorRoute,
  } as any)

const AppDashboardDoctorsProfileDoctorIdIndexRoute =
  AppDashboardDoctorsProfileDoctorIdIndexImport.update({
    id: '/doctors/profile/$doctorId/',
    path: '/doctors/profile/$doctorId/',
    getParentRoute: () => AppDashboardRoute,
  } as any)

const AppDoctorDoctorMessagePatientIdIndexRoute =
  AppDoctorDoctorMessagePatientIdIndexImport.update({
    id: '/doctor/message/$patientId/',
    path: '/doctor/message/$patientId/',
    getParentRoute: () => AppDoctorRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AppImport
      parentRoute: typeof rootRoute
    }
    '/_app/_doctor': {
      id: '/_app/_doctor'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AppDoctorImport
      parentRoute: typeof AppImport
    }
    '/_app/auth/sign-in': {
      id: '/_app/auth/sign-in'
      path: '/auth/sign-in'
      fullPath: '/auth/sign-in'
      preLoaderRoute: typeof AppAuthSignInImport
      parentRoute: typeof AppImport
    }
    '/_app/auth/verify': {
      id: '/_app/auth/verify'
      path: '/auth/verify'
      fullPath: '/auth/verify'
      preLoaderRoute: typeof AppAuthVerifyImport
      parentRoute: typeof AppImport
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardImport
      parentRoute: typeof AppImport
    }
    '/_app/dashboard/_consultation': {
      id: '/_app/dashboard/_consultation'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardConsultationImport
      parentRoute: typeof AppDashboardRoute
    }
    '/_app/pharmacy/cart': {
      id: '/_app/pharmacy/cart'
      path: '/pharmacy/cart'
      fullPath: '/pharmacy/cart'
      preLoaderRoute: typeof AppPharmacyCartImport
      parentRoute: typeof AppImport
    }
    '/_app/dashboard/': {
      id: '/_app/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof AppDashboardIndexImport
      parentRoute: typeof AppDashboardImport
    }
    '/_app/dashboard/_consultation/clientconsultation': {
      id: '/_app/dashboard/_consultation/clientconsultation'
      path: '/clientconsultation'
      fullPath: '/dashboard/clientconsultation'
      preLoaderRoute: typeof AppDashboardConsultationClientconsultationImport
      parentRoute: typeof AppDashboardConsultationImport
    }
    '/_app/dashboard/_consultation/jitsiconsultation': {
      id: '/_app/dashboard/_consultation/jitsiconsultation'
      path: '/jitsiconsultation'
      fullPath: '/dashboard/jitsiconsultation'
      preLoaderRoute: typeof AppDashboardConsultationJitsiconsultationImport
      parentRoute: typeof AppDashboardConsultationImport
    }
    '/_app/_consultation/consultations/': {
      id: '/_app/_consultation/consultations/'
      path: '/consultations'
      fullPath: '/consultations'
      preLoaderRoute: typeof AppConsultationConsultationsIndexImport
      parentRoute: typeof AppImport
    }
    '/_app/_doctor/doctor/': {
      id: '/_app/_doctor/doctor/'
      path: '/doctor'
      fullPath: '/doctor'
      preLoaderRoute: typeof AppDoctorDoctorIndexImport
      parentRoute: typeof AppDoctorImport
    }
    '/_app/auth/sign-up/': {
      id: '/_app/auth/sign-up/'
      path: '/auth/sign-up'
      fullPath: '/auth/sign-up'
      preLoaderRoute: typeof AppAuthSignUpIndexImport
      parentRoute: typeof AppImport
    }
    '/_app/dashboard/doctors/': {
      id: '/_app/dashboard/doctors/'
      path: '/doctors'
      fullPath: '/dashboard/doctors'
      preLoaderRoute: typeof AppDashboardDoctorsIndexImport
      parentRoute: typeof AppDashboardImport
    }
    '/_app/dashboard/profile/': {
      id: '/_app/dashboard/profile/'
      path: '/profile'
      fullPath: '/dashboard/profile'
      preLoaderRoute: typeof AppDashboardProfileIndexImport
      parentRoute: typeof AppDashboardImport
    }
    '/_app/dashboard/schedule/': {
      id: '/_app/dashboard/schedule/'
      path: '/schedule'
      fullPath: '/dashboard/schedule'
      preLoaderRoute: typeof AppDashboardScheduleIndexImport
      parentRoute: typeof AppDashboardImport
    }
    '/_app/dashboard/wallet/': {
      id: '/_app/dashboard/wallet/'
      path: '/wallet'
      fullPath: '/dashboard/wallet'
      preLoaderRoute: typeof AppDashboardWalletIndexImport
      parentRoute: typeof AppDashboardImport
    }
    '/_app/pharmacy/product/': {
      id: '/_app/pharmacy/product/'
      path: '/pharmacy/product'
      fullPath: '/pharmacy/product'
      preLoaderRoute: typeof AppPharmacyProductIndexImport
      parentRoute: typeof AppImport
    }
    '/_app/_doctor/doctor/appointments/': {
      id: '/_app/_doctor/doctor/appointments/'
      path: '/doctor/appointments'
      fullPath: '/doctor/appointments'
      preLoaderRoute: typeof AppDoctorDoctorAppointmentsIndexImport
      parentRoute: typeof AppDoctorImport
    }
    '/_app/_doctor/doctor/lab/': {
      id: '/_app/_doctor/doctor/lab/'
      path: '/doctor/lab'
      fullPath: '/doctor/lab'
      preLoaderRoute: typeof AppDoctorDoctorLabIndexImport
      parentRoute: typeof AppDoctorImport
    }
    '/_app/_doctor/doctor/message/': {
      id: '/_app/_doctor/doctor/message/'
      path: '/doctor/message'
      fullPath: '/doctor/message'
      preLoaderRoute: typeof AppDoctorDoctorMessageIndexImport
      parentRoute: typeof AppDoctorImport
    }
    '/_app/_doctor/doctor/patients/': {
      id: '/_app/_doctor/doctor/patients/'
      path: '/doctor/patients'
      fullPath: '/doctor/patients'
      preLoaderRoute: typeof AppDoctorDoctorPatientsIndexImport
      parentRoute: typeof AppDoctorImport
    }
    '/_app/_doctor/doctor/support/': {
      id: '/_app/_doctor/doctor/support/'
      path: '/doctor/support'
      fullPath: '/doctor/support'
      preLoaderRoute: typeof AppDoctorDoctorSupportIndexImport
      parentRoute: typeof AppDoctorImport
    }
    '/_app/dashboard/chats/$doctorId/': {
      id: '/_app/dashboard/chats/$doctorId/'
      path: '/chats/$doctorId'
      fullPath: '/dashboard/chats/$doctorId'
      preLoaderRoute: typeof AppDashboardChatsDoctorIdIndexImport
      parentRoute: typeof AppDashboardImport
    }
    '/_app/pharmacy/product/$id/': {
      id: '/_app/pharmacy/product/$id/'
      path: '/pharmacy/product/$id'
      fullPath: '/pharmacy/product/$id'
      preLoaderRoute: typeof AppPharmacyProductIdIndexImport
      parentRoute: typeof AppImport
    }
    '/_app/_doctor/doctor/message/$patientId/': {
      id: '/_app/_doctor/doctor/message/$patientId/'
      path: '/doctor/message/$patientId'
      fullPath: '/doctor/message/$patientId'
      preLoaderRoute: typeof AppDoctorDoctorMessagePatientIdIndexImport
      parentRoute: typeof AppDoctorImport
    }
    '/_app/dashboard/doctors/profile/$doctorId/': {
      id: '/_app/dashboard/doctors/profile/$doctorId/'
      path: '/doctors/profile/$doctorId'
      fullPath: '/dashboard/doctors/profile/$doctorId'
      preLoaderRoute: typeof AppDashboardDoctorsProfileDoctorIdIndexImport
      parentRoute: typeof AppDashboardImport
    }
  }
}

// Create and export the route tree

interface AppDoctorRouteChildren {
  AppDoctorDoctorIndexRoute: typeof AppDoctorDoctorIndexRoute
  AppDoctorDoctorAppointmentsIndexRoute: typeof AppDoctorDoctorAppointmentsIndexRoute
  AppDoctorDoctorLabIndexRoute: typeof AppDoctorDoctorLabIndexRoute
  AppDoctorDoctorMessageIndexRoute: typeof AppDoctorDoctorMessageIndexRoute
  AppDoctorDoctorPatientsIndexRoute: typeof AppDoctorDoctorPatientsIndexRoute
  AppDoctorDoctorSupportIndexRoute: typeof AppDoctorDoctorSupportIndexRoute
  AppDoctorDoctorMessagePatientIdIndexRoute: typeof AppDoctorDoctorMessagePatientIdIndexRoute
}

const AppDoctorRouteChildren: AppDoctorRouteChildren = {
  AppDoctorDoctorIndexRoute: AppDoctorDoctorIndexRoute,
  AppDoctorDoctorAppointmentsIndexRoute: AppDoctorDoctorAppointmentsIndexRoute,
  AppDoctorDoctorLabIndexRoute: AppDoctorDoctorLabIndexRoute,
  AppDoctorDoctorMessageIndexRoute: AppDoctorDoctorMessageIndexRoute,
  AppDoctorDoctorPatientsIndexRoute: AppDoctorDoctorPatientsIndexRoute,
  AppDoctorDoctorSupportIndexRoute: AppDoctorDoctorSupportIndexRoute,
  AppDoctorDoctorMessagePatientIdIndexRoute:
    AppDoctorDoctorMessagePatientIdIndexRoute,
}

const AppDoctorRouteWithChildren = AppDoctorRoute._addFileChildren(
  AppDoctorRouteChildren,
)

interface AppDashboardConsultationRouteChildren {
  AppDashboardConsultationClientconsultationRoute: typeof AppDashboardConsultationClientconsultationRoute
  AppDashboardConsultationJitsiconsultationRoute: typeof AppDashboardConsultationJitsiconsultationRoute
}

const AppDashboardConsultationRouteChildren: AppDashboardConsultationRouteChildren =
  {
    AppDashboardConsultationClientconsultationRoute:
      AppDashboardConsultationClientconsultationRoute,
    AppDashboardConsultationJitsiconsultationRoute:
      AppDashboardConsultationJitsiconsultationRoute,
  }

const AppDashboardConsultationRouteWithChildren =
  AppDashboardConsultationRoute._addFileChildren(
    AppDashboardConsultationRouteChildren,
  )

interface AppDashboardRouteChildren {
  AppDashboardConsultationRoute: typeof AppDashboardConsultationRouteWithChildren
  AppDashboardIndexRoute: typeof AppDashboardIndexRoute
  AppDashboardDoctorsIndexRoute: typeof AppDashboardDoctorsIndexRoute
  AppDashboardProfileIndexRoute: typeof AppDashboardProfileIndexRoute
  AppDashboardScheduleIndexRoute: typeof AppDashboardScheduleIndexRoute
  AppDashboardWalletIndexRoute: typeof AppDashboardWalletIndexRoute
  AppDashboardChatsDoctorIdIndexRoute: typeof AppDashboardChatsDoctorIdIndexRoute
  AppDashboardDoctorsProfileDoctorIdIndexRoute: typeof AppDashboardDoctorsProfileDoctorIdIndexRoute
}

const AppDashboardRouteChildren: AppDashboardRouteChildren = {
  AppDashboardConsultationRoute: AppDashboardConsultationRouteWithChildren,
  AppDashboardIndexRoute: AppDashboardIndexRoute,
  AppDashboardDoctorsIndexRoute: AppDashboardDoctorsIndexRoute,
  AppDashboardProfileIndexRoute: AppDashboardProfileIndexRoute,
  AppDashboardScheduleIndexRoute: AppDashboardScheduleIndexRoute,
  AppDashboardWalletIndexRoute: AppDashboardWalletIndexRoute,
  AppDashboardChatsDoctorIdIndexRoute: AppDashboardChatsDoctorIdIndexRoute,
  AppDashboardDoctorsProfileDoctorIdIndexRoute:
    AppDashboardDoctorsProfileDoctorIdIndexRoute,
}

const AppDashboardRouteWithChildren = AppDashboardRoute._addFileChildren(
  AppDashboardRouteChildren,
)

interface AppRouteChildren {
  AppDoctorRoute: typeof AppDoctorRouteWithChildren
  AppAuthSignInRoute: typeof AppAuthSignInRoute
  AppAuthVerifyRoute: typeof AppAuthVerifyRoute
  AppDashboardRoute: typeof AppDashboardRouteWithChildren
  AppPharmacyCartRoute: typeof AppPharmacyCartRoute
  AppConsultationConsultationsIndexRoute: typeof AppConsultationConsultationsIndexRoute
  AppAuthSignUpIndexRoute: typeof AppAuthSignUpIndexRoute
  AppPharmacyProductIndexRoute: typeof AppPharmacyProductIndexRoute
  AppPharmacyProductIdIndexRoute: typeof AppPharmacyProductIdIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppDoctorRoute: AppDoctorRouteWithChildren,
  AppAuthSignInRoute: AppAuthSignInRoute,
  AppAuthVerifyRoute: AppAuthVerifyRoute,
  AppDashboardRoute: AppDashboardRouteWithChildren,
  AppPharmacyCartRoute: AppPharmacyCartRoute,
  AppConsultationConsultationsIndexRoute:
    AppConsultationConsultationsIndexRoute,
  AppAuthSignUpIndexRoute: AppAuthSignUpIndexRoute,
  AppPharmacyProductIndexRoute: AppPharmacyProductIndexRoute,
  AppPharmacyProductIdIndexRoute: AppPharmacyProductIdIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

export interface FileRoutesByFullPath {
  '': typeof AppDoctorRouteWithChildren
  '/auth/sign-in': typeof AppAuthSignInRoute
  '/auth/verify': typeof AppAuthVerifyRoute
  '/dashboard': typeof AppDashboardConsultationRouteWithChildren
  '/pharmacy/cart': typeof AppPharmacyCartRoute
  '/dashboard/': typeof AppDashboardIndexRoute
  '/dashboard/clientconsultation': typeof AppDashboardConsultationClientconsultationRoute
  '/dashboard/jitsiconsultation': typeof AppDashboardConsultationJitsiconsultationRoute
  '/consultations': typeof AppConsultationConsultationsIndexRoute
  '/doctor': typeof AppDoctorDoctorIndexRoute
  '/auth/sign-up': typeof AppAuthSignUpIndexRoute
  '/dashboard/doctors': typeof AppDashboardDoctorsIndexRoute
  '/dashboard/profile': typeof AppDashboardProfileIndexRoute
  '/dashboard/schedule': typeof AppDashboardScheduleIndexRoute
  '/dashboard/wallet': typeof AppDashboardWalletIndexRoute
  '/pharmacy/product': typeof AppPharmacyProductIndexRoute
  '/doctor/appointments': typeof AppDoctorDoctorAppointmentsIndexRoute
  '/doctor/lab': typeof AppDoctorDoctorLabIndexRoute
  '/doctor/message': typeof AppDoctorDoctorMessageIndexRoute
  '/doctor/patients': typeof AppDoctorDoctorPatientsIndexRoute
  '/doctor/support': typeof AppDoctorDoctorSupportIndexRoute
  '/dashboard/chats/$doctorId': typeof AppDashboardChatsDoctorIdIndexRoute
  '/pharmacy/product/$id': typeof AppPharmacyProductIdIndexRoute
  '/doctor/message/$patientId': typeof AppDoctorDoctorMessagePatientIdIndexRoute
  '/dashboard/doctors/profile/$doctorId': typeof AppDashboardDoctorsProfileDoctorIdIndexRoute
}

export interface FileRoutesByTo {
  '': typeof AppDoctorRouteWithChildren
  '/auth/sign-in': typeof AppAuthSignInRoute
  '/auth/verify': typeof AppAuthVerifyRoute
  '/dashboard': typeof AppDashboardIndexRoute
  '/pharmacy/cart': typeof AppPharmacyCartRoute
  '/dashboard/clientconsultation': typeof AppDashboardConsultationClientconsultationRoute
  '/dashboard/jitsiconsultation': typeof AppDashboardConsultationJitsiconsultationRoute
  '/consultations': typeof AppConsultationConsultationsIndexRoute
  '/doctor': typeof AppDoctorDoctorIndexRoute
  '/auth/sign-up': typeof AppAuthSignUpIndexRoute
  '/dashboard/doctors': typeof AppDashboardDoctorsIndexRoute
  '/dashboard/profile': typeof AppDashboardProfileIndexRoute
  '/dashboard/schedule': typeof AppDashboardScheduleIndexRoute
  '/dashboard/wallet': typeof AppDashboardWalletIndexRoute
  '/pharmacy/product': typeof AppPharmacyProductIndexRoute
  '/doctor/appointments': typeof AppDoctorDoctorAppointmentsIndexRoute
  '/doctor/lab': typeof AppDoctorDoctorLabIndexRoute
  '/doctor/message': typeof AppDoctorDoctorMessageIndexRoute
  '/doctor/patients': typeof AppDoctorDoctorPatientsIndexRoute
  '/doctor/support': typeof AppDoctorDoctorSupportIndexRoute
  '/dashboard/chats/$doctorId': typeof AppDashboardChatsDoctorIdIndexRoute
  '/pharmacy/product/$id': typeof AppPharmacyProductIdIndexRoute
  '/doctor/message/$patientId': typeof AppDoctorDoctorMessagePatientIdIndexRoute
  '/dashboard/doctors/profile/$doctorId': typeof AppDashboardDoctorsProfileDoctorIdIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/_app': typeof AppRouteWithChildren
  '/_app/_doctor': typeof AppDoctorRouteWithChildren
  '/_app/auth/sign-in': typeof AppAuthSignInRoute
  '/_app/auth/verify': typeof AppAuthVerifyRoute
  '/_app/dashboard': typeof AppDashboardRouteWithChildren
  '/_app/dashboard/_consultation': typeof AppDashboardConsultationRouteWithChildren
  '/_app/pharmacy/cart': typeof AppPharmacyCartRoute
  '/_app/dashboard/': typeof AppDashboardIndexRoute
  '/_app/dashboard/_consultation/clientconsultation': typeof AppDashboardConsultationClientconsultationRoute
  '/_app/dashboard/_consultation/jitsiconsultation': typeof AppDashboardConsultationJitsiconsultationRoute
  '/_app/_consultation/consultations/': typeof AppConsultationConsultationsIndexRoute
  '/_app/_doctor/doctor/': typeof AppDoctorDoctorIndexRoute
  '/_app/auth/sign-up/': typeof AppAuthSignUpIndexRoute
  '/_app/dashboard/doctors/': typeof AppDashboardDoctorsIndexRoute
  '/_app/dashboard/profile/': typeof AppDashboardProfileIndexRoute
  '/_app/dashboard/schedule/': typeof AppDashboardScheduleIndexRoute
  '/_app/dashboard/wallet/': typeof AppDashboardWalletIndexRoute
  '/_app/pharmacy/product/': typeof AppPharmacyProductIndexRoute
  '/_app/_doctor/doctor/appointments/': typeof AppDoctorDoctorAppointmentsIndexRoute
  '/_app/_doctor/doctor/lab/': typeof AppDoctorDoctorLabIndexRoute
  '/_app/_doctor/doctor/message/': typeof AppDoctorDoctorMessageIndexRoute
  '/_app/_doctor/doctor/patients/': typeof AppDoctorDoctorPatientsIndexRoute
  '/_app/_doctor/doctor/support/': typeof AppDoctorDoctorSupportIndexRoute
  '/_app/dashboard/chats/$doctorId/': typeof AppDashboardChatsDoctorIdIndexRoute
  '/_app/pharmacy/product/$id/': typeof AppPharmacyProductIdIndexRoute
  '/_app/_doctor/doctor/message/$patientId/': typeof AppDoctorDoctorMessagePatientIdIndexRoute
  '/_app/dashboard/doctors/profile/$doctorId/': typeof AppDashboardDoctorsProfileDoctorIdIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | ''
    | '/auth/sign-in'
    | '/auth/verify'
    | '/dashboard'
    | '/pharmacy/cart'
    | '/dashboard/'
    | '/dashboard/clientconsultation'
    | '/dashboard/jitsiconsultation'
    | '/consultations'
    | '/doctor'
    | '/auth/sign-up'
    | '/dashboard/doctors'
    | '/dashboard/profile'
    | '/dashboard/schedule'
    | '/dashboard/wallet'
    | '/pharmacy/product'
    | '/doctor/appointments'
    | '/doctor/lab'
    | '/doctor/message'
    | '/doctor/patients'
    | '/doctor/support'
    | '/dashboard/chats/$doctorId'
    | '/pharmacy/product/$id'
    | '/doctor/message/$patientId'
    | '/dashboard/doctors/profile/$doctorId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | ''
    | '/auth/sign-in'
    | '/auth/verify'
    | '/dashboard'
    | '/pharmacy/cart'
    | '/dashboard/clientconsultation'
    | '/dashboard/jitsiconsultation'
    | '/consultations'
    | '/doctor'
    | '/auth/sign-up'
    | '/dashboard/doctors'
    | '/dashboard/profile'
    | '/dashboard/schedule'
    | '/dashboard/wallet'
    | '/pharmacy/product'
    | '/doctor/appointments'
    | '/doctor/lab'
    | '/doctor/message'
    | '/doctor/patients'
    | '/doctor/support'
    | '/dashboard/chats/$doctorId'
    | '/pharmacy/product/$id'
    | '/doctor/message/$patientId'
    | '/dashboard/doctors/profile/$doctorId'
  id:
    | '__root__'
    | '/_app'
    | '/_app/_doctor'
    | '/_app/auth/sign-in'
    | '/_app/auth/verify'
    | '/_app/dashboard'
    | '/_app/dashboard/_consultation'
    | '/_app/pharmacy/cart'
    | '/_app/dashboard/'
    | '/_app/dashboard/_consultation/clientconsultation'
    | '/_app/dashboard/_consultation/jitsiconsultation'
    | '/_app/_consultation/consultations/'
    | '/_app/_doctor/doctor/'
    | '/_app/auth/sign-up/'
    | '/_app/dashboard/doctors/'
    | '/_app/dashboard/profile/'
    | '/_app/dashboard/schedule/'
    | '/_app/dashboard/wallet/'
    | '/_app/pharmacy/product/'
    | '/_app/_doctor/doctor/appointments/'
    | '/_app/_doctor/doctor/lab/'
    | '/_app/_doctor/doctor/message/'
    | '/_app/_doctor/doctor/patients/'
    | '/_app/_doctor/doctor/support/'
    | '/_app/dashboard/chats/$doctorId/'
    | '/_app/pharmacy/product/$id/'
    | '/_app/_doctor/doctor/message/$patientId/'
    | '/_app/dashboard/doctors/profile/$doctorId/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
}

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/_app"
      ]
    },
    "/_app": {
      "filePath": "_app.tsx",
      "children": [
        "/_app/_doctor",
        "/_app/auth/sign-in",
        "/_app/auth/verify",
        "/_app/dashboard",
        "/_app/pharmacy/cart",
        "/_app/_consultation/consultations/",
        "/_app/auth/sign-up/",
        "/_app/pharmacy/product/",
        "/_app/pharmacy/product/$id/"
      ]
    },
    "/_app/_doctor": {
      "filePath": "_app/_doctor.tsx",
      "parent": "/_app",
      "children": [
        "/_app/_doctor/doctor/",
        "/_app/_doctor/doctor/appointments/",
        "/_app/_doctor/doctor/lab/",
        "/_app/_doctor/doctor/message/",
        "/_app/_doctor/doctor/patients/",
        "/_app/_doctor/doctor/support/",
        "/_app/_doctor/doctor/message/$patientId/"
      ]
    },
    "/_app/auth/sign-in": {
      "filePath": "_app/auth/sign-in.tsx",
      "parent": "/_app"
    },
    "/_app/auth/verify": {
      "filePath": "_app/auth/verify.tsx",
      "parent": "/_app"
    },
    "/_app/dashboard": {
      "filePath": "_app/dashboard",
      "parent": "/_app",
      "children": [
        "/_app/dashboard/_consultation",
        "/_app/dashboard/",
        "/_app/dashboard/doctors/",
        "/_app/dashboard/profile/",
        "/_app/dashboard/schedule/",
        "/_app/dashboard/wallet/",
        "/_app/dashboard/chats/$doctorId/",
        "/_app/dashboard/doctors/profile/$doctorId/"
      ]
    },
    "/_app/dashboard/_consultation": {
      "filePath": "_app/dashboard/_consultation.tsx",
      "parent": "/_app/dashboard",
      "children": [
        "/_app/dashboard/_consultation/clientconsultation",
        "/_app/dashboard/_consultation/jitsiconsultation"
      ]
    },
    "/_app/pharmacy/cart": {
      "filePath": "_app/pharmacy/cart.tsx",
      "parent": "/_app"
    },
    "/_app/dashboard/": {
      "filePath": "_app/dashboard/index.tsx",
      "parent": "/_app/dashboard"
    },
    "/_app/dashboard/_consultation/clientconsultation": {
      "filePath": "_app/dashboard/_consultation/clientconsultation.tsx",
      "parent": "/_app/dashboard/_consultation"
    },
    "/_app/dashboard/_consultation/jitsiconsultation": {
      "filePath": "_app/dashboard/_consultation/jitsiconsultation.tsx",
      "parent": "/_app/dashboard/_consultation"
    },
    "/_app/_consultation/consultations/": {
      "filePath": "_app/_consultation/consultations/index.tsx",
      "parent": "/_app"
    },
    "/_app/_doctor/doctor/": {
      "filePath": "_app/_doctor/doctor/index.tsx",
      "parent": "/_app/_doctor"
    },
    "/_app/auth/sign-up/": {
      "filePath": "_app/auth/sign-up/index.tsx",
      "parent": "/_app"
    },
    "/_app/dashboard/doctors/": {
      "filePath": "_app/dashboard/doctors/index.tsx",
      "parent": "/_app/dashboard"
    },
    "/_app/dashboard/profile/": {
      "filePath": "_app/dashboard/profile/index.tsx",
      "parent": "/_app/dashboard"
    },
    "/_app/dashboard/schedule/": {
      "filePath": "_app/dashboard/schedule/index.tsx",
      "parent": "/_app/dashboard"
    },
    "/_app/dashboard/wallet/": {
      "filePath": "_app/dashboard/wallet/index.tsx",
      "parent": "/_app/dashboard"
    },
    "/_app/pharmacy/product/": {
      "filePath": "_app/pharmacy/product/index.tsx",
      "parent": "/_app"
    },
    "/_app/_doctor/doctor/appointments/": {
      "filePath": "_app/_doctor/doctor/appointments/index.tsx",
      "parent": "/_app/_doctor"
    },
    "/_app/_doctor/doctor/lab/": {
      "filePath": "_app/_doctor/doctor/lab/index.tsx",
      "parent": "/_app/_doctor"
    },
    "/_app/_doctor/doctor/message/": {
      "filePath": "_app/_doctor/doctor/message/index.tsx",
      "parent": "/_app/_doctor"
    },
    "/_app/_doctor/doctor/patients/": {
      "filePath": "_app/_doctor/doctor/patients/index.tsx",
      "parent": "/_app/_doctor"
    },
    "/_app/_doctor/doctor/support/": {
      "filePath": "_app/_doctor/doctor/support/index.tsx",
      "parent": "/_app/_doctor"
    },
    "/_app/dashboard/chats/$doctorId/": {
      "filePath": "_app/dashboard/chats/$doctorId/index.tsx",
      "parent": "/_app/dashboard"
    },
    "/_app/pharmacy/product/$id/": {
      "filePath": "_app/pharmacy/product/$id/index.tsx",
      "parent": "/_app"
    },
    "/_app/_doctor/doctor/message/$patientId/": {
      "filePath": "_app/_doctor/doctor/message/$patientId/index.tsx",
      "parent": "/_app/_doctor"
    },
    "/_app/dashboard/doctors/profile/$doctorId/": {
      "filePath": "_app/dashboard/doctors/profile/$doctorId/index.tsx",
      "parent": "/_app/dashboard"
    }
  }
}
ROUTE_MANIFEST_END */
