# Generated by Django 5.1.3 on 2025-02-26 04:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultation', '0002_consultation_request_end_time_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultation_request',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_consultation_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='consultation_request',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_consultation_requests', to=settings.AUTH_USER_MODEL),
        ),
    ]
