# Generated by Django 5.1.3 on 2025-02-26 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultation', '0003_alter_consultation_request_doctor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultations',
            name='video_room_id',
            field=models.TextField(blank=True, null=True),
        ),
    ]
