# Generated by Django 5.1.3 on 2025-02-26 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultation', '0004_consultations_video_room_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultations',
            name='video_room_token',
            field=models.TextField(blank=True, null=True),
        ),
    ]
