# Generated by Django 5.1.3 on 2025-02-26 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consultation', '0005_consultations_video_room_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consultations',
            name='video_room_token',
        ),
    ]
