# Generated by Django 5.1.3 on 2025-03-22 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultation', '0006_remove_consultations_video_room_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consultations',
            name='video_room_id',
        ),
        migrations.AddField(
            model_name='consultations',
            name='doctor_token',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='consultations',
            name='patient_token',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='consultations',
            name='room_name',
            field=models.TextField(blank=True, null=True),
        ),
    ]
