/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppPharmacyIndexRouteImport } from './routes/_app/pharmacy/index'
import { Route as AppHowToUseIndexRouteImport } from './routes/_app/how-to-use/index'
import { Route as AppContactUsIndexRouteImport } from './routes/_app/contact-us/index'
import { Route as AppChatSupportIndexRouteImport } from './routes/_app/chat-support/index'
import { Route as AppCareServicesIndexRouteImport } from './routes/_app/care-services/index'
import { Route as AppAboutUsIndexRouteImport } from './routes/_app/about-us/index'
import { Route as AppExtrasVirtualConsultationsRouteImport } from './routes/_app/_extras/virtual-consultations'
import { Route as AppExtrasSpecialtiesRouteImport } from './routes/_app/_extras/specialties'
import { Route as AppExtrasSignupRouteImport } from './routes/_app/_extras/signup'
import { Route as AppExtrasGetTheAppRouteImport } from './routes/_app/_extras/get-the-app'

const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppPharmacyIndexRoute = AppPharmacyIndexRouteImport.update({
  id: '/_app/pharmacy/',
  path: '/pharmacy/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppHowToUseIndexRoute = AppHowToUseIndexRouteImport.update({
  id: '/_app/how-to-use/',
  path: '/how-to-use/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppContactUsIndexRoute = AppContactUsIndexRouteImport.update({
  id: '/_app/contact-us/',
  path: '/contact-us/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppChatSupportIndexRoute = AppChatSupportIndexRouteImport.update({
  id: '/_app/chat-support/',
  path: '/chat-support/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppCareServicesIndexRoute = AppCareServicesIndexRouteImport.update({
  id: '/_app/care-services/',
  path: '/care-services/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppAboutUsIndexRoute = AppAboutUsIndexRouteImport.update({
  id: '/_app/about-us/',
  path: '/about-us/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppExtrasVirtualConsultationsRoute =
  AppExtrasVirtualConsultationsRouteImport.update({
    id: '/_app/_extras/virtual-consultations',
    path: '/virtual-consultations',
    getParentRoute: () => rootRouteImport,
  } as any)
const AppExtrasSpecialtiesRoute = AppExtrasSpecialtiesRouteImport.update({
  id: '/_app/_extras/specialties',
  path: '/specialties',
  getParentRoute: () => rootRouteImport,
} as any)
const AppExtrasSignupRoute = AppExtrasSignupRouteImport.update({
  id: '/_app/_extras/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const AppExtrasGetTheAppRoute = AppExtrasGetTheAppRouteImport.update({
  id: '/_app/_extras/get-the-app',
  path: '/get-the-app',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/get-the-app': typeof AppExtrasGetTheAppRoute
  '/signup': typeof AppExtrasSignupRoute
  '/specialties': typeof AppExtrasSpecialtiesRoute
  '/virtual-consultations': typeof AppExtrasVirtualConsultationsRoute
  '/about-us': typeof AppAboutUsIndexRoute
  '/care-services': typeof AppCareServicesIndexRoute
  '/chat-support': typeof AppChatSupportIndexRoute
  '/contact-us': typeof AppContactUsIndexRoute
  '/how-to-use': typeof AppHowToUseIndexRoute
  '/pharmacy': typeof AppPharmacyIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/get-the-app': typeof AppExtrasGetTheAppRoute
  '/signup': typeof AppExtrasSignupRoute
  '/specialties': typeof AppExtrasSpecialtiesRoute
  '/virtual-consultations': typeof AppExtrasVirtualConsultationsRoute
  '/about-us': typeof AppAboutUsIndexRoute
  '/care-services': typeof AppCareServicesIndexRoute
  '/chat-support': typeof AppChatSupportIndexRoute
  '/contact-us': typeof AppContactUsIndexRoute
  '/how-to-use': typeof AppHowToUseIndexRoute
  '/pharmacy': typeof AppPharmacyIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/_app/_extras/get-the-app': typeof AppExtrasGetTheAppRoute
  '/_app/_extras/signup': typeof AppExtrasSignupRoute
  '/_app/_extras/specialties': typeof AppExtrasSpecialtiesRoute
  '/_app/_extras/virtual-consultations': typeof AppExtrasVirtualConsultationsRoute
  '/_app/about-us/': typeof AppAboutUsIndexRoute
  '/_app/care-services/': typeof AppCareServicesIndexRoute
  '/_app/chat-support/': typeof AppChatSupportIndexRoute
  '/_app/contact-us/': typeof AppContactUsIndexRoute
  '/_app/how-to-use/': typeof AppHowToUseIndexRoute
  '/_app/pharmacy/': typeof AppPharmacyIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/get-the-app'
    | '/signup'
    | '/specialties'
    | '/virtual-consultations'
    | '/about-us'
    | '/care-services'
    | '/chat-support'
    | '/contact-us'
    | '/how-to-use'
    | '/pharmacy'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/get-the-app'
    | '/signup'
    | '/specialties'
    | '/virtual-consultations'
    | '/about-us'
    | '/care-services'
    | '/chat-support'
    | '/contact-us'
    | '/how-to-use'
    | '/pharmacy'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/_app/_extras/get-the-app'
    | '/_app/_extras/signup'
    | '/_app/_extras/specialties'
    | '/_app/_extras/virtual-consultations'
    | '/_app/about-us/'
    | '/_app/care-services/'
    | '/_app/chat-support/'
    | '/_app/contact-us/'
    | '/_app/how-to-use/'
    | '/_app/pharmacy/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AppExtrasGetTheAppRoute: typeof AppExtrasGetTheAppRoute
  AppExtrasSignupRoute: typeof AppExtrasSignupRoute
  AppExtrasSpecialtiesRoute: typeof AppExtrasSpecialtiesRoute
  AppExtrasVirtualConsultationsRoute: typeof AppExtrasVirtualConsultationsRoute
  AppAboutUsIndexRoute: typeof AppAboutUsIndexRoute
  AppCareServicesIndexRoute: typeof AppCareServicesIndexRoute
  AppChatSupportIndexRoute: typeof AppChatSupportIndexRoute
  AppContactUsIndexRoute: typeof AppContactUsIndexRoute
  AppHowToUseIndexRoute: typeof AppHowToUseIndexRoute
  AppPharmacyIndexRoute: typeof AppPharmacyIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/pharmacy/': {
      id: '/_app/pharmacy/'
      path: '/pharmacy'
      fullPath: '/pharmacy'
      preLoaderRoute: typeof AppPharmacyIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/how-to-use/': {
      id: '/_app/how-to-use/'
      path: '/how-to-use'
      fullPath: '/how-to-use'
      preLoaderRoute: typeof AppHowToUseIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/contact-us/': {
      id: '/_app/contact-us/'
      path: '/contact-us'
      fullPath: '/contact-us'
      preLoaderRoute: typeof AppContactUsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/chat-support/': {
      id: '/_app/chat-support/'
      path: '/chat-support'
      fullPath: '/chat-support'
      preLoaderRoute: typeof AppChatSupportIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/care-services/': {
      id: '/_app/care-services/'
      path: '/care-services'
      fullPath: '/care-services'
      preLoaderRoute: typeof AppCareServicesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/about-us/': {
      id: '/_app/about-us/'
      path: '/about-us'
      fullPath: '/about-us'
      preLoaderRoute: typeof AppAboutUsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/_extras/virtual-consultations': {
      id: '/_app/_extras/virtual-consultations'
      path: '/virtual-consultations'
      fullPath: '/virtual-consultations'
      preLoaderRoute: typeof AppExtrasVirtualConsultationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/_extras/specialties': {
      id: '/_app/_extras/specialties'
      path: '/specialties'
      fullPath: '/specialties'
      preLoaderRoute: typeof AppExtrasSpecialtiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/_extras/signup': {
      id: '/_app/_extras/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof AppExtrasSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/_extras/get-the-app': {
      id: '/_app/_extras/get-the-app'
      path: '/get-the-app'
      fullPath: '/get-the-app'
      preLoaderRoute: typeof AppExtrasGetTheAppRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AppExtrasGetTheAppRoute: AppExtrasGetTheAppRoute,
  AppExtrasSignupRoute: AppExtrasSignupRoute,
  AppExtrasSpecialtiesRoute: AppExtrasSpecialtiesRoute,
  AppExtrasVirtualConsultationsRoute: AppExtrasVirtualConsultationsRoute,
  AppAboutUsIndexRoute: AppAboutUsIndexRoute,
  AppCareServicesIndexRoute: AppCareServicesIndexRoute,
  AppChatSupportIndexRoute: AppChatSupportIndexRoute,
  AppContactUsIndexRoute: AppContactUsIndexRoute,
  AppHowToUseIndexRoute: AppHowToUseIndexRoute,
  AppPharmacyIndexRoute: AppPharmacyIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
