/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as PagesImport } from './routes/_pages'
import { Route as DoctorImport } from './routes/_doctor'
import { Route as AppImport } from './routes/_app'
import { Route as LoginIndexImport } from './routes/login/index'
import { Route as DashboardIndexImport } from './routes/dashboard/index'
import { Route as PagesPagesImport } from './routes/_pages/_pages'
import { Route as AppDoctorImport } from './routes/_app/_doctor'
import { Route as DashboardScheduleIndexImport } from './routes/dashboard/schedule/index'
import { Route as PagesPagesIndexImport } from './routes/_pages/_pages/index'
import { Route as DoctorDoctorIndexImport } from './routes/_doctor/doctor/index'
import { Route as AppLoginIndexImport } from './routes/_app/login/index'
import { Route as AppDashboardIndexImport } from './routes/_app/dashboard/index'
import { Route as DoctorDoctorPatientsIndexImport } from './routes/_doctor/doctor/patients/index'
import { Route as AppDashboardWalletIndexImport } from './routes/_app/dashboard/wallet/index'
import { Route as AppDashboardScheduleIndexImport } from './routes/_app/dashboard/schedule/index'
import { Route as AppDashboardProfileIndexImport } from './routes/_app/dashboard/profile/index'
import { Route as AppDashboardDoctorsIndexImport } from './routes/_app/dashboard/doctors/index'
import { Route as AppDoctorDoctorIndexImport } from './routes/_app/_doctor/doctor/index'
import { Route as AppConsultationConsultationsIndexImport } from './routes/_app/_consultation/consultations/index'
import { Route as DashboardDoctorsProfileDoctorIdIndexImport } from './routes/dashboard/doctors/profile/$doctorId/index'
import { Route as AppDashboardChatsDoctorIdIndexImport } from './routes/_app/dashboard/chats/$doctorId/index'
import { Route as AppDoctorDoctorSupportIndexImport } from './routes/_app/_doctor/doctor/support/index'
import { Route as AppDoctorDoctorPatientsIndexImport } from './routes/_app/_doctor/doctor/patients/index'
import { Route as AppDoctorDoctorMessageIndexImport } from './routes/_app/_doctor/doctor/message/index'
import { Route as AppDoctorDoctorLabIndexImport } from './routes/_app/_doctor/doctor/lab/index'
import { Route as AppDoctorDoctorAppointmentsIndexImport } from './routes/_app/_doctor/doctor/appointments/index'
import { Route as AppDashboardDoctorsProfileDoctorIdIndexImport } from './routes/_app/dashboard/doctors/profile/$doctorId/index'
import { Route as AppDoctorDoctorMessagePatientIdIndexImport } from './routes/_app/_doctor/doctor/message/$patientId/index'

// Create/Update Routes

const PagesRoute = PagesImport.update({
  id: '/_pages',
  getParentRoute: () => rootRoute,
} as any)

const DoctorRoute = DoctorImport.update({
  id: '/_doctor',
  getParentRoute: () => rootRoute,
} as any)

const AppRoute = AppImport.update({
  id: '/_app',
  getParentRoute: () => rootRoute,
} as any)

const LoginIndexRoute = LoginIndexImport.update({
  path: '/login/',
  getParentRoute: () => rootRoute,
} as any)

const DashboardIndexRoute = DashboardIndexImport.update({
  path: '/dashboard/',
  getParentRoute: () => rootRoute,
} as any)

const PagesPagesRoute = PagesPagesImport.update({
  id: '/_pages',
  getParentRoute: () => PagesRoute,
} as any)

const AppDoctorRoute = AppDoctorImport.update({
  id: '/_doctor',
  getParentRoute: () => AppRoute,
} as any)

const DashboardScheduleIndexRoute = DashboardScheduleIndexImport.update({
  path: '/dashboard/schedule/',
  getParentRoute: () => rootRoute,
} as any)

const PagesPagesIndexRoute = PagesPagesIndexImport.update({
  path: '/',
  getParentRoute: () => PagesPagesRoute,
} as any)

const DoctorDoctorIndexRoute = DoctorDoctorIndexImport.update({
  path: '/doctor/',
  getParentRoute: () => DoctorRoute,
} as any)

const AppLoginIndexRoute = AppLoginIndexImport.update({
  path: '/login/',
  getParentRoute: () => AppRoute,
} as any)

const AppDashboardIndexRoute = AppDashboardIndexImport.update({
  path: '/dashboard/',
  getParentRoute: () => AppRoute,
} as any)

const DoctorDoctorPatientsIndexRoute = DoctorDoctorPatientsIndexImport.update({
  path: '/doctor/patients/',
  getParentRoute: () => DoctorRoute,
} as any)

const AppDashboardWalletIndexRoute = AppDashboardWalletIndexImport.update({
  path: '/dashboard/wallet/',
  getParentRoute: () => AppRoute,
} as any)

const AppDashboardScheduleIndexRoute = AppDashboardScheduleIndexImport.update({
  path: '/dashboard/schedule/',
  getParentRoute: () => AppRoute,
} as any)

const AppDashboardProfileIndexRoute = AppDashboardProfileIndexImport.update({
  path: '/dashboard/profile/',
  getParentRoute: () => AppRoute,
} as any)

const AppDashboardDoctorsIndexRoute = AppDashboardDoctorsIndexImport.update({
  path: '/dashboard/doctors/',
  getParentRoute: () => AppRoute,
} as any)

const AppDoctorDoctorIndexRoute = AppDoctorDoctorIndexImport.update({
  path: '/doctor/',
  getParentRoute: () => AppDoctorRoute,
} as any)

const AppConsultationConsultationsIndexRoute =
  AppConsultationConsultationsIndexImport.update({
    path: '/consultations/',
    getParentRoute: () => AppRoute,
  } as any)

const DashboardDoctorsProfileDoctorIdIndexRoute =
  DashboardDoctorsProfileDoctorIdIndexImport.update({
    path: '/dashboard/doctors/profile/$doctorId/',
    getParentRoute: () => rootRoute,
  } as any)

const AppDashboardChatsDoctorIdIndexRoute =
  AppDashboardChatsDoctorIdIndexImport.update({
    path: '/dashboard/chats/$doctorId/',
    getParentRoute: () => AppRoute,
  } as any)

const AppDoctorDoctorSupportIndexRoute =
  AppDoctorDoctorSupportIndexImport.update({
    path: '/doctor/support/',
    getParentRoute: () => AppDoctorRoute,
  } as any)

const AppDoctorDoctorPatientsIndexRoute =
  AppDoctorDoctorPatientsIndexImport.update({
    path: '/doctor/patients/',
    getParentRoute: () => AppDoctorRoute,
  } as any)

const AppDoctorDoctorMessageIndexRoute =
  AppDoctorDoctorMessageIndexImport.update({
    path: '/doctor/message/',
    getParentRoute: () => AppDoctorRoute,
  } as any)

const AppDoctorDoctorLabIndexRoute = AppDoctorDoctorLabIndexImport.update({
  path: '/doctor/lab/',
  getParentRoute: () => AppDoctorRoute,
} as any)

const AppDoctorDoctorAppointmentsIndexRoute =
  AppDoctorDoctorAppointmentsIndexImport.update({
    path: '/doctor/appointments/',
    getParentRoute: () => AppDoctorRoute,
  } as any)

const AppDashboardDoctorsProfileDoctorIdIndexRoute =
  AppDashboardDoctorsProfileDoctorIdIndexImport.update({
    path: '/dashboard/doctors/profile/$doctorId/',
    getParentRoute: () => AppRoute,
  } as any)

const AppDoctorDoctorMessagePatientIdIndexRoute =
  AppDoctorDoctorMessagePatientIdIndexImport.update({
    path: '/doctor/message/$patientId/',
    getParentRoute: () => AppDoctorRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AppImport
      parentRoute: typeof rootRoute
    }
    '/_doctor': {
      id: '/_doctor'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof DoctorImport
      parentRoute: typeof rootRoute
    }
    '/_pages': {
      id: '/_pages'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof PagesImport
      parentRoute: typeof rootRoute
    }
    '/_app/_doctor': {
      id: '/_app/_doctor'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AppDoctorImport
      parentRoute: typeof AppImport
    }
    '/_pages/_pages': {
      id: '/_pages/_pages'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof PagesPagesImport
      parentRoute: typeof PagesImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardIndexImport
      parentRoute: typeof rootRoute
    }
    '/login/': {
      id: '/login/'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginIndexImport
      parentRoute: typeof rootRoute
    }
    '/_app/dashboard/': {
      id: '/_app/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardIndexImport
      parentRoute: typeof AppImport
    }
    '/_app/login/': {
      id: '/_app/login/'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AppLoginIndexImport
      parentRoute: typeof AppImport
    }
    '/_doctor/doctor/': {
      id: '/_doctor/doctor/'
      path: '/doctor'
      fullPath: '/doctor'
      preLoaderRoute: typeof DoctorDoctorIndexImport
      parentRoute: typeof DoctorImport
    }
    '/_pages/_pages/': {
      id: '/_pages/_pages/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PagesPagesIndexImport
      parentRoute: typeof PagesPagesImport
    }
    '/dashboard/schedule/': {
      id: '/dashboard/schedule/'
      path: '/dashboard/schedule'
      fullPath: '/dashboard/schedule'
      preLoaderRoute: typeof DashboardScheduleIndexImport
      parentRoute: typeof rootRoute
    }
    '/_app/_consultation/consultations/': {
      id: '/_app/_consultation/consultations/'
      path: '/consultations'
      fullPath: '/consultations'
      preLoaderRoute: typeof AppConsultationConsultationsIndexImport
      parentRoute: typeof AppImport
    }
    '/_app/_doctor/doctor/': {
      id: '/_app/_doctor/doctor/'
      path: '/doctor'
      fullPath: '/doctor'
      preLoaderRoute: typeof AppDoctorDoctorIndexImport
      parentRoute: typeof AppDoctorImport
    }
    '/_app/dashboard/doctors/': {
      id: '/_app/dashboard/doctors/'
      path: '/dashboard/doctors'
      fullPath: '/dashboard/doctors'
      preLoaderRoute: typeof AppDashboardDoctorsIndexImport
      parentRoute: typeof AppImport
    }
    '/_app/dashboard/profile/': {
      id: '/_app/dashboard/profile/'
      path: '/dashboard/profile'
      fullPath: '/dashboard/profile'
      preLoaderRoute: typeof AppDashboardProfileIndexImport
      parentRoute: typeof AppImport
    }
    '/_app/dashboard/schedule/': {
      id: '/_app/dashboard/schedule/'
      path: '/dashboard/schedule'
      fullPath: '/dashboard/schedule'
      preLoaderRoute: typeof AppDashboardScheduleIndexImport
      parentRoute: typeof AppImport
    }
    '/_app/dashboard/wallet/': {
      id: '/_app/dashboard/wallet/'
      path: '/dashboard/wallet'
      fullPath: '/dashboard/wallet'
      preLoaderRoute: typeof AppDashboardWalletIndexImport
      parentRoute: typeof AppImport
    }
    '/_doctor/doctor/patients/': {
      id: '/_doctor/doctor/patients/'
      path: '/doctor/patients'
      fullPath: '/doctor/patients'
      preLoaderRoute: typeof DoctorDoctorPatientsIndexImport
      parentRoute: typeof DoctorImport
    }
    '/_app/_doctor/doctor/appointments/': {
      id: '/_app/_doctor/doctor/appointments/'
      path: '/doctor/appointments'
      fullPath: '/doctor/appointments'
      preLoaderRoute: typeof AppDoctorDoctorAppointmentsIndexImport
      parentRoute: typeof AppDoctorImport
    }
    '/_app/_doctor/doctor/lab/': {
      id: '/_app/_doctor/doctor/lab/'
      path: '/doctor/lab'
      fullPath: '/doctor/lab'
      preLoaderRoute: typeof AppDoctorDoctorLabIndexImport
      parentRoute: typeof AppDoctorImport
    }
    '/_app/_doctor/doctor/message/': {
      id: '/_app/_doctor/doctor/message/'
      path: '/doctor/message'
      fullPath: '/doctor/message'
      preLoaderRoute: typeof AppDoctorDoctorMessageIndexImport
      parentRoute: typeof AppDoctorImport
    }
    '/_app/_doctor/doctor/patients/': {
      id: '/_app/_doctor/doctor/patients/'
      path: '/doctor/patients'
      fullPath: '/doctor/patients'
      preLoaderRoute: typeof AppDoctorDoctorPatientsIndexImport
      parentRoute: typeof AppDoctorImport
    }
    '/_app/_doctor/doctor/support/': {
      id: '/_app/_doctor/doctor/support/'
      path: '/doctor/support'
      fullPath: '/doctor/support'
      preLoaderRoute: typeof AppDoctorDoctorSupportIndexImport
      parentRoute: typeof AppDoctorImport
    }
    '/_app/dashboard/chats/$doctorId/': {
      id: '/_app/dashboard/chats/$doctorId/'
      path: '/dashboard/chats/$doctorId'
      fullPath: '/dashboard/chats/$doctorId'
      preLoaderRoute: typeof AppDashboardChatsDoctorIdIndexImport
      parentRoute: typeof AppImport
    }
    '/dashboard/doctors/profile/$doctorId/': {
      id: '/dashboard/doctors/profile/$doctorId/'
      path: '/dashboard/doctors/profile/$doctorId'
      fullPath: '/dashboard/doctors/profile/$doctorId'
      preLoaderRoute: typeof DashboardDoctorsProfileDoctorIdIndexImport
      parentRoute: typeof rootRoute
    }
    '/_app/_doctor/doctor/message/$patientId/': {
      id: '/_app/_doctor/doctor/message/$patientId/'
      path: '/doctor/message/$patientId'
      fullPath: '/doctor/message/$patientId'
      preLoaderRoute: typeof AppDoctorDoctorMessagePatientIdIndexImport
      parentRoute: typeof AppDoctorImport
    }
    '/_app/dashboard/doctors/profile/$doctorId/': {
      id: '/_app/dashboard/doctors/profile/$doctorId/'
      path: '/dashboard/doctors/profile/$doctorId'
      fullPath: '/dashboard/doctors/profile/$doctorId'
      preLoaderRoute: typeof AppDashboardDoctorsProfileDoctorIdIndexImport
      parentRoute: typeof AppImport
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  AppRoute: AppRoute.addChildren({
    AppDoctorRoute: AppDoctorRoute.addChildren({
      AppDoctorDoctorIndexRoute,
      AppDoctorDoctorAppointmentsIndexRoute,
      AppDoctorDoctorLabIndexRoute,
      AppDoctorDoctorMessageIndexRoute,
      AppDoctorDoctorPatientsIndexRoute,
      AppDoctorDoctorSupportIndexRoute,
      AppDoctorDoctorMessagePatientIdIndexRoute,
    }),
    AppDashboardIndexRoute,
    AppLoginIndexRoute,
    AppConsultationConsultationsIndexRoute,
    AppDashboardDoctorsIndexRoute,
    AppDashboardProfileIndexRoute,
    AppDashboardScheduleIndexRoute,
    AppDashboardWalletIndexRoute,
    AppDashboardChatsDoctorIdIndexRoute,
    AppDashboardDoctorsProfileDoctorIdIndexRoute,
  }),
  DoctorRoute: DoctorRoute.addChildren({
    DoctorDoctorIndexRoute,
    DoctorDoctorPatientsIndexRoute,
  }),
  PagesRoute: PagesRoute.addChildren({
    PagesPagesRoute: PagesPagesRoute.addChildren({ PagesPagesIndexRoute }),
  }),
  DashboardIndexRoute,
  LoginIndexRoute,
  DashboardScheduleIndexRoute,
  DashboardDoctorsProfileDoctorIdIndexRoute,
})

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/_app",
        "/_doctor",
        "/_pages",
        "/dashboard/",
        "/login/",
        "/dashboard/schedule/",
        "/dashboard/doctors/profile/$doctorId/"
      ]
    },
    "/_app": {
      "filePath": "_app.tsx",
      "children": [
        "/_app/_doctor",
        "/_app/dashboard/",
        "/_app/login/",
        "/_app/_consultation/consultations/",
        "/_app/dashboard/doctors/",
        "/_app/dashboard/profile/",
        "/_app/dashboard/schedule/",
        "/_app/dashboard/wallet/",
        "/_app/dashboard/chats/$doctorId/",
        "/_app/dashboard/doctors/profile/$doctorId/"
      ]
    },
    "/_doctor": {
      "filePath": "_doctor.tsx",
      "children": [
        "/_doctor/doctor/",
        "/_doctor/doctor/patients/"
      ]
    },
    "/_pages": {
      "filePath": "_pages.tsx",
      "children": [
        "/_pages/_pages"
      ]
    },
    "/_app/_doctor": {
      "filePath": "_app/_doctor.tsx",
      "parent": "/_app",
      "children": [
        "/_app/_doctor/doctor/",
        "/_app/_doctor/doctor/appointments/",
        "/_app/_doctor/doctor/lab/",
        "/_app/_doctor/doctor/message/",
        "/_app/_doctor/doctor/patients/",
        "/_app/_doctor/doctor/support/",
        "/_app/_doctor/doctor/message/$patientId/"
      ]
    },
    "/_pages/_pages": {
      "filePath": "_pages/_pages.tsx",
      "parent": "/_pages",
      "children": [
        "/_pages/_pages/"
      ]
    },
    "/dashboard/": {
      "filePath": "dashboard/index.tsx"
    },
    "/login/": {
      "filePath": "login/index.tsx"
    },
    "/_app/dashboard/": {
      "filePath": "_app/dashboard/index.tsx",
      "parent": "/_app"
    },
    "/_app/login/": {
      "filePath": "_app/login/index.tsx",
      "parent": "/_app"
    },
    "/_doctor/doctor/": {
      "filePath": "_doctor/doctor/index.tsx",
      "parent": "/_doctor"
    },
    "/_pages/_pages/": {
      "filePath": "_pages/_pages/index.tsx",
      "parent": "/_pages/_pages"
    },
    "/dashboard/schedule/": {
      "filePath": "dashboard/schedule/index.tsx"
    },
    "/_app/_consultation/consultations/": {
      "filePath": "_app/_consultation/consultations/index.tsx",
      "parent": "/_app"
    },
    "/_app/_doctor/doctor/": {
      "filePath": "_app/_doctor/doctor/index.tsx",
      "parent": "/_app/_doctor"
    },
    "/_app/dashboard/doctors/": {
      "filePath": "_app/dashboard/doctors/index.tsx",
      "parent": "/_app"
    },
    "/_app/dashboard/profile/": {
      "filePath": "_app/dashboard/profile/index.tsx",
      "parent": "/_app"
    },
    "/_app/dashboard/schedule/": {
      "filePath": "_app/dashboard/schedule/index.tsx",
      "parent": "/_app"
    },
    "/_app/dashboard/wallet/": {
      "filePath": "_app/dashboard/wallet/index.tsx",
      "parent": "/_app"
    },
    "/_doctor/doctor/patients/": {
      "filePath": "_doctor/doctor/patients/index.tsx",
      "parent": "/_doctor"
    },
    "/_app/_doctor/doctor/appointments/": {
      "filePath": "_app/_doctor/doctor/appointments/index.tsx",
      "parent": "/_app/_doctor"
    },
    "/_app/_doctor/doctor/lab/": {
      "filePath": "_app/_doctor/doctor/lab/index.tsx",
      "parent": "/_app/_doctor"
    },
    "/_app/_doctor/doctor/message/": {
      "filePath": "_app/_doctor/doctor/message/index.tsx",
      "parent": "/_app/_doctor"
    },
    "/_app/_doctor/doctor/patients/": {
      "filePath": "_app/_doctor/doctor/patients/index.tsx",
      "parent": "/_app/_doctor"
    },
    "/_app/_doctor/doctor/support/": {
      "filePath": "_app/_doctor/doctor/support/index.tsx",
      "parent": "/_app/_doctor"
    },
    "/_app/dashboard/chats/$doctorId/": {
      "filePath": "_app/dashboard/chats/$doctorId/index.tsx",
      "parent": "/_app"
    },
    "/dashboard/doctors/profile/$doctorId/": {
      "filePath": "dashboard/doctors/profile/$doctorId/index.tsx"
    },
    "/_app/_doctor/doctor/message/$patientId/": {
      "filePath": "_app/_doctor/doctor/message/$patientId/index.tsx",
      "parent": "/_app/_doctor"
    },
    "/_app/dashboard/doctors/profile/$doctorId/": {
      "filePath": "_app/dashboard/doctors/profile/$doctorId/index.tsx",
      "parent": "/_app"
    }
  }
}
ROUTE_MANIFEST_END */
