/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/_index'
import { Route as DoctorImport } from './routes/_doctor'
import { Route as LoginIndexImport } from './routes/login/index'
import { Route as DashboardIndexImport } from './routes/dashboard/index'
import { Route as IndexIndexImport } from './routes/_index/index'
import { Route as DashboardWalletIndexImport } from './routes/dashboard/wallet/index'
import { Route as DashboardScheduleIndexImport } from './routes/dashboard/schedule/index'
import { Route as DashboardProfileIndexImport } from './routes/dashboard/profile/index'
import { Route as DashboardDoctorsIndexImport } from './routes/dashboard/doctors/index'
import { Route as DoctorDoctorIndexImport } from './routes/_doctor/doctor/index'
import { Route as DashboardChatsDoctorIdIndexImport } from './routes/dashboard/chats/$doctorId/index'
import { Route as DoctorDoctorPatientsIndexImport } from './routes/_doctor/doctor/patients/index'
import { Route as DashboardDoctorsProfileDoctorIdIndexImport } from './routes/dashboard/doctors/profile/$doctorId/index'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  id: '/_index',
  getParentRoute: () => rootRoute,
} as any)

const DoctorRoute = DoctorImport.update({
  id: '/_doctor',
  getParentRoute: () => rootRoute,
} as any)

const LoginIndexRoute = LoginIndexImport.update({
  path: '/login/',
  getParentRoute: () => rootRoute,
} as any)

const DashboardIndexRoute = DashboardIndexImport.update({
  path: '/dashboard/',
  getParentRoute: () => rootRoute,
} as any)

const IndexIndexRoute = IndexIndexImport.update({
  path: '/',
  getParentRoute: () => IndexRoute,
} as any)

const DashboardWalletIndexRoute = DashboardWalletIndexImport.update({
  path: '/dashboard/wallet/',
  getParentRoute: () => rootRoute,
} as any)

const DashboardScheduleIndexRoute = DashboardScheduleIndexImport.update({
  path: '/dashboard/schedule/',
  getParentRoute: () => rootRoute,
} as any)

const DashboardProfileIndexRoute = DashboardProfileIndexImport.update({
  path: '/dashboard/profile/',
  getParentRoute: () => rootRoute,
} as any)

const DashboardDoctorsIndexRoute = DashboardDoctorsIndexImport.update({
  path: '/dashboard/doctors/',
  getParentRoute: () => rootRoute,
} as any)

const DoctorDoctorIndexRoute = DoctorDoctorIndexImport.update({
  path: '/doctor/',
  getParentRoute: () => DoctorRoute,
} as any)

const DashboardChatsDoctorIdIndexRoute =
  DashboardChatsDoctorIdIndexImport.update({
    path: '/dashboard/chats/$doctorId/',
    getParentRoute: () => rootRoute,
  } as any)

const DoctorDoctorPatientsIndexRoute = DoctorDoctorPatientsIndexImport.update({
  path: '/doctor/patients/',
  getParentRoute: () => DoctorRoute,
} as any)

const DashboardDoctorsProfileDoctorIdIndexRoute =
  DashboardDoctorsProfileDoctorIdIndexImport.update({
    path: '/dashboard/doctors/profile/$doctorId/',
    getParentRoute: () => rootRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_doctor': {
      id: '/_doctor'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof DoctorImport
      parentRoute: typeof rootRoute
    }
    '/_index': {
      id: '/_index'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/_index/': {
      id: '/_index/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexIndexImport
      parentRoute: typeof IndexImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardIndexImport
      parentRoute: typeof rootRoute
    }
    '/login/': {
      id: '/login/'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginIndexImport
      parentRoute: typeof rootRoute
    }
    '/_doctor/doctor/': {
      id: '/_doctor/doctor/'
      path: '/doctor'
      fullPath: '/doctor'
      preLoaderRoute: typeof DoctorDoctorIndexImport
      parentRoute: typeof DoctorImport
    }
    '/dashboard/doctors/': {
      id: '/dashboard/doctors/'
      path: '/dashboard/doctors'
      fullPath: '/dashboard/doctors'
      preLoaderRoute: typeof DashboardDoctorsIndexImport
      parentRoute: typeof rootRoute
    }
    '/dashboard/profile/': {
      id: '/dashboard/profile/'
      path: '/dashboard/profile'
      fullPath: '/dashboard/profile'
      preLoaderRoute: typeof DashboardProfileIndexImport
      parentRoute: typeof rootRoute
    }
    '/dashboard/schedule/': {
      id: '/dashboard/schedule/'
      path: '/dashboard/schedule'
      fullPath: '/dashboard/schedule'
      preLoaderRoute: typeof DashboardScheduleIndexImport
      parentRoute: typeof rootRoute
    }
    '/dashboard/wallet/': {
      id: '/dashboard/wallet/'
      path: '/dashboard/wallet'
      fullPath: '/dashboard/wallet'
      preLoaderRoute: typeof DashboardWalletIndexImport
      parentRoute: typeof rootRoute
    }
    '/_doctor/doctor/patients/': {
      id: '/_doctor/doctor/patients/'
      path: '/doctor/patients'
      fullPath: '/doctor/patients'
      preLoaderRoute: typeof DoctorDoctorPatientsIndexImport
      parentRoute: typeof DoctorImport
    }
    '/dashboard/chats/$doctorId/': {
      id: '/dashboard/chats/$doctorId/'
      path: '/dashboard/chats/$doctorId'
      fullPath: '/dashboard/chats/$doctorId'
      preLoaderRoute: typeof DashboardChatsDoctorIdIndexImport
      parentRoute: typeof rootRoute
    }
    '/dashboard/doctors/profile/$doctorId/': {
      id: '/dashboard/doctors/profile/$doctorId/'
      path: '/dashboard/doctors/profile/$doctorId'
      fullPath: '/dashboard/doctors/profile/$doctorId'
      preLoaderRoute: typeof DashboardDoctorsProfileDoctorIdIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  DoctorRoute: DoctorRoute.addChildren({
    DoctorDoctorIndexRoute,
    DoctorDoctorPatientsIndexRoute,
  }),
  IndexRoute: IndexRoute.addChildren({ IndexIndexRoute }),
  DashboardIndexRoute,
  LoginIndexRoute,
  DashboardDoctorsIndexRoute,
  DashboardProfileIndexRoute,
  DashboardScheduleIndexRoute,
  DashboardWalletIndexRoute,
  DashboardChatsDoctorIdIndexRoute,
  DashboardDoctorsProfileDoctorIdIndexRoute,
})

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/_doctor",
        "/_index",
        "/dashboard/",
        "/login/",
        "/dashboard/doctors/",
        "/dashboard/profile/",
        "/dashboard/schedule/",
        "/dashboard/wallet/",
        "/dashboard/chats/$doctorId/",
        "/dashboard/doctors/profile/$doctorId/"
      ]
    },
    "/_doctor": {
      "filePath": "_doctor.tsx",
      "children": [
        "/_doctor/doctor/",
        "/_doctor/doctor/patients/"
      ]
    },
    "/_index": {
      "filePath": "_index.tsx",
      "children": [
        "/_index/"
      ]
    },
    "/_index/": {
      "filePath": "_index/index.tsx",
      "parent": "/_index"
    },
    "/dashboard/": {
      "filePath": "dashboard/index.tsx"
    },
    "/login/": {
      "filePath": "login/index.tsx"
    },
    "/_doctor/doctor/": {
      "filePath": "_doctor/doctor/index.tsx",
      "parent": "/_doctor"
    },
    "/dashboard/doctors/": {
      "filePath": "dashboard/doctors/index.tsx"
    },
    "/dashboard/profile/": {
      "filePath": "dashboard/profile/index.tsx"
    },
    "/dashboard/schedule/": {
      "filePath": "dashboard/schedule/index.tsx"
    },
    "/dashboard/wallet/": {
      "filePath": "dashboard/wallet/index.tsx"
    },
    "/_doctor/doctor/patients/": {
      "filePath": "_doctor/doctor/patients/index.tsx",
      "parent": "/_doctor"
    },
    "/dashboard/chats/$doctorId/": {
      "filePath": "dashboard/chats/$doctorId/index.tsx"
    },
    "/dashboard/doctors/profile/$doctorId/": {
      "filePath": "dashboard/doctors/profile/$doctorId/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
