/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/_index'
import { Route as LoginIndexImport } from './routes/login/index'
import { Route as DashboardIndexImport } from './routes/dashboard/index'
import { Route as IndexIndexImport } from './routes/_index/index'
import { Route as ScaffoldConsultationImport } from './routes/scaffold/consultation'
import { Route as DashboardWalletIndexImport } from './routes/dashboard/wallet/index'
import { Route as DashboardProfileIndexImport } from './routes/dashboard/profile/index'
import { Route as DashboardDoctorsIndexImport } from './routes/dashboard/doctors/index'
import { Route as DashboardChatsIndexImport } from './routes/dashboard/chats/index'
import { Route as DashboardChatsDoctorIdIndexImport } from './routes/dashboard/chats/$doctorId/index'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  id: '/_index',
  getParentRoute: () => rootRoute,
} as any)

const LoginIndexRoute = LoginIndexImport.update({
  path: '/login/',
  getParentRoute: () => rootRoute,
} as any)

const DashboardIndexRoute = DashboardIndexImport.update({
  path: '/dashboard/',
  getParentRoute: () => rootRoute,
} as any)

const IndexIndexRoute = IndexIndexImport.update({
  path: '/',
  getParentRoute: () => IndexRoute,
} as any)

const ScaffoldConsultationRoute = ScaffoldConsultationImport.update({
  path: '/scaffold/consultation',
  getParentRoute: () => rootRoute,
} as any)

const DashboardWalletIndexRoute = DashboardWalletIndexImport.update({
  path: '/dashboard/wallet/',
  getParentRoute: () => rootRoute,
} as any)

const DashboardProfileIndexRoute = DashboardProfileIndexImport.update({
  path: '/dashboard/profile/',
  getParentRoute: () => rootRoute,
} as any)

const DashboardDoctorsIndexRoute = DashboardDoctorsIndexImport.update({
  path: '/dashboard/doctors/',
  getParentRoute: () => rootRoute,
} as any)

const DashboardChatsIndexRoute = DashboardChatsIndexImport.update({
  path: '/dashboard/chats/',
  getParentRoute: () => rootRoute,
} as any)

const DashboardChatsDoctorIdIndexRoute =
  DashboardChatsDoctorIdIndexImport.update({
    path: '/dashboard/chats/$doctorId/',
    getParentRoute: () => rootRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_index': {
      id: '/_index'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/scaffold/consultation': {
      id: '/scaffold/consultation'
      path: '/scaffold/consultation'
      fullPath: '/scaffold/consultation'
      preLoaderRoute: typeof ScaffoldConsultationImport
      parentRoute: typeof rootRoute
    }
    '/_index/': {
      id: '/_index/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexIndexImport
      parentRoute: typeof IndexImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardIndexImport
      parentRoute: typeof rootRoute
    }
    '/login/': {
      id: '/login/'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginIndexImport
      parentRoute: typeof rootRoute
    }
    '/dashboard/chats/': {
      id: '/dashboard/chats/'
      path: '/dashboard/chats'
      fullPath: '/dashboard/chats'
      preLoaderRoute: typeof DashboardChatsIndexImport
      parentRoute: typeof rootRoute
    }
    '/dashboard/doctors/': {
      id: '/dashboard/doctors/'
      path: '/dashboard/doctors'
      fullPath: '/dashboard/doctors'
      preLoaderRoute: typeof DashboardDoctorsIndexImport
      parentRoute: typeof rootRoute
    }
    '/dashboard/profile/': {
      id: '/dashboard/profile/'
      path: '/dashboard/profile'
      fullPath: '/dashboard/profile'
      preLoaderRoute: typeof DashboardProfileIndexImport
      parentRoute: typeof rootRoute
    }
    '/dashboard/wallet/': {
      id: '/dashboard/wallet/'
      path: '/dashboard/wallet'
      fullPath: '/dashboard/wallet'
      preLoaderRoute: typeof DashboardWalletIndexImport
      parentRoute: typeof rootRoute
    }
    '/dashboard/chats/$doctorId/': {
      id: '/dashboard/chats/$doctorId/'
      path: '/dashboard/chats/$doctorId'
      fullPath: '/dashboard/chats/$doctorId'
      preLoaderRoute: typeof DashboardChatsDoctorIdIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  IndexRoute: IndexRoute.addChildren({ IndexIndexRoute }),
  ScaffoldConsultationRoute,
  DashboardIndexRoute,
  LoginIndexRoute,
  DashboardChatsIndexRoute,
  DashboardDoctorsIndexRoute,
  DashboardProfileIndexRoute,
  DashboardWalletIndexRoute,
  DashboardChatsDoctorIdIndexRoute,
})

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/_index",
        "/scaffold/consultation",
        "/dashboard/",
        "/login/",
        "/dashboard/chats/",
        "/dashboard/doctors/",
        "/dashboard/profile/",
        "/dashboard/wallet/",
        "/dashboard/chats/$doctorId/"
      ]
    },
    "/_index": {
      "filePath": "_index.tsx",
      "children": [
        "/_index/"
      ]
    },
    "/scaffold/consultation": {
      "filePath": "scaffold/consultation.tsx"
    },
    "/_index/": {
      "filePath": "_index/index.tsx",
      "parent": "/_index"
    },
    "/dashboard/": {
      "filePath": "dashboard/index.tsx"
    },
    "/login/": {
      "filePath": "login/index.tsx"
    },
    "/dashboard/chats/": {
      "filePath": "dashboard/chats/index.tsx"
    },
    "/dashboard/doctors/": {
      "filePath": "dashboard/doctors/index.tsx"
    },
    "/dashboard/profile/": {
      "filePath": "dashboard/profile/index.tsx"
    },
    "/dashboard/wallet/": {
      "filePath": "dashboard/wallet/index.tsx"
    },
    "/dashboard/chats/$doctorId/": {
      "filePath": "dashboard/chats/$doctorId/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
