/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/auth/forget-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description   Initiates the password reset process.
         *
         *       Receives an email address and generates a password reset token if the email exists in the database.
         *       Returns a UID and reset key that will be used to verify the reset request. */
        post: operations["Authentication_initiatePasswordReset"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/forget-password/{uid}/{otp}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description   Confirms password reset request and updates the password.
         *
         *       Validates the provided UID and OTP token, then updates the user's password if:
         *       - The reset token hasn't expired
         *       - The provided passwords match
         *       - The user exists and token is valid */
        post: operations["Authentication_confirmPasswordReset"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/resend-verify-email": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Resend verification email */
        post: operations["Authentication_resendVerificationEmail"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/reset-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** @description Reset password */
        put: operations["Authentication_resetPassword"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/reset-password/send-email": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Send reset password email */
        post: operations["Authentication_sendResetPasswordEmail"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/sign-in": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Sign in user */
        post: operations["Authentication_signIn"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/sign-out": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Sign out user */
        get: operations["Authentication_signOut"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/sign-up": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Sign up new user */
        post: operations["Authentication_signUp"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/verify-email": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Verify email address */
        post: operations["Authentication_verifyEmail"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/consultation/request/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Fetch consultation requests */
        get: operations["Request_fetchConsultationRequests"];
        put?: never;
        /** @description Request consultation */
        post: operations["Request_requestConsultation"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/consultation/request/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Fetch consultation request by ID */
        get: operations["Request_fetchConsultationRequestById"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/consultation/request/{id}/accept": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Accept consultation request */
        post: operations["Request_acceptConsultationRequest"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/consultation/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Fetch consultation by ID */
        get: operations["Consultation_fetchConsultationById"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/consultation/{id}/access-token": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Generate access token */
        get: operations["Consultation_generateAccessToken"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/consultation/{id}/chat": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Add chat */
        post: operations["Consultation_fetchChat"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/consultation/{id}/note": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Add doctors notes */
        post: operations["Consultation_addDoctorsNotes"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/dev/user": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Create a user */
        post: operations["Dev_createUser"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/doctors/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Fetch all doctors */
        get: operations["Doctor_fetchDoctors"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/doctors/profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Fetch doctor profile */
        get: operations["Doctor_fetchProfile"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** @description Update doctor profile */
        patch: operations["Doctor_updateDoctorById"];
        trace?: never;
    };
    "/api/doctors/profile/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Fetch doctor by ID */
        get: operations["Doctor_fetchDoctorById"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/patients/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Fetch all patients */
        get: operations["Patient_fetchPatients"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/patients/profile/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Fetch patient profile */
        get: operations["Patient_fetchProfile"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** @description Update patient profile */
        patch: operations["Patient_updatePatientById"];
        trace?: never;
    };
    "/api/patients/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Fetch patient by ID */
        get: operations["Patient_fetchPatientById"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/waitlist": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["Waitlist_joinWaitlist"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/wallet": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["Wallet_fetchWallet"];
        put?: never;
        post: operations["Wallet_topUpWallet"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/wallet/transactions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["Wallet_fetchWalletTransactions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description Authentication token */
        "Api.Authentication.AuthCredentials": {
            /** @example 745731af4484f323968969eda289aeee */
            access: string;
            /** @example 745731af4484f323968969eda289aeee */
            refresh: string;
            user: components["schemas"]["Api.Doctor.Doctor"];
        };
        "Api.Authentication.ConfirmForgotPasswordPayload": {
            password: components["schemas"]["Password"];
            password2: components["schemas"]["Password"];
        };
        "Api.Authentication.ForgotPasswordPayload": {
            email: components["schemas"]["Email"];
        };
        "Api.Authentication.PasswordResetInitResponse": {
            /** @example Please check your email address for a password reset link */
            message: string;
        };
        "Api.Authentication.ResendVerificationEmailPayload": {
            /** @example mary.slessor@mail.com */
            email: string;
        };
        "Api.Authentication.ResetPasswordPayload": {
            email: components["schemas"]["Email"];
            password: components["schemas"]["Password"];
        };
        "Api.Authentication.SendResetPasswordEmailPayload": {
            email: components["schemas"]["Email"];
        };
        "Api.Authentication.SignInPayload": {
            email: components["schemas"]["Email"];
            password: components["schemas"]["Password"];
        };
        "Api.Authentication.SignOutSuccessful": {
            /** @example Sign out successful */
            message: string;
        };
        "Api.Authentication.SignUpPayload": {
            /** @example Mary */
            first_name: string;
            /** @example Slessor */
            last_name: string;
            email: components["schemas"]["Email"];
            password: components["schemas"]["Password"];
            password2: components["schemas"]["Password"];
            /** @example true */
            is_doctor: boolean;
        };
        "Api.Authentication.VerificationError": {
            /** @example User Registered Successfully, Verification Otp wasn't sent please resend */
            message: string;
        };
        "Api.Authentication.VerificationSuccessful": {
            /** @example Email verified successfully */
            message: string;
        };
        "Api.Authentication.VerifyEmailPayload": {
            /** @example 123456 */
            otp: string;
        };
        "Api.Authentication.WelcomeMessage": {
            /** @example Please check your email address for a verification code */
            message: string;
        };
        "Api.AuthenticationRequiredError": {
            /** @example Authentication required */
            message: string;
        };
        "Api.BadRequestError": {
            /** @example Required fields missing */
            message: string;
        };
        "Api.Consultation.AccessToken": {
            /** @example eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6Ik1hcnkgU2xlc3NvciIsImlhdCI6MTUxNjIzOTAyMn0.UFI1B6pCOrqlpaFHV58dqqTLYCCC8hukJAVY8Wb1Z9o */
            token: string;
        };
        "Api.Consultation.Chat": {
            id: components["schemas"]["Id"];
            /** @example Hello, how are you feeling today? */
            content: string;
            media: components["schemas"]["Api.Consultation.Media"][];
            sent_by: components["schemas"]["Role"];
            created_at: components["schemas"]["DateTime"];
        };
        "Api.Consultation.Consultation": {
            doctors_notes: components["schemas"]["Api.Consultation.DoctorNote"][];
            chats: components["schemas"]["Api.Consultation.Chat"][];
            room_id: components["schemas"]["Id"];
            doctor_id: components["schemas"]["Id"];
            patient_id: components["schemas"]["Id"];
        };
        "Api.Consultation.ConsultationChatAdded": {
            /** @example Chat added */
            message: string;
        };
        "Api.Consultation.ConsultationNoteAdded": {
            /** @example Doctors notes added */
            message: string;
        };
        "Api.Consultation.DoctorNote": {
            id: components["schemas"]["Id"];
            /** @example Patient is suffering from a cold */
            content: string;
            created_at: components["schemas"]["DateTime"];
        };
        "Api.Consultation.Media": {
            /** @enum {string} */
            type: "image" | "video";
            /** @example https://example.com/image.jpg */
            url: string;
        };
        "Api.Consultation.Request.ConsultationRequest": {
            doctor_id: components["schemas"]["Id"];
            patient_id: components["schemas"]["Id"];
            /** @enum {string} */
            status: "pending" | "accepted" | "rejected";
            /** @example I am feeling unwell */
            message: string;
            start_time: components["schemas"]["DateTime"];
            end_time: components["schemas"]["DateTime"];
            created_at: components["schemas"]["DateTime"];
        };
        "Api.Consultation.Request.ConsultationRequestAccepted": {
            /** @enum {string} */
            message: "Consultation request accepted";
        };
        "Api.Consultation.Request.ConsultationRequestCreated": {
            /** @example Consultation request created */
            message: string;
        };
        "Api.Consultation.Request.ConsultationRequestPayload": {
            doctor_id: components["schemas"]["Id"];
            start_time: components["schemas"]["DateTime"];
            end_time: components["schemas"]["DateTime"];
            /** @example I am feeling unwell */
            message: string;
        };
        "Api.Consultation.Request.UnauthorisedRequest": {
            /** @enum {string} */
            message: "Doctor cannot create a consultation request";
        };
        "Api.Dev.UserCreatedMessage": {
            /** @example User created successfully */
            message: string;
        };
        "Api.Doctor.Certification": {
            /** @example MBBS */
            name: string;
            /** @example University of Lagos */
            institution: string;
            /** @example January 2000 */
            date: string;
        };
        "Api.Doctor.Doctor": {
            id: components["schemas"]["Id"];
            /** @example https://example.com/image.jpg */
            profile_picture_url: string;
            /** @example John */
            first_name: string;
            /** @example Doe */
            last_name: string;
            email: components["schemas"]["Email"];
            phone_number: components["schemas"]["PhoneNumber"];
            date_of_birth: components["schemas"]["DateOfBirth"];
            specialization: components["schemas"]["Api.Doctor.Specialization"] | null;
            /** Format: int64 */
            patients_treated: number;
            /** Format: int64 */
            years_of_experience: number;
            /** Format: int64 */
            reviews: number;
            /** Format: double */
            rating: number;
            description: string | null;
            other_names: string | null;
            /**
             * Format: double
             * @example 500
             */
            home_consultation_charge: number;
            /**
             * Format: double
             * @example 100
             */
            video_consultation_charge: number;
            /**
             * Format: double
             * @example 300
             */
            clinic_consultation_charge: number;
            certifications: components["schemas"]["Api.Doctor.Certification"][] | null;
            experiences: components["schemas"]["Api.Doctor.Experience"][] | null;
            working_hours: components["schemas"]["Api.Doctor.WorkingHour"][] | null;
            location: components["schemas"]["Api.Doctor.Location"] | null;
        };
        "Api.Doctor.DoctorNotFoundError": {
            /** @example Doctor not found */
            message: string;
        };
        "Api.Doctor.DoctorProfileUpdatedResponse": {
            /** @example Successful */
            message: string;
        };
        "Api.Doctor.DoctorUpdate": {
            id?: components["schemas"]["Id"];
            /** @example https://example.com/image.jpg */
            profile_picture_url?: string;
            /** @example John */
            first_name?: string;
            /** @example Doe */
            last_name?: string;
            email?: components["schemas"]["Email"];
            phone_number?: components["schemas"]["PhoneNumber"];
            date_of_birth?: components["schemas"]["DateOfBirth"];
            specialization?: components["schemas"]["Api.Doctor.Specialization"] | null;
            /** Format: int64 */
            patients_treated?: number;
            /** Format: int64 */
            years_of_experience?: number;
            /** Format: int64 */
            reviews?: number;
            /** Format: double */
            rating?: number;
            description?: string | null;
            other_names?: string | null;
            /**
             * Format: double
             * @example 500
             */
            home_consultation_charge?: number;
            /**
             * Format: double
             * @example 100
             */
            video_consultation_charge?: number;
            /**
             * Format: double
             * @example 300
             */
            clinic_consultation_charge?: number;
            certifications?: components["schemas"]["Api.Doctor.Certification"][] | null;
            experiences?: components["schemas"]["Api.Doctor.Experience"][] | null;
            working_hours?: components["schemas"]["Api.Doctor.WorkingHour"][] | null;
            location?: components["schemas"]["Api.Doctor.LocationUpdate"] | null;
        };
        "Api.Doctor.Experience": {
            /** @example General Practitioner */
            title: string;
            /** @example University of Lagos */
            institution: string;
            /** @example January 2020 */
            start_date: string;
            /** @example January 2021 */
            end_date?: string;
        };
        "Api.Doctor.Location": {
            /** @example Federal Univeristy Teaching Hospital, Owerri */
            landmark: string;
            /** @example 105 Hospital Road */
            street: string;
            /** @example 5.4836, 7.0336 */
            coordinates?: string;
            /** @example Owerri */
            city: string;
            /** @example Imo */
            state: string;
        };
        "Api.Doctor.LocationUpdate": {
            /** @example Federal Univeristy Teaching Hospital, Owerri */
            landmark?: string;
            /** @example 105 Hospital Road */
            street?: string;
            /** @example 5.4836, 7.0336 */
            coordinates?: string;
            /** @example Owerri */
            city?: string;
            /** @example Imo */
            state?: string;
        };
        "Api.Doctor.PaginatedDoctors": {
            results: {
                /** @example Successful */
                message: string;
                data: components["schemas"]["Api.Doctor.Doctor"][];
            };
            /**
             * Format: int64
             * @example 18
             */
            count: number;
            /** @example http://localhost:8000/api/doctors/?page=3 */
            next: string | null;
            /** @example http://localhost:8000/api/doctors/?page=2 */
            previous: string | null;
        };
        /** @example General Practitioner */
        "Api.Doctor.Specialization": string;
        "Api.Doctor.SuccessMessage": {
            /** @example Successful */
            message: string;
        };
        "Api.Doctor.WorkingHour": {
            /** @enum {string} */
            day: "monday" | "tuesday" | "wednesday" | "thursday" | "friday" | "saturday" | "sunday";
            /** @example 08:00 */
            start_time: string;
            /** @example 17:00 */
            end_time: string;
        };
        "Api.EmailPayload": {
            email: components["schemas"]["Email"];
        };
        "Api.NoTokenProvidedError": {
            /** @example Authentication credentials were not provided or are invalid. */
            message: string;
        };
        "Api.Patient.PaginatedPatients": {
            results: {
                /** @example Successful */
                message: string;
                data: components["schemas"]["Api.Patient.Patient"][];
            };
            /**
             * Format: int64
             * @example 18
             */
            count: number;
            /** @example http://localhost:8000/api/patients?page=3 */
            next: string | null;
            /** @example http://localhost:8000/api/patients?page=2 */
            previous: string | null;
        };
        "Api.Patient.Patient": {
            id: components["schemas"]["Id"];
            /** @example Mary */
            first_name: string;
            /** @example Slessor */
            last_name: string;
            other_names: string | null;
            phone_number: components["schemas"]["PhoneNumber"];
            date_of_birth: components["schemas"]["DateOfBirth"];
            email: components["schemas"]["Email"];
            /** Format: int64 */
            age: number | null;
            profile_picture_url: string;
        };
        "Api.Patient.PatientProfileUpdatedResponse": {
            /** @example Successful */
            message: string;
        };
        "Api.Patient.PatientUpdate": {
            id?: components["schemas"]["Id"];
            /** @example Mary */
            first_name?: string;
            /** @example Slessor */
            last_name?: string;
            other_names?: string | null;
            phone_number?: components["schemas"]["PhoneNumber"];
            date_of_birth?: components["schemas"]["DateOfBirth"];
            email?: components["schemas"]["Email"];
            /** Format: int64 */
            age?: number | null;
            profile_picture_url?: string;
        };
        "Api.UnexpectedError": {
            /** @example An unexpected error occurred */
            message: string;
        };
        "Api.VerifyOtpError": {
            /** @example Invalid verification OTP or OTP has expired. */
            message: string;
        };
        "Api.Waitlist.JoinWaitlistPayload": {
            email: components["schemas"]["Email"];
        };
        "Api.Waitlist.WaitlistAlreadyJoinedError": {
            /** @example You're already in the waitlist */
            message: string;
        };
        "Api.Waitlist.WaitlistJoined": {
            /** @example You have been added to the waitlist */
            message: string;
        };
        "Api.Wallet.Wallet": {
            id: components["schemas"]["Id"];
            /**
             * Format: double
             * @example 5000
             */
            balance: number;
        };
        "Api.Wallet.WalletTopupPayload": {
            /** Format: double */
            amount: number;
        };
        "Api.Wallet.WalletTopupResponse": {
            /** @example https://checkout.paystack.com/5mz7yvom8rzo498 */
            url: string;
        };
        "Api.Wallet.WalletTransaction": {
            id: components["schemas"]["Id"];
            /** @enum {string} */
            type: "credit" | "debit";
            /**
             * Format: double
             * @example 500
             */
            amount: number;
            /** @example Booked consultation */
            description: string;
            /** @example Booked a consultation with Dr. Mark */
            note: string;
            created_at: components["schemas"]["DateTime"];
        };
        /** @example 2000-01-01 */
        DateOfBirth: string;
        /** @example 2021-09-01T12:00:00Z */
        DateTime: string;
        /** @example mary.slessor@mail.com */
        Email: string;
        /** @example f47ac10b-58cc-4372-a567-0e02b2c3d479 */
        Id: string;
        PaginatedMeta: {
            /**
             * Format: int64
             * @example 100
             */
            total: number;
            /**
             * Format: int64
             * @example 1
             */
            page: number;
            /**
             * Format: int64
             * @example 10
             */
            per_page: number;
        };
        /** @example $3cureP@ssw0rd */
        Password: string;
        /** @example +2348123456789 */
        PhoneNumber: string;
        /** @enum {string} */
        Role: "patient" | "doctor";
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    Authentication_initiatePasswordReset: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Api.Authentication.ForgotPasswordPayload"];
            };
        };
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Api.Authentication.PasswordResetInitResponse"];
                };
            };
            /** @description The server could not understand the request due to invalid syntax. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Api.BadRequestError"];
                };
            };
        };
    };
    Authentication_confirmPasswordReset: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                uid: string;
                otp: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Api.Authentication.ConfirmForgotPasswordPayload"];
            };
        };
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Api.Authentication.WelcomeMessage"];
                };
            };
            /** @description The server could not understand the request due to invalid syntax. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Api.BadRequestError"];
                };
            };
            /** @description Server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Api.UnexpectedError"];
                };
            };
        };
    };
    Authentication_resendVerificationEmail: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Api.Authentication.ResendVerificationEmailPayload"];
            };
        };
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Api.Authentication.WelcomeMessage"];
                };
            };
            /** @description The server could not understand the request due to invalid syntax. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Api.BadRequestError"];
                };
            };
            /** @description Server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Api.UnexpectedError"];
                };
            };
        };
    };
    Authentication_resetPassword: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Api.Authentication.ResetPasswordPayload"];
            };
        };
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Api.Authentication.WelcomeMessage"];
                };
            };
            /** @description The server could not understand the request due to invalid syntax. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Api.BadRequestError"];
                };
            };
            /** @description Server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Api.UnexpectedError"];
                };
            };
        };
    };
    Authentication_sendResetPasswordEmail: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Api.Authentication.SendResetPasswordEmailPayload"];
            };
        };
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Api.Authentication.WelcomeMessage"];
                };
            };
            /** @description The server could not understand the request due to invalid syntax. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Api.BadRequestError"];
                };
            };
            /** @description Server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Api.UnexpectedError"];
                };
            };
        };
    };
    Authentication_signIn: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Api.Authentication.SignInPayload"];
            };
        };
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Api.Authentication.AuthCredentials"];
                };
            };
            /** @description The server could not understand the request due to invalid syntax. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Api.BadRequestError"];
                };
            };
            /** @description Server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Api.UnexpectedError"];
                };
            };
        };
    };
    Authentication_signOut: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Api.Authentication.SignOutSuccessful"];
                };
            };
            /** @description Server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Api.UnexpectedError"];
                };
            };
        };
    };
    Authentication_signUp: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Api.Authentication.SignUpPayload"];
            };
        };
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Api.Authentication.WelcomeMessage"];
                };
            };
            /** @description The request has been accepted for processing, but processing has not yet completed. */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Api.Authentication.VerificationError"];
                };
            };
            /** @description The server could not understand the request due to invalid syntax. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Api.BadRequestError"];
                };
            };
            /** @description Server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Api.UnexpectedError"];
                };
            };
        };
    };
    Authentication_verifyEmail: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Api.Authentication.VerifyEmailPayload"];
            };
        };
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Api.Authentication.VerificationSuccessful"];
                };
            };
            /** @description The server could not understand the request due to invalid syntax. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Api.BadRequestError"];
                };
            };
            /** @description The server cannot find the requested resource. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Api.VerifyOtpError"];
                };
            };
            /** @description Server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Api.UnexpectedError"];
                };
            };
        };
    };
    Request_fetchConsultationRequests: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["Api.Consultation.Request.ConsultationRequest"][];
                        meta: components["schemas"]["PaginatedMeta"];
                    };
                };
            };
            /** @description Access is unauthorized. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Api.AuthenticationRequiredError"];
                };
            };
            /** @description Server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Api.UnexpectedError"];
                };
            };
        };
    };
    Request_requestConsultation: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Api.Consultation.Request.ConsultationRequestPayload"];
            };
        };
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Api.Consultation.Request.ConsultationRequestCreated"];
                };
            };
            /** @description The server could not understand the request due to invalid syntax. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Api.BadRequestError"];
                };
            };
            /** @description Access is unauthorized. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Api.AuthenticationRequiredError"];
                };
            };
            /** @description Access is forbidden. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Api.Consultation.Request.UnauthorisedRequest"];
                };
            };
            /** @description Server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Api.UnexpectedError"];
                };
            };
        };
    };
    Request_fetchConsultationRequestById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Api.Consultation.Request.ConsultationRequest"];
                };
            };
            /** @description Access is unauthorized. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Api.AuthenticationRequiredError"];
                };
            };
            /** @description The server cannot find the requested resource. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example Consultation not found */
                        message: string;
                    };
                };
            };
            /** @description Server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Api.UnexpectedError"];
                };
            };
        };
    };
    Request_acceptConsultationRequest: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Api.Consultation.Request.ConsultationRequestAccepted"][];
                };
            };
            /** @description Access is unauthorized. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Api.AuthenticationRequiredError"];
                };
            };
            /** @description The server cannot find the requested resource. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example Consultation not found */
                        message: string;
                    };
                };
            };
            /** @description Server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Api.UnexpectedError"];
                };
            };
        };
    };
    Consultation_fetchConsultationById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Api.Consultation.Consultation"];
                };
            };
            /** @description Access is unauthorized. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Api.AuthenticationRequiredError"];
                };
            };
            /** @description The server cannot find the requested resource. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example Consultation not found */
                        message: string;
                    };
                };
            };
            /** @description Server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Api.UnexpectedError"];
                };
            };
        };
    };
    Consultation_generateAccessToken: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Api.Consultation.AccessToken"];
                };
            };
            /** @description Access is unauthorized. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Api.AuthenticationRequiredError"];
                };
            };
            /** @description The server cannot find the requested resource. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example Consultation not found */
                        message: string;
                    };
                };
            };
            /** @description Server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Api.UnexpectedError"];
                };
            };
        };
    };
    Consultation_fetchChat: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Api.Consultation.ConsultationChatAdded"];
                };
            };
            /** @description Access is unauthorized. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Api.AuthenticationRequiredError"];
                };
            };
            /** @description The server cannot find the requested resource. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example Consultation not found */
                        message: string;
                    };
                };
            };
            /** @description Server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Api.UnexpectedError"];
                };
            };
        };
    };
    Consultation_addDoctorsNotes: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": string;
            };
        };
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Api.Consultation.ConsultationNoteAdded"];
                };
            };
            /** @description Access is unauthorized. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Api.AuthenticationRequiredError"];
                };
            };
            /** @description The server cannot find the requested resource. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example Consultation not found */
                        message: string;
                    };
                };
            };
            /** @description Server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Api.UnexpectedError"];
                };
            };
        };
    };
    Dev_createUser: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Api.Authentication.SignUpPayload"];
            };
        };
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Api.Dev.UserCreatedMessage"];
                };
            };
            /** @description Server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Api.UnexpectedError"];
                };
            };
        };
    };
    Doctor_fetchDoctors: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Api.Doctor.PaginatedDoctors"];
                };
            };
            /** @description Access is unauthorized. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Api.AuthenticationRequiredError"];
                };
            };
            /** @description Server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Api.UnexpectedError"];
                };
            };
        };
    };
    Doctor_fetchProfile: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Api.Doctor.Doctor"];
                };
            };
            /** @description Access is unauthorized. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Api.AuthenticationRequiredError"];
                };
            };
            /** @description Server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Api.UnexpectedError"];
                };
            };
        };
    };
    Doctor_updateDoctorById: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Api.Doctor.DoctorUpdate"];
            };
        };
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Api.Doctor.DoctorProfileUpdatedResponse"];
                };
            };
            /** @description Access is unauthorized. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Api.AuthenticationRequiredError"];
                };
            };
            /** @description Server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Api.UnexpectedError"];
                };
            };
            /** @description An unexpected error response. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Api.Doctor.DoctorNotFoundError"];
                };
            };
        };
    };
    Doctor_fetchDoctorById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Api.Doctor.Doctor"];
                };
            };
            /** @description Access is unauthorized. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Api.AuthenticationRequiredError"];
                };
            };
            /** @description Server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Api.UnexpectedError"];
                };
            };
            /** @description An unexpected error response. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Api.Doctor.DoctorNotFoundError"];
                };
            };
        };
    };
    Patient_fetchPatients: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Api.Patient.PaginatedPatients"];
                };
            };
            /** @description Access is unauthorized. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Api.AuthenticationRequiredError"];
                };
            };
            /** @description Server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Api.UnexpectedError"];
                };
            };
        };
    };
    Patient_fetchProfile: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Api.Patient.Patient"];
                };
            };
            /** @description Access is unauthorized. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Api.AuthenticationRequiredError"];
                };
            };
            /** @description Server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Api.UnexpectedError"];
                };
            };
        };
    };
    Patient_updatePatientById: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Api.Patient.PatientUpdate"];
            };
        };
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Api.Patient.PatientProfileUpdatedResponse"];
                };
            };
            /** @description Access is unauthorized. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Api.AuthenticationRequiredError"];
                };
            };
            /** @description The server cannot find the requested resource. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example Patient not found */
                        message: string;
                    };
                };
            };
            /** @description Server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Api.UnexpectedError"];
                };
            };
        };
    };
    Patient_fetchPatientById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Api.Patient.Patient"];
                };
            };
            /** @description Access is unauthorized. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Api.AuthenticationRequiredError"];
                };
            };
            /** @description The server cannot find the requested resource. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example Patient not found */
                        message: string;
                    };
                };
            };
            /** @description Server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Api.UnexpectedError"];
                };
            };
        };
    };
    Waitlist_joinWaitlist: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Api.Waitlist.JoinWaitlistPayload"];
            };
        };
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Api.Waitlist.WaitlistJoined"];
                };
            };
            /** @description Client error */
            406: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Api.Waitlist.WaitlistAlreadyJoinedError"];
                };
            };
            /** @description Server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Api.UnexpectedError"];
                };
            };
        };
    };
    Wallet_fetchWallet: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Api.Wallet.Wallet"];
                };
            };
            /** @description Access is unauthorized. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Api.AuthenticationRequiredError"];
                };
            };
            /** @description Server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Api.UnexpectedError"];
                };
            };
        };
    };
    Wallet_topUpWallet: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Api.Wallet.WalletTopupPayload"];
            };
        };
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Api.Wallet.WalletTopupResponse"];
                };
            };
            /** @description The server could not understand the request due to invalid syntax. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Api.BadRequestError"];
                };
            };
            /** @description Access is unauthorized. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Api.AuthenticationRequiredError"];
                };
            };
            /** @description Server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Api.UnexpectedError"];
                };
            };
        };
    };
    Wallet_fetchWalletTransactions: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["Api.Wallet.WalletTransaction"][];
                        meta: components["schemas"]["PaginatedMeta"];
                    };
                };
            };
            /** @description Access is unauthorized. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Api.AuthenticationRequiredError"];
                };
            };
            /** @description Server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Api.UnexpectedError"];
                };
            };
        };
    };
}
