# Generated by Django 5.0.6 on 2025-02-03 23:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0002_patientprofile_profile_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patientprofile',
            old_name='profile_image',
            new_name='profile_picture_url',
        ),
    ]
