# Generated by Django 5.1.3 on 2025-02-24 23:41

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0003_rename_profile_image_patientprofile_profile_picture_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientprofile',
            name='date_of_birth',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='patientprofile',
            name='phone_number',
            field=models.TextField(blank=True, null=True),
        ),
    ]
