# Generated by Django 5.0.6 on 2025-02-03 22:58

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorprofile',
            name='profile_image',
            field=cloudinary.models.CloudinaryField(default='.cloudinary.com/dlanhtzbw/image/upload/v1675343188/Telegram Clone/no-profile_aknbeq.jpg', max_length=255, verbose_name='image'),
        ),
    ]
