# Generated by Django 5.0.6 on 2025-02-03 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0002_doctorprofile_profile_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctorprofile',
            old_name='profile_image',
            new_name='profile_picture_url',
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='certifications',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='clinic_consultation_charge',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='experiences',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='home_consultation_charge',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='location',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='patients_treated',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='rating',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='reviews',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='specialization',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='video_consultation_charge',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='working_hours',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='years_of_experience',
            field=models.IntegerField(default=0),
        ),
    ]
