# Generated by Django 5.1.3 on 2025-02-24 23:41

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0003_rename_profile_image_doctorprofile_profile_picture_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorprofile',
            name='phone_number',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='doctorprofile',
            name='profile_picture_url',
            field=cloudinary.models.CloudinaryField(default='https://res.cloudinary.com/dlanhtzbw/image/upload/v1675343188/Telegram Clone/no-profile_aknbeq.jpg', max_length=255, verbose_name='image'),
        ),
    ]
