# Generated by Django 5.1.3 on 2025-03-22 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0004_alter_doctorprofile_phone_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorprofile',
            name='profile_picture_url',
            field=models.TextField(default='res.cloudinary.com/dlanhtzbw/image/upload/v1675343188/Telegram Clone/no-profile_aknbeq.jpg'),
        ),
    ]
