/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as AboutImport } from './routes/about'
import { Route as IndexImport } from './routes/index'
import { Route as AppPharmacyIndexImport } from './routes/_app/pharmacy/index'
import { Route as AppHowToUseIndexImport } from './routes/_app/how-to-use/index'
import { Route as AppContactUsIndexImport } from './routes/_app/contact-us/index'
import { Route as AppChatSupportIndexImport } from './routes/_app/chat-support/index'
import { Route as AppCareServicesIndexImport } from './routes/_app/care-services/index'
import { Route as AppAboutUsIndexImport } from './routes/_app/about-us/index'
import { Route as AppExtrasVirtualConsultationsImport } from './routes/_app/_extras/virtual-consultations'
import { Route as AppExtrasSpecialtiesImport } from './routes/_app/_extras/specialties'
import { Route as AppExtrasSignupImport } from './routes/_app/_extras/signup'
import { Route as AppExtrasGetTheAppImport } from './routes/_app/_extras/get-the-app'

// Create/Update Routes

const AboutRoute = AboutImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const AppPharmacyIndexRoute = AppPharmacyIndexImport.update({
  id: '/_app/pharmacy/',
  path: '/pharmacy/',
  getParentRoute: () => rootRoute,
} as any)

const AppHowToUseIndexRoute = AppHowToUseIndexImport.update({
  id: '/_app/how-to-use/',
  path: '/how-to-use/',
  getParentRoute: () => rootRoute,
} as any)

const AppContactUsIndexRoute = AppContactUsIndexImport.update({
  id: '/_app/contact-us/',
  path: '/contact-us/',
  getParentRoute: () => rootRoute,
} as any)

const AppChatSupportIndexRoute = AppChatSupportIndexImport.update({
  id: '/_app/chat-support/',
  path: '/chat-support/',
  getParentRoute: () => rootRoute,
} as any)

const AppCareServicesIndexRoute = AppCareServicesIndexImport.update({
  id: '/_app/care-services/',
  path: '/care-services/',
  getParentRoute: () => rootRoute,
} as any)

const AppAboutUsIndexRoute = AppAboutUsIndexImport.update({
  id: '/_app/about-us/',
  path: '/about-us/',
  getParentRoute: () => rootRoute,
} as any)

const AppExtrasVirtualConsultationsRoute =
  AppExtrasVirtualConsultationsImport.update({
    id: '/_app/_extras/virtual-consultations',
    path: '/virtual-consultations',
    getParentRoute: () => rootRoute,
  } as any)

const AppExtrasSpecialtiesRoute = AppExtrasSpecialtiesImport.update({
  id: '/_app/_extras/specialties',
  path: '/specialties',
  getParentRoute: () => rootRoute,
} as any)

const AppExtrasSignupRoute = AppExtrasSignupImport.update({
  id: '/_app/_extras/signup',
  path: '/signup',
  getParentRoute: () => rootRoute,
} as any)

const AppExtrasGetTheAppRoute = AppExtrasGetTheAppImport.update({
  id: '/_app/_extras/get-the-app',
  path: '/get-the-app',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutImport
      parentRoute: typeof rootRoute
    }
    '/_app/_extras/get-the-app': {
      id: '/_app/_extras/get-the-app'
      path: '/get-the-app'
      fullPath: '/get-the-app'
      preLoaderRoute: typeof AppExtrasGetTheAppImport
      parentRoute: typeof rootRoute
    }
    '/_app/_extras/signup': {
      id: '/_app/_extras/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof AppExtrasSignupImport
      parentRoute: typeof rootRoute
    }
    '/_app/_extras/specialties': {
      id: '/_app/_extras/specialties'
      path: '/specialties'
      fullPath: '/specialties'
      preLoaderRoute: typeof AppExtrasSpecialtiesImport
      parentRoute: typeof rootRoute
    }
    '/_app/_extras/virtual-consultations': {
      id: '/_app/_extras/virtual-consultations'
      path: '/virtual-consultations'
      fullPath: '/virtual-consultations'
      preLoaderRoute: typeof AppExtrasVirtualConsultationsImport
      parentRoute: typeof rootRoute
    }
    '/_app/about-us/': {
      id: '/_app/about-us/'
      path: '/about-us'
      fullPath: '/about-us'
      preLoaderRoute: typeof AppAboutUsIndexImport
      parentRoute: typeof rootRoute
    }
    '/_app/care-services/': {
      id: '/_app/care-services/'
      path: '/care-services'
      fullPath: '/care-services'
      preLoaderRoute: typeof AppCareServicesIndexImport
      parentRoute: typeof rootRoute
    }
    '/_app/chat-support/': {
      id: '/_app/chat-support/'
      path: '/chat-support'
      fullPath: '/chat-support'
      preLoaderRoute: typeof AppChatSupportIndexImport
      parentRoute: typeof rootRoute
    }
    '/_app/contact-us/': {
      id: '/_app/contact-us/'
      path: '/contact-us'
      fullPath: '/contact-us'
      preLoaderRoute: typeof AppContactUsIndexImport
      parentRoute: typeof rootRoute
    }
    '/_app/how-to-use/': {
      id: '/_app/how-to-use/'
      path: '/how-to-use'
      fullPath: '/how-to-use'
      preLoaderRoute: typeof AppHowToUseIndexImport
      parentRoute: typeof rootRoute
    }
    '/_app/pharmacy/': {
      id: '/_app/pharmacy/'
      path: '/pharmacy'
      fullPath: '/pharmacy'
      preLoaderRoute: typeof AppPharmacyIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/get-the-app': typeof AppExtrasGetTheAppRoute
  '/signup': typeof AppExtrasSignupRoute
  '/specialties': typeof AppExtrasSpecialtiesRoute
  '/virtual-consultations': typeof AppExtrasVirtualConsultationsRoute
  '/about-us': typeof AppAboutUsIndexRoute
  '/care-services': typeof AppCareServicesIndexRoute
  '/chat-support': typeof AppChatSupportIndexRoute
  '/contact-us': typeof AppContactUsIndexRoute
  '/how-to-use': typeof AppHowToUseIndexRoute
  '/pharmacy': typeof AppPharmacyIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/get-the-app': typeof AppExtrasGetTheAppRoute
  '/signup': typeof AppExtrasSignupRoute
  '/specialties': typeof AppExtrasSpecialtiesRoute
  '/virtual-consultations': typeof AppExtrasVirtualConsultationsRoute
  '/about-us': typeof AppAboutUsIndexRoute
  '/care-services': typeof AppCareServicesIndexRoute
  '/chat-support': typeof AppChatSupportIndexRoute
  '/contact-us': typeof AppContactUsIndexRoute
  '/how-to-use': typeof AppHowToUseIndexRoute
  '/pharmacy': typeof AppPharmacyIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/_app/_extras/get-the-app': typeof AppExtrasGetTheAppRoute
  '/_app/_extras/signup': typeof AppExtrasSignupRoute
  '/_app/_extras/specialties': typeof AppExtrasSpecialtiesRoute
  '/_app/_extras/virtual-consultations': typeof AppExtrasVirtualConsultationsRoute
  '/_app/about-us/': typeof AppAboutUsIndexRoute
  '/_app/care-services/': typeof AppCareServicesIndexRoute
  '/_app/chat-support/': typeof AppChatSupportIndexRoute
  '/_app/contact-us/': typeof AppContactUsIndexRoute
  '/_app/how-to-use/': typeof AppHowToUseIndexRoute
  '/_app/pharmacy/': typeof AppPharmacyIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/get-the-app'
    | '/signup'
    | '/specialties'
    | '/virtual-consultations'
    | '/about-us'
    | '/care-services'
    | '/chat-support'
    | '/contact-us'
    | '/how-to-use'
    | '/pharmacy'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/get-the-app'
    | '/signup'
    | '/specialties'
    | '/virtual-consultations'
    | '/about-us'
    | '/care-services'
    | '/chat-support'
    | '/contact-us'
    | '/how-to-use'
    | '/pharmacy'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/_app/_extras/get-the-app'
    | '/_app/_extras/signup'
    | '/_app/_extras/specialties'
    | '/_app/_extras/virtual-consultations'
    | '/_app/about-us/'
    | '/_app/care-services/'
    | '/_app/chat-support/'
    | '/_app/contact-us/'
    | '/_app/how-to-use/'
    | '/_app/pharmacy/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AppExtrasGetTheAppRoute: typeof AppExtrasGetTheAppRoute
  AppExtrasSignupRoute: typeof AppExtrasSignupRoute
  AppExtrasSpecialtiesRoute: typeof AppExtrasSpecialtiesRoute
  AppExtrasVirtualConsultationsRoute: typeof AppExtrasVirtualConsultationsRoute
  AppAboutUsIndexRoute: typeof AppAboutUsIndexRoute
  AppCareServicesIndexRoute: typeof AppCareServicesIndexRoute
  AppChatSupportIndexRoute: typeof AppChatSupportIndexRoute
  AppContactUsIndexRoute: typeof AppContactUsIndexRoute
  AppHowToUseIndexRoute: typeof AppHowToUseIndexRoute
  AppPharmacyIndexRoute: typeof AppPharmacyIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AppExtrasGetTheAppRoute: AppExtrasGetTheAppRoute,
  AppExtrasSignupRoute: AppExtrasSignupRoute,
  AppExtrasSpecialtiesRoute: AppExtrasSpecialtiesRoute,
  AppExtrasVirtualConsultationsRoute: AppExtrasVirtualConsultationsRoute,
  AppAboutUsIndexRoute: AppAboutUsIndexRoute,
  AppCareServicesIndexRoute: AppCareServicesIndexRoute,
  AppChatSupportIndexRoute: AppChatSupportIndexRoute,
  AppContactUsIndexRoute: AppContactUsIndexRoute,
  AppHowToUseIndexRoute: AppHowToUseIndexRoute,
  AppPharmacyIndexRoute: AppPharmacyIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/about",
        "/_app/_extras/get-the-app",
        "/_app/_extras/signup",
        "/_app/_extras/specialties",
        "/_app/_extras/virtual-consultations",
        "/_app/about-us/",
        "/_app/care-services/",
        "/_app/chat-support/",
        "/_app/contact-us/",
        "/_app/how-to-use/",
        "/_app/pharmacy/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/about": {
      "filePath": "about.tsx"
    },
    "/_app/_extras/get-the-app": {
      "filePath": "_app/_extras/get-the-app.tsx"
    },
    "/_app/_extras/signup": {
      "filePath": "_app/_extras/signup.tsx"
    },
    "/_app/_extras/specialties": {
      "filePath": "_app/_extras/specialties.tsx"
    },
    "/_app/_extras/virtual-consultations": {
      "filePath": "_app/_extras/virtual-consultations.tsx"
    },
    "/_app/about-us/": {
      "filePath": "_app/about-us/index.tsx"
    },
    "/_app/care-services/": {
      "filePath": "_app/care-services/index.tsx"
    },
    "/_app/chat-support/": {
      "filePath": "_app/chat-support/index.tsx"
    },
    "/_app/contact-us/": {
      "filePath": "_app/contact-us/index.tsx"
    },
    "/_app/how-to-use/": {
      "filePath": "_app/how-to-use/index.tsx"
    },
    "/_app/pharmacy/": {
      "filePath": "_app/pharmacy/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
